// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

type AddServiceInput struct {
	Name           *string `json:"name,omitempty"`
	Repository     *string `json:"repository,omitempty"`
	ContextPath    *string `json:"contextPath,omitempty"`
	InstallationID *string `json:"installationId,omitempty"`
	Image          *string `json:"image,omitempty"`
}

type AutoscalingInput struct {
	Enabled     bool `json:"enabled"`
	MinReplicas int  `json:"minReplicas"`
	MaxReplicas int  `json:"maxReplicas"`
	TargetCPU   int  `json:"targetCPU"`
}

type AutoscalingSettings struct {
	MinReplicas int `json:"minReplicas"`
	MaxReplicas int `json:"maxReplicas"`
	TargetCPU   int `json:"targetCpu"`
}

type BillingPortalURL struct {
	URL string `json:"url"`
}

type BillingSubscription struct {
	Plan              *Plan              `json:"plan,omitempty"`
	Status            SubscriptionStatus `json:"status"`
	CurrentPeriodEnd  time.Time          `json:"currentPeriodEnd"`
	CreditAmountCents int                `json:"creditAmountCents"`
	CreditExpiry      *time.Time         `json:"creditExpiry,omitempty"`
	HasPaymentMethod  bool               `json:"hasPaymentMethod"`
}

type Build struct {
	ID         string      `json:"id"`
	Status     BuildStatus `json:"status"`
	StartedAt  time.Time   `json:"startedAt"`
	FinishedAt *time.Time  `json:"finishedAt,omitempty"`
}

type CheckoutSession struct {
	URL string `json:"url"`
}

type CreateDatabaseInput struct {
	Environment platform.EnvironmentID `json:"environment"`
	Name        string                 `json:"name"`
	Version     *string                `json:"version,omitempty"`
	Instances   *int                   `json:"instances,omitempty"`
	Size        *string                `json:"size,omitempty"`
}

type CreateEnvironmentInput struct {
	Project         platform.ProjectID      `json:"project"`
	Name            string                  `json:"name"`
	FromEnvironment *platform.EnvironmentID `json:"fromEnvironment,omitempty"`
	Tier            *ResourceTier           `json:"tier,omitempty"`
}

type CreateProjectInput struct {
	// Human-readable project name (e.g. "My API").
	Name string `json:"name"`
	// Optional URL-safe slug. Auto-derived from name if omitted.
	ID *string `json:"id,omitempty"`
}

type CreateWorkspaceCheckoutInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Plan Plan   `json:"plan"`
}

type Database struct {
	ID        platform.DatabaseID `json:"id"`
	Name      string              `json:"name"`
	Version   string              `json:"version"`
	Instances int                 `json:"instances"`
	Status    DatabaseStatus      `json:"status"`
	Size      string              `json:"size"`
	CreatedAt time.Time           `json:"createdAt"`
}

type DatabaseColumn struct {
	Name       string `json:"name"`
	Type       string `json:"type"`
	Nullable   bool   `json:"nullable"`
	PrimaryKey bool   `json:"primaryKey"`
}

type DatabaseCredentials struct {
	Host     string `json:"host"`
	Port     string `json:"port"`
	Dbname   string `json:"dbname"`
	User     string `json:"user"`
	Password string `json:"password"`
	URI      string `json:"uri"`
}

// A reference to a CNPG database secret key (resolved at pod startup via secretKeyRef).
type DatabaseRef struct {
	Database platform.DatabaseID `json:"database"`
	Key      string              `json:"key"`
}

type DatabaseRefInput struct {
	Database platform.DatabaseID `json:"database"`
	Key      string              `json:"key"`
}

type DatabaseTable struct {
	Name          string           `json:"name"`
	Schema        string           `json:"schema"`
	EstimatedRows int              `json:"estimatedRows"`
	Columns       []DatabaseColumn `json:"columns"`
}

type DatabaseTableData struct {
	Columns            []string    `json:"columns"`
	Rows               [][]*string `json:"rows"`
	TotalEstimatedRows int         `json:"totalEstimatedRows"`
}

type Deployment struct {
	ID                   platform.DeploymentID `json:"id"`
	Image                string                `json:"image"`
	ImageDigest          *string               `json:"imageDigest,omitempty"`
	Commit               string                `json:"commit"`
	CommitMessage        string                `json:"commitMessage"`
	Ref                  string                `json:"ref"`
	SourceURL            string                `json:"sourceUrl"`
	ContextPath          string                `json:"contextPath"`
	Resources            *Resources            `json:"resources"`
	Command              string                `json:"command"`
	BuildID              string                `json:"buildId"`
	DeployedBy           string                `json:"deployedBy"`
	Status               DeploymentStatus      `json:"status"`
	Replicas             *ReplicaCount         `json:"replicas"`
	CreatedAt            time.Time             `json:"createdAt"`
	GitHubInstallationID string                `json:"-"`
}

type DetectedService struct {
	Name          string `json:"name"`
	Language      string `json:"language"`
	Framework     string `json:"framework"`
	StartCommand  string `json:"startCommand"`
	SuggestedPort int    `json:"suggestedPort"`
}

type DNSRecord struct {
	Type  DNSRecordType `json:"type"`
	Host  string        `json:"host"`
	Value string        `json:"value"`
}

type DNSState struct {
	Status          DNSStatus   `json:"status"`
	RequiredRecords []DNSRecord `json:"requiredRecords"`
}

type Endpoint struct {
	Host     string       `json:"host"`
	Port     int          `json:"port"`
	Protocol Protocol     `json:"protocol"`
	Type     EndpointType `json:"type"`
	DNS      *DNSState    `json:"dns"`
	TLS      TLSStatus    `json:"tls"`
}

type Environment struct {
	ID           platform.EnvironmentID `json:"id"`
	Name         string                 `json:"name"`
	ResourceTier ResourceTier           `json:"resourceTier"`
	Services     []Service              `json:"services"`
	Databases    []Database             `json:"databases"`
}

type EnvironmentResources struct {
	Tier       ResourceTier        `json:"tier"`
	Allocation *ResourceAllocation `json:"allocation"`
}

type GitHubInstallation struct {
	ID               string            `json:"id"`
	AccountLogin     string            `json:"accountLogin"`
	AccountAvatarURL string            `json:"accountAvatarUrl"`
	AccountType      GitHubAccountType `json:"accountType"`
}

type GitHubRepository struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	FullName      string `json:"fullName"`
	HTMLURL       string `json:"htmlUrl"`
	DefaultBranch string `json:"defaultBranch"`
	Private       bool   `json:"private"`
}

// A container image from a public registry (Docker Hub).
type ImageSearchResult struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	StarCount   int    `json:"starCount"`
	PullCount   int    `json:"pullCount"`
	Official    bool   `json:"official"`
}

type InviteMemberInput struct {
	Email string        `json:"email"`
	Role  WorkspaceRole `json:"role"`
}

type Mutation struct {
}

type Project struct {
	ID           platform.ProjectID `json:"id"`
	Name         string             `json:"name"`
	Environments []Environment      `json:"environments"`
}

type Query struct {
}

type QueryResult struct {
	Columns      []string    `json:"columns"`
	Rows         [][]*string `json:"rows"`
	AffectedRows int         `json:"affectedRows"`
}

type ReplicaCount struct {
	Desired int `json:"desired"`
	Ready   int `json:"ready"`
}

type ResourceAllocation struct {
	CPUMillicores int `json:"cpuMillicores"`
	MemoryMb      int `json:"memoryMB"`
	DiskMb        int `json:"diskMB"`
}

type Resources struct {
	CPU    string `json:"cpu"`
	Memory string `json:"memory"`
}

type Service struct {
	ID                platform.ServiceID   `json:"id"`
	Name              string               `json:"name"`
	Status            ServiceStatus        `json:"status"`
	Replicas          *ReplicaCount        `json:"replicas"`
	Autoscaling       *AutoscalingSettings `json:"autoscaling,omitempty"`
	Port              int                  `json:"port"`
	Endpoints         []Endpoint           `json:"endpoints"`
	SourceURL         string               `json:"sourceUrl"`
	ContextPath       string               `json:"contextPath"`
	Resources         *Resources           `json:"resources"`
	Command           string               `json:"command"`
	DefaultCommand    string               `json:"defaultCommand"`
	ActiveDeployment  *Deployment          `json:"activeDeployment,omitempty"`
	Deployments       []Deployment         `json:"deployments"`
	Builds            []Build              `json:"builds"`
	LastDeployedAt    *time.Time           `json:"lastDeployedAt,omitempty"`
	CreatedAt         time.Time            `json:"createdAt"`
	PlatformEndpoints []platform.Endpoint  `json:"-"`
}

type ServiceLogEntry struct {
	// Log line text. Prefixed with [pod-suffix] when multiple replicas exist.
	Line string `json:"line"`
	// Name of the pod that produced this line.
	Pod string `json:"pod"`
}

type ServiceVariable struct {
	Key         string       `json:"key"`
	Value       string       `json:"value"`
	FromShared  bool         `json:"fromShared"`
	DatabaseRef *DatabaseRef `json:"databaseRef,omitempty"`
}

type ServiceVariableInput struct {
	Key string `json:"key"`
	// Direct value. Required when no ref is set.
	Value *string `json:"value,omitempty"`
	// If true, value is resolved from the shared variable with the same key.
	FromShared *bool `json:"fromShared,omitempty"`
	// Reference to a database secret key.
	DatabaseRef *DatabaseRefInput `json:"databaseRef,omitempty"`
}

type SetEnvironmentResourcesInput struct {
	Environment   platform.EnvironmentID `json:"environment"`
	Tier          ResourceTier           `json:"tier"`
	CPUMillicores int                    `json:"cpuMillicores"`
	MemoryMb      int                    `json:"memoryMB"`
	DiskMb        int                    `json:"diskMB"`
}

type SetServiceScalingInput struct {
	Service     platform.ServiceID `json:"service"`
	Replicas    int                `json:"replicas"`
	Autoscaling *AutoscalingInput  `json:"autoscaling,omitempty"`
}

type Subscription struct {
}

type UpdateMemberRoleInput struct {
	UserID string        `json:"userId"`
	Role   WorkspaceRole `json:"role"`
}

type UpdateWorkspaceInput struct {
	Name string `json:"name"`
}

type UsageSummary struct {
	ResourceCostCents   int `json:"resourceCostCents"`
	CreditsCents        int `json:"creditsCents"`
	EstimatedTotalCents int `json:"estimatedTotalCents"`
}

type User struct {
	Name       *string               `json:"name,omitempty"`
	Email      *string               `json:"email,omitempty"`
	AvatarURL  string                `json:"avatarUrl"`
	Workspaces []WorkspaceMembership `json:"workspaces"`
}

type Variable struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type VariableInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Volume struct {
	ID            platform.VolumeID `json:"id"`
	Name          string            `json:"name"`
	Size          string            `json:"size"`
	RequestedSize string            `json:"requestedSize"`
	UsedBytes     int               `json:"usedBytes"`
	CapacityBytes int               `json:"capacityBytes"`
}

type Workspace struct {
	ID        string            `json:"id"`
	Name      string            `json:"name"`
	Personal  bool              `json:"personal"`
	Suspended bool              `json:"suspended"`
	Members   []WorkspaceMember `json:"members"`
}

type WorkspaceMember struct {
	ID    string        `json:"id"`
	Email string        `json:"email"`
	Name  *string       `json:"name,omitempty"`
	Role  WorkspaceRole `json:"role"`
}

type WorkspaceMembership struct {
	Workspace string        `json:"workspace"`
	Role      WorkspaceRole `json:"role"`
}

type BuildStatus string

const (
	BuildStatusQueued    BuildStatus = "QUEUED"
	BuildStatusRunning   BuildStatus = "RUNNING"
	BuildStatusSucceeded BuildStatus = "SUCCEEDED"
	BuildStatusFailed    BuildStatus = "FAILED"
	BuildStatusCancelled BuildStatus = "CANCELLED"
)

var AllBuildStatus = []BuildStatus{
	BuildStatusQueued,
	BuildStatusRunning,
	BuildStatusSucceeded,
	BuildStatusFailed,
	BuildStatusCancelled,
}

func (e BuildStatus) IsValid() bool {
	switch e {
	case BuildStatusQueued, BuildStatusRunning, BuildStatusSucceeded, BuildStatusFailed, BuildStatusCancelled:
		return true
	}
	return false
}

func (e BuildStatus) String() string {
	return string(e)
}

func (e *BuildStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BuildStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BuildStatus", str)
	}
	return nil
}

func (e BuildStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BuildStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BuildStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DatabaseStatus string

const (
	DatabaseStatusHealthy  DatabaseStatus = "HEALTHY"
	DatabaseStatusDegraded DatabaseStatus = "DEGRADED"
	DatabaseStatusFailed   DatabaseStatus = "FAILED"
	DatabaseStatusPending  DatabaseStatus = "PENDING"
	DatabaseStatusStopped  DatabaseStatus = "STOPPED"
)

var AllDatabaseStatus = []DatabaseStatus{
	DatabaseStatusHealthy,
	DatabaseStatusDegraded,
	DatabaseStatusFailed,
	DatabaseStatusPending,
	DatabaseStatusStopped,
}

func (e DatabaseStatus) IsValid() bool {
	switch e {
	case DatabaseStatusHealthy, DatabaseStatusDegraded, DatabaseStatusFailed, DatabaseStatusPending, DatabaseStatusStopped:
		return true
	}
	return false
}

func (e DatabaseStatus) String() string {
	return string(e)
}

func (e *DatabaseStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DatabaseStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DatabaseStatus", str)
	}
	return nil
}

func (e DatabaseStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DatabaseStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DatabaseStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DeploymentStatus string

const (
	DeploymentStatusDeploying  DeploymentStatus = "DEPLOYING"
	DeploymentStatusActive     DeploymentStatus = "ACTIVE"
	DeploymentStatusSuperseded DeploymentStatus = "SUPERSEDED"
	DeploymentStatusFailed     DeploymentStatus = "FAILED"
)

var AllDeploymentStatus = []DeploymentStatus{
	DeploymentStatusDeploying,
	DeploymentStatusActive,
	DeploymentStatusSuperseded,
	DeploymentStatusFailed,
}

func (e DeploymentStatus) IsValid() bool {
	switch e {
	case DeploymentStatusDeploying, DeploymentStatusActive, DeploymentStatusSuperseded, DeploymentStatusFailed:
		return true
	}
	return false
}

func (e DeploymentStatus) String() string {
	return string(e)
}

func (e *DeploymentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeploymentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeploymentStatus", str)
	}
	return nil
}

func (e DeploymentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DeploymentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DeploymentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DNSRecordType string

const (
	DNSRecordTypeTxt   DNSRecordType = "TXT"
	DNSRecordTypeCname DNSRecordType = "CNAME"
	DNSRecordTypeA     DNSRecordType = "A"
)

var AllDNSRecordType = []DNSRecordType{
	DNSRecordTypeTxt,
	DNSRecordTypeCname,
	DNSRecordTypeA,
}

func (e DNSRecordType) IsValid() bool {
	switch e {
	case DNSRecordTypeTxt, DNSRecordTypeCname, DNSRecordTypeA:
		return true
	}
	return false
}

func (e DNSRecordType) String() string {
	return string(e)
}

func (e *DNSRecordType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DNSRecordType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DnsRecordType", str)
	}
	return nil
}

func (e DNSRecordType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DNSRecordType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DNSRecordType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DNSStatus string

const (
	DNSStatusValid         DNSStatus = "VALID"
	DNSStatusPending       DNSStatus = "PENDING"
	DNSStatusMisconfigured DNSStatus = "MISCONFIGURED"
	DNSStatusError         DNSStatus = "ERROR"
)

var AllDNSStatus = []DNSStatus{
	DNSStatusValid,
	DNSStatusPending,
	DNSStatusMisconfigured,
	DNSStatusError,
}

func (e DNSStatus) IsValid() bool {
	switch e {
	case DNSStatusValid, DNSStatusPending, DNSStatusMisconfigured, DNSStatusError:
		return true
	}
	return false
}

func (e DNSStatus) String() string {
	return string(e)
}

func (e *DNSStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DNSStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DnsStatus", str)
	}
	return nil
}

func (e DNSStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DNSStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DNSStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EndpointType string

const (
	EndpointTypePlatform EndpointType = "PLATFORM"
	EndpointTypeCustom   EndpointType = "CUSTOM"
	EndpointTypeInternal EndpointType = "INTERNAL"
)

var AllEndpointType = []EndpointType{
	EndpointTypePlatform,
	EndpointTypeCustom,
	EndpointTypeInternal,
}

func (e EndpointType) IsValid() bool {
	switch e {
	case EndpointTypePlatform, EndpointTypeCustom, EndpointTypeInternal:
		return true
	}
	return false
}

func (e EndpointType) String() string {
	return string(e)
}

func (e *EndpointType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EndpointType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EndpointType", str)
	}
	return nil
}

func (e EndpointType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EndpointType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EndpointType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GitHubAccountType string

const (
	GitHubAccountTypeOrganization GitHubAccountType = "ORGANIZATION"
	GitHubAccountTypeUser         GitHubAccountType = "USER"
)

var AllGitHubAccountType = []GitHubAccountType{
	GitHubAccountTypeOrganization,
	GitHubAccountTypeUser,
}

func (e GitHubAccountType) IsValid() bool {
	switch e {
	case GitHubAccountTypeOrganization, GitHubAccountTypeUser:
		return true
	}
	return false
}

func (e GitHubAccountType) String() string {
	return string(e)
}

func (e *GitHubAccountType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GitHubAccountType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GitHubAccountType", str)
	}
	return nil
}

func (e GitHubAccountType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GitHubAccountType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GitHubAccountType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Plan string

const (
	PlanHobby Plan = "HOBBY"
	PlanPro   Plan = "PRO"
)

var AllPlan = []Plan{
	PlanHobby,
	PlanPro,
}

func (e Plan) IsValid() bool {
	switch e {
	case PlanHobby, PlanPro:
		return true
	}
	return false
}

func (e Plan) String() string {
	return string(e)
}

func (e *Plan) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Plan(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Plan", str)
	}
	return nil
}

func (e Plan) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Plan) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Plan) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Protocol string

const (
	ProtocolHTTP  Protocol = "HTTP"
	ProtocolHTTPS Protocol = "HTTPS"
	ProtocolTCP   Protocol = "TCP"
)

var AllProtocol = []Protocol{
	ProtocolHTTP,
	ProtocolHTTPS,
	ProtocolTCP,
}

func (e Protocol) IsValid() bool {
	switch e {
	case ProtocolHTTP, ProtocolHTTPS, ProtocolTCP:
		return true
	}
	return false
}

func (e Protocol) String() string {
	return string(e)
}

func (e *Protocol) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Protocol(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Protocol", str)
	}
	return nil
}

func (e Protocol) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Protocol) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Protocol) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ResourceTier string

const (
	ResourceTierEco        ResourceTier = "ECO"
	ResourceTierProduction ResourceTier = "PRODUCTION"
)

var AllResourceTier = []ResourceTier{
	ResourceTierEco,
	ResourceTierProduction,
}

func (e ResourceTier) IsValid() bool {
	switch e {
	case ResourceTierEco, ResourceTierProduction:
		return true
	}
	return false
}

func (e ResourceTier) String() string {
	return string(e)
}

func (e *ResourceTier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ResourceTier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ResourceTier", str)
	}
	return nil
}

func (e ResourceTier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ResourceTier) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ResourceTier) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleAnonymous Role = "ANONYMOUS"
	RoleUser      Role = "USER"
	RoleAdmin     Role = "ADMIN"
)

var AllRole = []Role{
	RoleAnonymous,
	RoleUser,
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAnonymous, RoleUser, RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ServiceStatus string

const (
	ServiceStatusHealthy   ServiceStatus = "HEALTHY"
	ServiceStatusDegraded  ServiceStatus = "DEGRADED"
	ServiceStatusDeploying ServiceStatus = "DEPLOYING"
	ServiceStatusFailed    ServiceStatus = "FAILED"
	ServiceStatusStopped   ServiceStatus = "STOPPED"
	ServiceStatusBuilding  ServiceStatus = "BUILDING"
)

var AllServiceStatus = []ServiceStatus{
	ServiceStatusHealthy,
	ServiceStatusDegraded,
	ServiceStatusDeploying,
	ServiceStatusFailed,
	ServiceStatusStopped,
	ServiceStatusBuilding,
}

func (e ServiceStatus) IsValid() bool {
	switch e {
	case ServiceStatusHealthy, ServiceStatusDegraded, ServiceStatusDeploying, ServiceStatusFailed, ServiceStatusStopped, ServiceStatusBuilding:
		return true
	}
	return false
}

func (e ServiceStatus) String() string {
	return string(e)
}

func (e *ServiceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServiceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServiceStatus", str)
	}
	return nil
}

func (e ServiceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServiceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServiceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusActive     SubscriptionStatus = "ACTIVE"
	SubscriptionStatusPastDue    SubscriptionStatus = "PAST_DUE"
	SubscriptionStatusCanceled   SubscriptionStatus = "CANCELED"
	SubscriptionStatusIncomplete SubscriptionStatus = "INCOMPLETE"
	SubscriptionStatusTrialing   SubscriptionStatus = "TRIALING"
)

var AllSubscriptionStatus = []SubscriptionStatus{
	SubscriptionStatusActive,
	SubscriptionStatusPastDue,
	SubscriptionStatusCanceled,
	SubscriptionStatusIncomplete,
	SubscriptionStatusTrialing,
}

func (e SubscriptionStatus) IsValid() bool {
	switch e {
	case SubscriptionStatusActive, SubscriptionStatusPastDue, SubscriptionStatusCanceled, SubscriptionStatusIncomplete, SubscriptionStatusTrialing:
		return true
	}
	return false
}

func (e SubscriptionStatus) String() string {
	return string(e)
}

func (e *SubscriptionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SubscriptionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SubscriptionStatus", str)
	}
	return nil
}

func (e SubscriptionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SubscriptionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SubscriptionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TLSStatus string

const (
	TLSStatusNone         TLSStatus = "NONE"
	TLSStatusProvisioning TLSStatus = "PROVISIONING"
	TLSStatusActive       TLSStatus = "ACTIVE"
	TLSStatusError        TLSStatus = "ERROR"
)

var AllTLSStatus = []TLSStatus{
	TLSStatusNone,
	TLSStatusProvisioning,
	TLSStatusActive,
	TLSStatusError,
}

func (e TLSStatus) IsValid() bool {
	switch e {
	case TLSStatusNone, TLSStatusProvisioning, TLSStatusActive, TLSStatusError:
		return true
	}
	return false
}

func (e TLSStatus) String() string {
	return string(e)
}

func (e *TLSStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TLSStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TlsStatus", str)
	}
	return nil
}

func (e TLSStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TLSStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TLSStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkspaceRole string

const (
	WorkspaceRoleUser  WorkspaceRole = "USER"
	WorkspaceRoleAdmin WorkspaceRole = "ADMIN"
)

var AllWorkspaceRole = []WorkspaceRole{
	WorkspaceRoleUser,
	WorkspaceRoleAdmin,
}

func (e WorkspaceRole) IsValid() bool {
	switch e {
	case WorkspaceRoleUser, WorkspaceRoleAdmin:
		return true
	}
	return false
}

func (e WorkspaceRole) String() string {
	return string(e)
}

func (e *WorkspaceRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkspaceRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkspaceRole", str)
	}
	return nil
}

func (e WorkspaceRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkspaceRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkspaceRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
