apiVersion: v2
name: lucity-infra
description: Lucity platform infrastructure — OCI registry (Zot), Git server (Soft-serve), GitOps (ArgoCD), and PostgreSQL operator (CNPG)
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: zot
    version: "0.1.104"
    repository: "http://zotregistry.dev/helm-charts"
    condition: zot.enabled
  - name: argo-cd
    version: "9.4.17"
    repository: "https://argoproj.github.io/argo-helm"
    condition: argo-cd.enabled
  - name: cloudnative-pg
    version: "0.28.0"
    repository: "https://cloudnative-pg.github.io/charts"
    condition: cloudnative-pg.enabled
  - name: victoria-metrics-single
    version: "0.37.0"
    repository: "https://victoriametrics.github.io/helm-charts/"
    condition: victoria-metrics-single.enabled
  - name: victoria-logs-single
    version: "0.12.2"
    repository: "https://victoriametrics.github.io/helm-charts/"
    condition: victoria-logs-single.enabled
  - name: victoria-metrics-alert
    version: "0.39.0"
    repository: "https://victoriametrics.github.io/helm-charts/"
    condition: victoria-metrics-alert.enabled
  - name: opentelemetry-operator
    version: "0.110.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-operator.enabled
  - name: grafana
    version: "12.2.1"
    repository: "https://grafana-community.github.io/helm-charts"
    condition: grafana.enabled
  - name: traefik
    version: "41.0.0"
    repository: "https://traefik.github.io/charts"
    condition: traefik.enabled
