// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: packager.proto

package packager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PackagerService_InitProject_FullMethodName           = "/packager.PackagerService/InitProject"
	PackagerService_ListProjects_FullMethodName          = "/packager.PackagerService/ListProjects"
	PackagerService_GetProject_FullMethodName            = "/packager.PackagerService/GetProject"
	PackagerService_DeleteProject_FullMethodName         = "/packager.PackagerService/DeleteProject"
	PackagerService_AddService_FullMethodName            = "/packager.PackagerService/AddService"
	PackagerService_RemoveService_FullMethodName         = "/packager.PackagerService/RemoveService"
	PackagerService_UpdateImageTag_FullMethodName        = "/packager.PackagerService/UpdateImageTag"
	PackagerService_CreateEnvironment_FullMethodName     = "/packager.PackagerService/CreateEnvironment"
	PackagerService_DeleteEnvironment_FullMethodName     = "/packager.PackagerService/DeleteEnvironment"
	PackagerService_Promote_FullMethodName               = "/packager.PackagerService/Promote"
	PackagerService_Eject_FullMethodName                 = "/packager.PackagerService/Eject"
	PackagerService_DeploymentHistory_FullMethodName     = "/packager.PackagerService/DeploymentHistory"
	PackagerService_AddDomain_FullMethodName             = "/packager.PackagerService/AddDomain"
	PackagerService_RemoveDomain_FullMethodName          = "/packager.PackagerService/RemoveDomain"
	PackagerService_AllDomains_FullMethodName            = "/packager.PackagerService/AllDomains"
	PackagerService_SharedVariables_FullMethodName       = "/packager.PackagerService/SharedVariables"
	PackagerService_SetSharedVariables_FullMethodName    = "/packager.PackagerService/SetSharedVariables"
	PackagerService_ServiceVariables_FullMethodName      = "/packager.PackagerService/ServiceVariables"
	PackagerService_SetServiceVariables_FullMethodName   = "/packager.PackagerService/SetServiceVariables"
	PackagerService_AddDatabase_FullMethodName           = "/packager.PackagerService/AddDatabase"
	PackagerService_RemoveDatabase_FullMethodName        = "/packager.PackagerService/RemoveDatabase"
	PackagerService_SyncChart_FullMethodName             = "/packager.PackagerService/SyncChart"
	PackagerService_SetResources_FullMethodName          = "/packager.PackagerService/SetResources"
	PackagerService_SetServiceScaling_FullMethodName     = "/packager.PackagerService/SetServiceScaling"
	PackagerService_SetCustomStartCommand_FullMethodName = "/packager.PackagerService/SetCustomStartCommand"
)

// PackagerServiceClient is the client API for PackagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PackagerServiceClient interface {
	// InitProject creates a new GitOps repository for a project.
	InitProject(ctx context.Context, in *InitProjectRequest, opts ...grpc.CallOption) (*InitProjectResponse, error)
	// ListProjects returns all projects managed by the packager.
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	// GetProject returns a single project by name.
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error)
	// DeleteProject removes a project and its GitOps repository.
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error)
	// AddService adds a service definition to the project's base values.
	AddService(ctx context.Context, in *AddServiceRequest, opts ...grpc.CallOption) (*AddServiceResponse, error)
	// RemoveService removes a service definition from the project's base values.
	RemoveService(ctx context.Context, in *RemoveServiceRequest, opts ...grpc.CallOption) (*RemoveServiceResponse, error)
	// UpdateImageTag updates the image tag for a service in a specific environment.
	UpdateImageTag(ctx context.Context, in *UpdateImageTagRequest, opts ...grpc.CallOption) (*UpdateImageTagResponse, error)
	// CreateEnvironment creates a new environment in the GitOps repo.
	CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*CreateEnvironmentResponse, error)
	// DeleteEnvironment removes an environment from the GitOps repo.
	DeleteEnvironment(ctx context.Context, in *DeleteEnvironmentRequest, opts ...grpc.CallOption) (*DeleteEnvironmentResponse, error)
	// Promote copies an image tag from one environment to another.
	Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error)
	// Eject exports the complete project configuration for independent operation.
	Eject(ctx context.Context, in *EjectRequest, opts ...grpc.CallOption) (*EjectResponse, error)
	// DeploymentHistory returns the deployment history for a service in an environment.
	DeploymentHistory(ctx context.Context, in *DeploymentHistoryRequest, opts ...grpc.CallOption) (*DeploymentHistoryResponse, error)
	// AddDomain adds a domain hostname to a service in an environment.
	AddDomain(ctx context.Context, in *AddDomainRequest, opts ...grpc.CallOption) (*AddDomainResponse, error)
	// RemoveDomain removes a domain hostname from a service in an environment.
	RemoveDomain(ctx context.Context, in *RemoveDomainRequest, opts ...grpc.CallOption) (*RemoveDomainResponse, error)
	// AllDomains returns all domain hostnames across all projects and environments (for collision detection).
	AllDomains(ctx context.Context, in *AllDomainsRequest, opts ...grpc.CallOption) (*AllDomainsResponse, error)
	// SharedVariables returns all shared variables for an environment.
	SharedVariables(ctx context.Context, in *SharedVariablesRequest, opts ...grpc.CallOption) (*SharedVariablesResponse, error)
	// SetSharedVariables replaces all shared variables for an environment.
	// Also propagates changes to any services that reference shared vars via sharedRefs.
	SetSharedVariables(ctx context.Context, in *SetSharedVariablesRequest, opts ...grpc.CallOption) (*SetSharedVariablesResponse, error)
	// ServiceVariables returns all variables for a service in an environment.
	ServiceVariables(ctx context.Context, in *ServiceVariablesRequest, opts ...grpc.CallOption) (*ServiceVariablesResponse, error)
	// SetServiceVariables replaces all variables for a service in an environment.
	// Shared refs are resolved from the environment's shared variables.
	SetServiceVariables(ctx context.Context, in *SetServiceVariablesRequest, opts ...grpc.CallOption) (*SetServiceVariablesResponse, error)
	// AddDatabase adds a PostgreSQL database definition to the project's base values.
	AddDatabase(ctx context.Context, in *AddDatabaseRequest, opts ...grpc.CallOption) (*AddDatabaseResponse, error)
	// RemoveDatabase removes a PostgreSQL database from the project's base values.
	RemoveDatabase(ctx context.Context, in *RemoveDatabaseRequest, opts ...grpc.CallOption) (*RemoveDatabaseResponse, error)
	// SyncChart updates the embedded lucity-app Helm chart in the project's GitOps repo.
	// Called to propagate chart template changes (e.g., new Gateway config) to existing repos.
	SyncChart(ctx context.Context, in *SyncChartRequest, opts ...grpc.CallOption) (*SyncChartResponse, error)
	// SetResources writes resource requests/limits to an environment's values.yaml.
	// Keeps the GitOps repo in sync with K8s ResourceQuota for ejection purposes.
	SetResources(ctx context.Context, in *SetResourcesRequest, opts ...grpc.CallOption) (*SetResourcesResponse, error)
	// SetServiceScaling writes replica count and autoscaling config to an environment's values.yaml.
	SetServiceScaling(ctx context.Context, in *SetServiceScalingRequest, opts ...grpc.CallOption) (*SetServiceScalingResponse, error)
	// SetCustomStartCommand sets or clears the custom start command for a service in base values.
	SetCustomStartCommand(ctx context.Context, in *SetCustomStartCommandRequest, opts ...grpc.CallOption) (*SetCustomStartCommandResponse, error)
}

type packagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPackagerServiceClient(cc grpc.ClientConnInterface) PackagerServiceClient {
	return &packagerServiceClient{cc}
}

func (c *packagerServiceClient) InitProject(ctx context.Context, in *InitProjectRequest, opts ...grpc.CallOption) (*InitProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitProjectResponse)
	err := c.cc.Invoke(ctx, PackagerService_InitProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, PackagerService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectResponse)
	err := c.cc.Invoke(ctx, PackagerService_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProjectResponse)
	err := c.cc.Invoke(ctx, PackagerService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) AddService(ctx context.Context, in *AddServiceRequest, opts ...grpc.CallOption) (*AddServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddServiceResponse)
	err := c.cc.Invoke(ctx, PackagerService_AddService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) RemoveService(ctx context.Context, in *RemoveServiceRequest, opts ...grpc.CallOption) (*RemoveServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveServiceResponse)
	err := c.cc.Invoke(ctx, PackagerService_RemoveService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) UpdateImageTag(ctx context.Context, in *UpdateImageTagRequest, opts ...grpc.CallOption) (*UpdateImageTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateImageTagResponse)
	err := c.cc.Invoke(ctx, PackagerService_UpdateImageTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*CreateEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEnvironmentResponse)
	err := c.cc.Invoke(ctx, PackagerService_CreateEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) DeleteEnvironment(ctx context.Context, in *DeleteEnvironmentRequest, opts ...grpc.CallOption) (*DeleteEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEnvironmentResponse)
	err := c.cc.Invoke(ctx, PackagerService_DeleteEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteResponse)
	err := c.cc.Invoke(ctx, PackagerService_Promote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) Eject(ctx context.Context, in *EjectRequest, opts ...grpc.CallOption) (*EjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EjectResponse)
	err := c.cc.Invoke(ctx, PackagerService_Eject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) DeploymentHistory(ctx context.Context, in *DeploymentHistoryRequest, opts ...grpc.CallOption) (*DeploymentHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploymentHistoryResponse)
	err := c.cc.Invoke(ctx, PackagerService_DeploymentHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) AddDomain(ctx context.Context, in *AddDomainRequest, opts ...grpc.CallOption) (*AddDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDomainResponse)
	err := c.cc.Invoke(ctx, PackagerService_AddDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) RemoveDomain(ctx context.Context, in *RemoveDomainRequest, opts ...grpc.CallOption) (*RemoveDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveDomainResponse)
	err := c.cc.Invoke(ctx, PackagerService_RemoveDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) AllDomains(ctx context.Context, in *AllDomainsRequest, opts ...grpc.CallOption) (*AllDomainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllDomainsResponse)
	err := c.cc.Invoke(ctx, PackagerService_AllDomains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) SharedVariables(ctx context.Context, in *SharedVariablesRequest, opts ...grpc.CallOption) (*SharedVariablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SharedVariablesResponse)
	err := c.cc.Invoke(ctx, PackagerService_SharedVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) SetSharedVariables(ctx context.Context, in *SetSharedVariablesRequest, opts ...grpc.CallOption) (*SetSharedVariablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSharedVariablesResponse)
	err := c.cc.Invoke(ctx, PackagerService_SetSharedVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) ServiceVariables(ctx context.Context, in *ServiceVariablesRequest, opts ...grpc.CallOption) (*ServiceVariablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceVariablesResponse)
	err := c.cc.Invoke(ctx, PackagerService_ServiceVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) SetServiceVariables(ctx context.Context, in *SetServiceVariablesRequest, opts ...grpc.CallOption) (*SetServiceVariablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetServiceVariablesResponse)
	err := c.cc.Invoke(ctx, PackagerService_SetServiceVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) AddDatabase(ctx context.Context, in *AddDatabaseRequest, opts ...grpc.CallOption) (*AddDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDatabaseResponse)
	err := c.cc.Invoke(ctx, PackagerService_AddDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) RemoveDatabase(ctx context.Context, in *RemoveDatabaseRequest, opts ...grpc.CallOption) (*RemoveDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveDatabaseResponse)
	err := c.cc.Invoke(ctx, PackagerService_RemoveDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) SyncChart(ctx context.Context, in *SyncChartRequest, opts ...grpc.CallOption) (*SyncChartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncChartResponse)
	err := c.cc.Invoke(ctx, PackagerService_SyncChart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) SetResources(ctx context.Context, in *SetResourcesRequest, opts ...grpc.CallOption) (*SetResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResourcesResponse)
	err := c.cc.Invoke(ctx, PackagerService_SetResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) SetServiceScaling(ctx context.Context, in *SetServiceScalingRequest, opts ...grpc.CallOption) (*SetServiceScalingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetServiceScalingResponse)
	err := c.cc.Invoke(ctx, PackagerService_SetServiceScaling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packagerServiceClient) SetCustomStartCommand(ctx context.Context, in *SetCustomStartCommandRequest, opts ...grpc.CallOption) (*SetCustomStartCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCustomStartCommandResponse)
	err := c.cc.Invoke(ctx, PackagerService_SetCustomStartCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PackagerServiceServer is the server API for PackagerService service.
// All implementations must embed UnimplementedPackagerServiceServer
// for forward compatibility.
type PackagerServiceServer interface {
	// InitProject creates a new GitOps repository for a project.
	InitProject(context.Context, *InitProjectRequest) (*InitProjectResponse, error)
	// ListProjects returns all projects managed by the packager.
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	// GetProject returns a single project by name.
	GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error)
	// DeleteProject removes a project and its GitOps repository.
	DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteProjectResponse, error)
	// AddService adds a service definition to the project's base values.
	AddService(context.Context, *AddServiceRequest) (*AddServiceResponse, error)
	// RemoveService removes a service definition from the project's base values.
	RemoveService(context.Context, *RemoveServiceRequest) (*RemoveServiceResponse, error)
	// UpdateImageTag updates the image tag for a service in a specific environment.
	UpdateImageTag(context.Context, *UpdateImageTagRequest) (*UpdateImageTagResponse, error)
	// CreateEnvironment creates a new environment in the GitOps repo.
	CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*CreateEnvironmentResponse, error)
	// DeleteEnvironment removes an environment from the GitOps repo.
	DeleteEnvironment(context.Context, *DeleteEnvironmentRequest) (*DeleteEnvironmentResponse, error)
	// Promote copies an image tag from one environment to another.
	Promote(context.Context, *PromoteRequest) (*PromoteResponse, error)
	// Eject exports the complete project configuration for independent operation.
	Eject(context.Context, *EjectRequest) (*EjectResponse, error)
	// DeploymentHistory returns the deployment history for a service in an environment.
	DeploymentHistory(context.Context, *DeploymentHistoryRequest) (*DeploymentHistoryResponse, error)
	// AddDomain adds a domain hostname to a service in an environment.
	AddDomain(context.Context, *AddDomainRequest) (*AddDomainResponse, error)
	// RemoveDomain removes a domain hostname from a service in an environment.
	RemoveDomain(context.Context, *RemoveDomainRequest) (*RemoveDomainResponse, error)
	// AllDomains returns all domain hostnames across all projects and environments (for collision detection).
	AllDomains(context.Context, *AllDomainsRequest) (*AllDomainsResponse, error)
	// SharedVariables returns all shared variables for an environment.
	SharedVariables(context.Context, *SharedVariablesRequest) (*SharedVariablesResponse, error)
	// SetSharedVariables replaces all shared variables for an environment.
	// Also propagates changes to any services that reference shared vars via sharedRefs.
	SetSharedVariables(context.Context, *SetSharedVariablesRequest) (*SetSharedVariablesResponse, error)
	// ServiceVariables returns all variables for a service in an environment.
	ServiceVariables(context.Context, *ServiceVariablesRequest) (*ServiceVariablesResponse, error)
	// SetServiceVariables replaces all variables for a service in an environment.
	// Shared refs are resolved from the environment's shared variables.
	SetServiceVariables(context.Context, *SetServiceVariablesRequest) (*SetServiceVariablesResponse, error)
	// AddDatabase adds a PostgreSQL database definition to the project's base values.
	AddDatabase(context.Context, *AddDatabaseRequest) (*AddDatabaseResponse, error)
	// RemoveDatabase removes a PostgreSQL database from the project's base values.
	RemoveDatabase(context.Context, *RemoveDatabaseRequest) (*RemoveDatabaseResponse, error)
	// SyncChart updates the embedded lucity-app Helm chart in the project's GitOps repo.
	// Called to propagate chart template changes (e.g., new Gateway config) to existing repos.
	SyncChart(context.Context, *SyncChartRequest) (*SyncChartResponse, error)
	// SetResources writes resource requests/limits to an environment's values.yaml.
	// Keeps the GitOps repo in sync with K8s ResourceQuota for ejection purposes.
	SetResources(context.Context, *SetResourcesRequest) (*SetResourcesResponse, error)
	// SetServiceScaling writes replica count and autoscaling config to an environment's values.yaml.
	SetServiceScaling(context.Context, *SetServiceScalingRequest) (*SetServiceScalingResponse, error)
	// SetCustomStartCommand sets or clears the custom start command for a service in base values.
	SetCustomStartCommand(context.Context, *SetCustomStartCommandRequest) (*SetCustomStartCommandResponse, error)
	mustEmbedUnimplementedPackagerServiceServer()
}

// UnimplementedPackagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPackagerServiceServer struct{}

func (UnimplementedPackagerServiceServer) InitProject(context.Context, *InitProjectRequest) (*InitProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitProject not implemented")
}
func (UnimplementedPackagerServiceServer) ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedPackagerServiceServer) GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedPackagerServiceServer) DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedPackagerServiceServer) AddService(context.Context, *AddServiceRequest) (*AddServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddService not implemented")
}
func (UnimplementedPackagerServiceServer) RemoveService(context.Context, *RemoveServiceRequest) (*RemoveServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveService not implemented")
}
func (UnimplementedPackagerServiceServer) UpdateImageTag(context.Context, *UpdateImageTagRequest) (*UpdateImageTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateImageTag not implemented")
}
func (UnimplementedPackagerServiceServer) CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*CreateEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEnvironment not implemented")
}
func (UnimplementedPackagerServiceServer) DeleteEnvironment(context.Context, *DeleteEnvironmentRequest) (*DeleteEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEnvironment not implemented")
}
func (UnimplementedPackagerServiceServer) Promote(context.Context, *PromoteRequest) (*PromoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedPackagerServiceServer) Eject(context.Context, *EjectRequest) (*EjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Eject not implemented")
}
func (UnimplementedPackagerServiceServer) DeploymentHistory(context.Context, *DeploymentHistoryRequest) (*DeploymentHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeploymentHistory not implemented")
}
func (UnimplementedPackagerServiceServer) AddDomain(context.Context, *AddDomainRequest) (*AddDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDomain not implemented")
}
func (UnimplementedPackagerServiceServer) RemoveDomain(context.Context, *RemoveDomainRequest) (*RemoveDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDomain not implemented")
}
func (UnimplementedPackagerServiceServer) AllDomains(context.Context, *AllDomainsRequest) (*AllDomainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllDomains not implemented")
}
func (UnimplementedPackagerServiceServer) SharedVariables(context.Context, *SharedVariablesRequest) (*SharedVariablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SharedVariables not implemented")
}
func (UnimplementedPackagerServiceServer) SetSharedVariables(context.Context, *SetSharedVariablesRequest) (*SetSharedVariablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSharedVariables not implemented")
}
func (UnimplementedPackagerServiceServer) ServiceVariables(context.Context, *ServiceVariablesRequest) (*ServiceVariablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceVariables not implemented")
}
func (UnimplementedPackagerServiceServer) SetServiceVariables(context.Context, *SetServiceVariablesRequest) (*SetServiceVariablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetServiceVariables not implemented")
}
func (UnimplementedPackagerServiceServer) AddDatabase(context.Context, *AddDatabaseRequest) (*AddDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDatabase not implemented")
}
func (UnimplementedPackagerServiceServer) RemoveDatabase(context.Context, *RemoveDatabaseRequest) (*RemoveDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDatabase not implemented")
}
func (UnimplementedPackagerServiceServer) SyncChart(context.Context, *SyncChartRequest) (*SyncChartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncChart not implemented")
}
func (UnimplementedPackagerServiceServer) SetResources(context.Context, *SetResourcesRequest) (*SetResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetResources not implemented")
}
func (UnimplementedPackagerServiceServer) SetServiceScaling(context.Context, *SetServiceScalingRequest) (*SetServiceScalingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetServiceScaling not implemented")
}
func (UnimplementedPackagerServiceServer) SetCustomStartCommand(context.Context, *SetCustomStartCommandRequest) (*SetCustomStartCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCustomStartCommand not implemented")
}
func (UnimplementedPackagerServiceServer) mustEmbedUnimplementedPackagerServiceServer() {}
func (UnimplementedPackagerServiceServer) testEmbeddedByValue()                         {}

// UnsafePackagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PackagerServiceServer will
// result in compilation errors.
type UnsafePackagerServiceServer interface {
	mustEmbedUnimplementedPackagerServiceServer()
}

func RegisterPackagerServiceServer(s grpc.ServiceRegistrar, srv PackagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedPackagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PackagerService_ServiceDesc, srv)
}

func _PackagerService_InitProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).InitProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_InitProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).InitProject(ctx, req.(*InitProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_AddService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).AddService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_AddService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).AddService(ctx, req.(*AddServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_RemoveService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).RemoveService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_RemoveService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).RemoveService(ctx, req.(*RemoveServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_UpdateImageTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateImageTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).UpdateImageTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_UpdateImageTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).UpdateImageTag(ctx, req.(*UpdateImageTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_CreateEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).CreateEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_CreateEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).CreateEnvironment(ctx, req.(*CreateEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_DeleteEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).DeleteEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_DeleteEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).DeleteEnvironment(ctx, req.(*DeleteEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_Promote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).Promote(ctx, req.(*PromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_Eject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).Eject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_Eject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).Eject(ctx, req.(*EjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_DeploymentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploymentHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).DeploymentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_DeploymentHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).DeploymentHistory(ctx, req.(*DeploymentHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_AddDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).AddDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_AddDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).AddDomain(ctx, req.(*AddDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_RemoveDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).RemoveDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_RemoveDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).RemoveDomain(ctx, req.(*RemoveDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_AllDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).AllDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_AllDomains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).AllDomains(ctx, req.(*AllDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_SharedVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SharedVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).SharedVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_SharedVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).SharedVariables(ctx, req.(*SharedVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_SetSharedVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSharedVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).SetSharedVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_SetSharedVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).SetSharedVariables(ctx, req.(*SetSharedVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_ServiceVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).ServiceVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_ServiceVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).ServiceVariables(ctx, req.(*ServiceVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_SetServiceVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetServiceVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).SetServiceVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_SetServiceVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).SetServiceVariables(ctx, req.(*SetServiceVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_AddDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).AddDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_AddDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).AddDatabase(ctx, req.(*AddDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_RemoveDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).RemoveDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_RemoveDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).RemoveDatabase(ctx, req.(*RemoveDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_SyncChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).SyncChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_SyncChart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).SyncChart(ctx, req.(*SyncChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_SetResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).SetResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_SetResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).SetResources(ctx, req.(*SetResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_SetServiceScaling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetServiceScalingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).SetServiceScaling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_SetServiceScaling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).SetServiceScaling(ctx, req.(*SetServiceScalingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackagerService_SetCustomStartCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCustomStartCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).SetCustomStartCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_SetCustomStartCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).SetCustomStartCommand(ctx, req.(*SetCustomStartCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PackagerService_ServiceDesc is the grpc.ServiceDesc for PackagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PackagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "packager.PackagerService",
	HandlerType: (*PackagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitProject",
			Handler:    _PackagerService_InitProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _PackagerService_ListProjects_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _PackagerService_GetProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _PackagerService_DeleteProject_Handler,
		},
		{
			MethodName: "AddService",
			Handler:    _PackagerService_AddService_Handler,
		},
		{
			MethodName: "RemoveService",
			Handler:    _PackagerService_RemoveService_Handler,
		},
		{
			MethodName: "UpdateImageTag",
			Handler:    _PackagerService_UpdateImageTag_Handler,
		},
		{
			MethodName: "CreateEnvironment",
			Handler:    _PackagerService_CreateEnvironment_Handler,
		},
		{
			MethodName: "DeleteEnvironment",
			Handler:    _PackagerService_DeleteEnvironment_Handler,
		},
		{
			MethodName: "Promote",
			Handler:    _PackagerService_Promote_Handler,
		},
		{
			MethodName: "Eject",
			Handler:    _PackagerService_Eject_Handler,
		},
		{
			MethodName: "DeploymentHistory",
			Handler:    _PackagerService_DeploymentHistory_Handler,
		},
		{
			MethodName: "AddDomain",
			Handler:    _PackagerService_AddDomain_Handler,
		},
		{
			MethodName: "RemoveDomain",
			Handler:    _PackagerService_RemoveDomain_Handler,
		},
		{
			MethodName: "AllDomains",
			Handler:    _PackagerService_AllDomains_Handler,
		},
		{
			MethodName: "SharedVariables",
			Handler:    _PackagerService_SharedVariables_Handler,
		},
		{
			MethodName: "SetSharedVariables",
			Handler:    _PackagerService_SetSharedVariables_Handler,
		},
		{
			MethodName: "ServiceVariables",
			Handler:    _PackagerService_ServiceVariables_Handler,
		},
		{
			MethodName: "SetServiceVariables",
			Handler:    _PackagerService_SetServiceVariables_Handler,
		},
		{
			MethodName: "AddDatabase",
			Handler:    _PackagerService_AddDatabase_Handler,
		},
		{
			MethodName: "RemoveDatabase",
			Handler:    _PackagerService_RemoveDatabase_Handler,
		},
		{
			MethodName: "SyncChart",
			Handler:    _PackagerService_SyncChart_Handler,
		},
		{
			MethodName: "SetResources",
			Handler:    _PackagerService_SetResources_Handler,
		},
		{
			MethodName: "SetServiceScaling",
			Handler:    _PackagerService_SetServiceScaling_Handler,
		},
		{
			MethodName: "SetCustomStartCommand",
			Handler:    _PackagerService_SetCustomStartCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "packager.proto",
}
