{{- if and (index .Values "victoria-metrics-alert" "alertmanager" "enabled") .Values.alertingTelegram.botToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-alertmanager-telegram
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: observability
type: Opaque
stringData:
  bot_token: {{ .Values.alertingTelegram.botToken | quote }}
{{- end }}
