{{- if and (index .Values "grafana" "enabled") .Values.grafanaOIDC.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-oauth
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: observability
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: {{ .Values.grafanaOIDC.clientSecret | quote }}
{{- end }}
