{{- if .Values.logto.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-logto
  labels:
    app.kubernetes.io/name: logto
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: identity-provider
type: Opaque
stringData:
  m2m-app-id: {{ .Values.logto.secrets.m2mAppId | quote }}
  m2m-app-secret: {{ .Values.logto.secrets.m2mAppSecret | quote }}
  secret-vault-kek: {{ .Values.logto.secrets.secretVaultKek | quote }}
{{- end }}
