{{- if .Values.rauthy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rauthy
  labels:
    app.kubernetes.io/name: rauthy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: identity-provider
spec:
  type: {{ .Values.rauthy.service.type }}
  ports:
    - name: http
      port: {{ .Values.rauthy.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.rauthy.service.httpsPort }}
      targetPort: https
      protocol: TCP
  selector:
    app.kubernetes.io/name: rauthy
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
