{{- if .Values.rauthy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rauthy-headless
  labels:
    app.kubernetes.io/name: rauthy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: identity-provider
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  sessionAffinity: None
  ports:
    - name: hiqlite-raft
      port: 8100
      targetPort: hiqlite-raft
      protocol: TCP
    - name: hiqlite-api
      port: 8200
      targetPort: hiqlite-api
      protocol: TCP
  selector:
    app.kubernetes.io/name: rauthy
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
