{{- if .Values.rybbit.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rybbit
  labels:
    app.kubernetes.io/name: rybbit
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: analytics
type: Opaque
stringData:
  clickhouse-password: {{ .Values.rybbit.secrets.clickhousePassword | quote }}
  better-auth-secret: {{ .Values.rybbit.secrets.betterAuthSecret | quote }}
{{- end }}
