{{- if .Values.rybbit.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rybbit-clickhouse
  labels:
    app.kubernetes.io/name: rybbit-clickhouse
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: analytics
data:
  network.xml: |
    <clickhouse>
        <listen_host>0.0.0.0</listen_host>
    </clickhouse>
  enable_json.xml: |
    <clickhouse>
        <settings>
            <enable_json_type>1</enable_json_type>
        </settings>
    </clickhouse>
  logging_rules.xml: |
    <clickhouse>
      <logger>
          <level>warning</level>
          <console>true</console>
      </logger>
      <query_thread_log remove="remove"/>
      <query_log remove="remove"/>
      <text_log remove="remove"/>
      <trace_log remove="remove"/>
      <metric_log remove="remove"/>
      <asynchronous_metric_log remove="remove"/>
      <session_log remove="remove"/>
      <part_log remove="remove"/>
      <latency_log remove="remove"/>
      <processors_profile_log remove="remove"/>
    </clickhouse>
  user_logging.xml: |
    <clickhouse>
      <profiles>
        <default>
          <log_queries>0</log_queries>
          <log_query_threads>0</log_query_threads>
          <log_processors_profiles>0</log_processors_profiles>
        </default>
      </profiles>
    </clickhouse>
  low_memory.xml: |
    <clickhouse>
      <mark_cache_size>134217728</mark_cache_size>
      <index_mark_cache_size>33554432</index_mark_cache_size>
      <background_pool_size>2</background_pool_size>
      <background_merges_mutations_concurrency_ratio>2</background_merges_mutations_concurrency_ratio>
      <background_common_pool_size>2</background_common_pool_size>
      <background_schedule_pool_size>8</background_schedule_pool_size>
      <background_move_pool_size>1</background_move_pool_size>
      <background_fetches_pool_size>1</background_fetches_pool_size>
      <background_buffer_flush_schedule_pool_size>1</background_buffer_flush_schedule_pool_size>
      <background_message_broker_schedule_pool_size>1</background_message_broker_schedule_pool_size>
      <background_distributed_schedule_pool_size>1</background_distributed_schedule_pool_size>
      <merge_tree>
        <merge_max_block_size>1024</merge_max_block_size>
        <number_of_free_entries_in_pool_to_lower_max_size_of_merge>2</number_of_free_entries_in_pool_to_lower_max_size_of_merge>
        <number_of_free_entries_in_pool_to_execute_mutation>2</number_of_free_entries_in_pool_to_execute_mutation>
        <number_of_free_entries_in_pool_to_execute_optimize_entire_partition>2</number_of_free_entries_in_pool_to_execute_optimize_entire_partition>
      </merge_tree>
    </clickhouse>
{{- end }}
