apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lucity-agent.fullname" . }}-data
  labels:
    {{- include "lucity-agent.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
