apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lucity-agent.fullname" . }}
  labels:
    {{- include "lucity-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
