package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/zeitlos/lucity/services/gateway/graphql/model"
)

// SetEnvironmentResources is the resolver for the setEnvironmentResources field.
func (r *mutationResolver) SetEnvironmentResources(ctx context.Context, input model.SetEnvironmentResourcesInput) (*model.EnvironmentResources, error) {
	res, err := r.API.SetEnvironmentResources(ctx, input.ProjectID, input.Environment, string(input.Tier), input.CPUMillicores, input.MemoryMb, input.DiskMb)
	if err != nil {
		return nil, err
	}
	result := convertEnvironmentResources(*res)
	return &result, nil
}

// EnvironmentResources is the resolver for the environmentResources field.
func (r *queryResolver) EnvironmentResources(ctx context.Context, projectID string, environment string) (*model.EnvironmentResources, error) {
	res, err := r.API.EnvironmentResources(ctx, projectID, environment)
	if err != nil {
		return nil, err
	}
	result := convertEnvironmentResources(*res)
	return &result, nil
}
