package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/zeitlos/lucity/services/gateway/graphql/model"
)

// CreateDatabase is the resolver for the createDatabase field.
func (r *mutationResolver) CreateDatabase(ctx context.Context, input model.CreateDatabaseInput) (*model.Database, error) {
	version := ""
	if input.Version != nil {
		version = *input.Version
	}
	instances := 0
	if input.Instances != nil {
		instances = *input.Instances
	}
	size := ""
	if input.Size != nil {
		size = *input.Size
	}
	db, err := r.API.CreateDatabase(ctx, input.ProjectID, input.Name, version, instances, size)
	if err != nil {
		return nil, err
	}
	result := convertDatabase(*db)
	return &result, nil
}

// DeleteDatabase is the resolver for the deleteDatabase field.
func (r *mutationResolver) DeleteDatabase(ctx context.Context, projectID string, name string) (bool, error) {
	return r.API.DeleteDatabase(ctx, projectID, name)
}

// Databases is the resolver for the databases field.
func (r *queryResolver) Databases(ctx context.Context, projectID string) ([]model.Database, error) {
	dbs, err := r.API.Databases(ctx, projectID)
	if err != nil {
		return nil, err
	}
	result := make([]model.Database, 0, len(dbs))
	for _, d := range dbs {
		result = append(result, convertDatabase(d))
	}
	return result, nil
}
