package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/zeitlos/lucity/services/gateway/graphql/model"
)

// GithubSources is the resolver for the githubSources field.
func (r *queryResolver) GithubSources(ctx context.Context) ([]model.GitHubInstallation, error) {
	installations, err := r.API.GitHubSources(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]model.GitHubInstallation, 0, len(installations))
	for _, i := range installations {
		result = append(result, convertGitHubInstallation(i))
	}
	return result, nil
}

// GithubRepositories is the resolver for the githubRepositories field.
func (r *queryResolver) GithubRepositories(ctx context.Context, installationID string) ([]model.GitHubRepository, error) {
	repos, err := r.API.GitHubRepositories(ctx, installationID)
	if err != nil {
		return nil, err
	}
	result := make([]model.GitHubRepository, 0, len(repos))
	for _, r := range repos {
		result = append(result, convertGitHubRepository(r))
	}
	return result, nil
}

// GithubConnected is the resolver for the githubConnected field.
func (r *queryResolver) GithubConnected(ctx context.Context) (bool, error) {
	return r.API.GitHubConnected(ctx)
}
