package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/zeitlos/lucity/services/gateway/graphql/model"
)

// ServiceLogs is the resolver for the serviceLogs field.
func (r *subscriptionResolver) ServiceLogs(ctx context.Context, projectID string, service string, environment string, tailLines *int) (<-chan *model.ServiceLogEntry, error) {
	ch, err := r.API.ServiceLogs(ctx, projectID, service, environment, tailLines)
	if err != nil {
		return nil, err
	}

	out := make(chan *model.ServiceLogEntry, 128)
	go func() {
		defer close(out)
		for entry := range ch {
			select {
			case out <- &model.ServiceLogEntry{Line: entry.Line, Pod: entry.Pod}:
			case <-ctx.Done():
				return
			}
		}
	}()

	return out, nil
}
