package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"strings"

	"github.com/zeitlos/lucity/services/gateway/graphql/model"
	"github.com/zeitlos/lucity/services/gateway/handler"
)

// ResourceTier is the resolver for the resourceTier field.
func (r *environmentResolver) ResourceTier(ctx context.Context, obj *model.Environment) (*model.ResourceTier, error) {
	// Extract projectId from the environment ID (format: "projectId/envName").
	projectID, _, found := strings.Cut(obj.ID, "/")
	if !found {
		return nil, nil
	}
	res, err := r.API.EnvironmentResources(ctx, projectID, obj.Name)
	if err != nil {
		// Environment not yet deployed or no tier set — return nil.
		return nil, nil
	}
	tier := model.ResourceTier(res.Tier)
	return &tier, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	p, err := r.API.CreateProject(ctx, input.Name)
	if err != nil {
		return nil, err
	}
	result := convertProject(*p, r.API.WorkloadDomain)
	return &result, nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	return r.API.DeleteProject(ctx, id)
}

// CreateEnvironment is the resolver for the createEnvironment field.
func (r *mutationResolver) CreateEnvironment(ctx context.Context, input model.CreateEnvironmentInput) (*model.Environment, error) {
	fromEnv := ""
	if input.FromEnvironment != nil {
		fromEnv = *input.FromEnvironment
	}
	tier := ""
	if input.Tier != nil {
		tier = string(*input.Tier)
	}
	e, err := r.API.CreateEnvironment(ctx, input.ProjectID, input.Name, fromEnv, tier)
	if err != nil {
		return nil, err
	}
	result := convertEnvironment(*e, r.API.WorkloadDomain)
	return &result, nil
}

// DeleteEnvironment is the resolver for the deleteEnvironment field.
func (r *mutationResolver) DeleteEnvironment(ctx context.Context, projectID string, environment string) (bool, error) {
	return r.API.DeleteEnvironment(ctx, projectID, environment)
}

// Promote is the resolver for the promote field.
func (r *mutationResolver) Promote(ctx context.Context, input model.PromoteInput) (*model.ServiceInstance, error) {
	si, err := r.API.Promote(ctx, input.ProjectID, input.Service, input.FromEnvironment, input.ToEnvironment)
	if err != nil {
		return nil, err
	}
	result := convertServiceInstance(*si, r.API.WorkloadDomain)
	return &result, nil
}

// SetServiceScaling is the resolver for the setServiceScaling field.
func (r *mutationResolver) SetServiceScaling(ctx context.Context, input model.SetServiceScalingInput) (*model.ScalingConfig, error) {
	var autoscaling *handler.AutoscalingConfig
	if input.Autoscaling != nil {
		autoscaling = &handler.AutoscalingConfig{
			Enabled:     input.Autoscaling.Enabled,
			MinReplicas: input.Autoscaling.MinReplicas,
			MaxReplicas: input.Autoscaling.MaxReplicas,
			TargetCPU:   input.Autoscaling.TargetCPU,
		}
	}
	sc, err := r.API.SetServiceScaling(ctx, input.ProjectID, input.Environment, input.Service, input.Replicas, autoscaling)
	if err != nil {
		return nil, err
	}
	result := convertScalingConfig(*sc)
	return &result, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]model.Project, error) {
	projects, err := r.API.Projects(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]model.Project, 0, len(projects))
	for _, p := range projects {
		result = append(result, convertProject(p, r.API.WorkloadDomain))
	}
	return result, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	p, err := r.API.Project(ctx, id)
	if err != nil {
		return nil, err
	}
	result := convertProject(*p, r.API.WorkloadDomain)
	return &result, nil
}

// Environment returns EnvironmentResolver implementation.
func (r *Resolver) Environment() EnvironmentResolver { return &environmentResolver{r} }

type environmentResolver struct{ *Resolver }
