package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/zeitlos/lucity/services/gateway/graphql/model"
)

// SearchImages is the resolver for the searchImages field.
func (r *queryResolver) SearchImages(ctx context.Context, query string) ([]model.ImageSearchResult, error) {
	images, err := r.API.SearchImages(ctx, query)
	if err != nil {
		return nil, err
	}
	results := make([]model.ImageSearchResult, 0, len(images))
	for _, img := range images {
		results = append(results, model.ImageSearchResult{
			Name:        img.Name,
			Description: img.Description,
			StarCount:   img.StarCount,
			PullCount:   int(img.PullCount),
			Official:    img.Official,
		})
	}
	return results, nil
}
