package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"strconv"

	"github.com/zeitlos/lucity/services/gateway/graphql/model"
)

// AddService is the resolver for the addService field.
func (r *mutationResolver) AddService(ctx context.Context, input model.AddServiceInput) (*model.Service, error) {
	framework := ""
	if input.Framework != nil {
		framework = *input.Framework
	}
	sourceURL := ""
	if input.SourceURL != nil {
		sourceURL = *input.SourceURL
	}
	contextPath := ""
	if input.ContextPath != nil {
		contextPath = *input.ContextPath
	}
	var installationID *int64
	if input.InstallationID != nil {
		id, err := strconv.ParseInt(*input.InstallationID, 10, 64)
		if err != nil {
			return nil, fmt.Errorf("invalid installation ID: %w", err)
		}
		installationID = &id
	}
	name := ""
	if input.Name != nil {
		name = *input.Name
	}
	port := 0
	if input.Port != nil {
		port = *input.Port
	}
	externalImage := ""
	if input.Image != nil {
		externalImage = *input.Image
	}
	svc, err := r.API.AddService(ctx, input.ProjectID, name, port, framework, sourceURL, contextPath, installationID, externalImage)
	if err != nil {
		return nil, err
	}
	result := convertService(*svc, r.API.WorkloadDomain)
	return &result, nil
}

// RemoveService is the resolver for the removeService field.
func (r *mutationResolver) RemoveService(ctx context.Context, projectID string, service string) (bool, error) {
	return r.API.RemoveService(ctx, projectID, service)
}

// Deploy is the resolver for the deploy field.
func (r *mutationResolver) Deploy(ctx context.Context, input model.DeployInput) (*model.DeployRun, error) {
	gitRef := ""
	if input.GitRef != nil {
		gitRef = *input.GitRef
	}
	d, err := r.API.Deploy(ctx, input.ProjectID, input.Service, input.Environment, gitRef)
	if err != nil {
		return nil, err
	}
	result := convertDeploymentOp(*d)
	return &result, nil
}

// Rollback is the resolver for the rollback field.
func (r *mutationResolver) Rollback(ctx context.Context, input model.RollbackInput) (bool, error) {
	return r.API.Rollback(ctx, input.ProjectID, input.Service, input.Environment, input.ImageTag)
}

// GenerateDomain is the resolver for the generateDomain field.
func (r *mutationResolver) GenerateDomain(ctx context.Context, input model.GenerateDomainInput) (*model.Domain, error) {
	d, err := r.API.GenerateDomain(ctx, input.ProjectID, input.Service, input.Environment)
	if err != nil {
		return nil, err
	}
	return convertDomain(*d), nil
}

// AddCustomDomain is the resolver for the addCustomDomain field.
func (r *mutationResolver) AddCustomDomain(ctx context.Context, input model.AddCustomDomainInput) (*model.Domain, error) {
	d, err := r.API.AddCustomDomain(ctx, input.ProjectID, input.Service, input.Environment, input.Hostname)
	if err != nil {
		return nil, err
	}
	return convertDomain(*d), nil
}

// RemoveDomain is the resolver for the removeDomain field.
func (r *mutationResolver) RemoveDomain(ctx context.Context, input model.RemoveDomainInput) (bool, error) {
	return r.API.RemoveDomain(ctx, input.ProjectID, input.Service, input.Environment, input.Hostname)
}

// DetectServices is the resolver for the detectServices field.
func (r *queryResolver) DetectServices(ctx context.Context, sourceURL string, installationID *string) ([]model.DetectedService, error) {
	var instID *int64
	if installationID != nil {
		id, err := strconv.ParseInt(*installationID, 10, 64)
		if err != nil {
			return nil, fmt.Errorf("invalid installation ID: %w", err)
		}
		instID = &id
	}
	services, err := r.API.DetectServices(ctx, sourceURL, instID)
	if err != nil {
		return nil, err
	}
	result := make([]model.DetectedService, 0, len(services))
	for _, s := range services {
		result = append(result, convertDetectedService(s))
	}
	return result, nil
}

// DeployStatus is the resolver for the deployStatus field.
func (r *queryResolver) DeployStatus(ctx context.Context, id string) (*model.DeployRun, error) {
	d, err := r.API.DeployStatus(ctx, id)
	if err != nil {
		return nil, err
	}
	result := convertDeploymentOp(*d)
	return &result, nil
}

// ActiveDeployment is the resolver for the activeDeployment field.
func (r *queryResolver) ActiveDeployment(ctx context.Context, projectID string, service string, environment string) (*model.DeployRun, error) {
	d, err := r.API.ActiveDeployment(ctx, projectID, service, environment)
	if err != nil {
		return nil, err
	}
	if d == nil {
		return nil, nil
	}
	result := convertDeploymentOp(*d)
	return &result, nil
}

// PlatformConfig is the resolver for the platformConfig field.
func (r *queryResolver) PlatformConfig(ctx context.Context) (*model.PlatformConfig, error) {
	wd, dt := r.API.PlatformConfig()
	return &model.PlatformConfig{
		WorkloadDomain: wd,
		DomainTarget:   dt,
	}, nil
}

// CheckDNSStatus is the resolver for the checkDnsStatus field.
func (r *queryResolver) CheckDNSStatus(ctx context.Context, hostname string) (*model.DNSCheck, error) {
	check := r.API.CheckDns(hostname)
	return convertDnsCheck(check), nil
}

// DeployLogs is the resolver for the deployLogs field.
func (r *subscriptionResolver) DeployLogs(ctx context.Context, id string) (<-chan string, error) {
	ch, unsub, err := r.API.DeployLogs(ctx, id)
	if err != nil {
		return nil, err
	}
	// Unsubscribe when the client disconnects.
	go func() {
		<-ctx.Done()
		unsub()
	}()
	return ch, nil
}
