package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/zeitlos/lucity/services/gateway/graphql/model"
)

// AddService is the resolver for the addService field.
func (r *mutationResolver) AddService(ctx context.Context, input model.AddServiceInput) (*model.Service, error) {
	framework := ""
	if input.Framework != nil {
		framework = *input.Framework
	}
	sourceURL := ""
	if input.SourceURL != nil {
		sourceURL = *input.SourceURL
	}
	contextPath := ""
	if input.ContextPath != nil {
		contextPath = *input.ContextPath
	}
	svc, err := r.API.AddService(ctx, input.ProjectID, input.Name, input.Port, framework, sourceURL, contextPath)
	if err != nil {
		return nil, err
	}
	result := convertService(*svc)
	return &result, nil
}

// RemoveService is the resolver for the removeService field.
func (r *mutationResolver) RemoveService(ctx context.Context, projectID string, service string) (bool, error) {
	return r.API.RemoveService(ctx, projectID, service)
}

// BuildService is the resolver for the buildService field.
func (r *mutationResolver) BuildService(ctx context.Context, input model.BuildServiceInput) (*model.Build, error) {
	gitRef := ""
	if input.GitRef != nil {
		gitRef = *input.GitRef
	}
	b, err := r.API.StartBuild(ctx, input.ProjectID, input.Service, gitRef)
	if err != nil {
		return nil, err
	}
	result := convertBuild(*b)
	return &result, nil
}

// DeployBuild is the resolver for the deployBuild field.
func (r *mutationResolver) DeployBuild(ctx context.Context, input model.DeployBuildInput) (bool, error) {
	digest := ""
	if input.Digest != nil {
		digest = *input.Digest
	}
	return r.API.DeployBuild(ctx, input.ProjectID, input.Service, input.Environment, input.Tag, digest)
}

// Deploy is the resolver for the deploy field.
func (r *mutationResolver) Deploy(ctx context.Context, input model.DeployInput) (*model.DeployRun, error) {
	gitRef := ""
	if input.GitRef != nil {
		gitRef = *input.GitRef
	}
	d, err := r.API.Deploy(ctx, input.ProjectID, input.Service, input.Environment, gitRef)
	if err != nil {
		return nil, err
	}
	result := convertDeploymentOp(*d)
	return &result, nil
}

// SetServiceDomain is the resolver for the setServiceDomain field.
func (r *mutationResolver) SetServiceDomain(ctx context.Context, input model.SetServiceDomainInput) (bool, error) {
	return r.API.SetServiceDomain(ctx, input.ProjectID, input.Service, input.Environment, input.Host)
}

// DetectServices is the resolver for the detectServices field.
func (r *queryResolver) DetectServices(ctx context.Context, sourceURL string) ([]model.DetectedService, error) {
	services, err := r.API.DetectServices(ctx, sourceURL)
	if err != nil {
		return nil, err
	}
	result := make([]model.DetectedService, 0, len(services))
	for _, s := range services {
		result = append(result, convertDetectedService(s))
	}
	return result, nil
}

// BuildStatus is the resolver for the buildStatus field.
func (r *queryResolver) BuildStatus(ctx context.Context, id string) (*model.Build, error) {
	b, err := r.API.BuildStatus(ctx, id)
	if err != nil {
		return nil, err
	}
	result := convertBuild(*b)
	return &result, nil
}

// DeployStatus is the resolver for the deployStatus field.
func (r *queryResolver) DeployStatus(ctx context.Context, id string) (*model.DeployRun, error) {
	d, err := r.API.DeployStatus(ctx, id)
	if err != nil {
		return nil, err
	}
	result := convertDeploymentOp(*d)
	return &result, nil
}

// ActiveDeployment is the resolver for the activeDeployment field.
func (r *queryResolver) ActiveDeployment(ctx context.Context, projectID string, service string, environment string) (*model.DeployRun, error) {
	d, err := r.API.ActiveDeployment(ctx, projectID, service, environment)
	if err != nil {
		return nil, err
	}
	if d == nil {
		return nil, nil
	}
	result := convertDeploymentOp(*d)
	return &result, nil
}

// DeployLogs is the resolver for the deployLogs field.
func (r *subscriptionResolver) DeployLogs(ctx context.Context, id string) (<-chan string, error) {
	ch, unsub, err := r.API.DeployLogs(ctx, id)
	if err != nil {
		return nil, err
	}
	// Unsubscribe when the client disconnects.
	go func() {
		<-ctx.Done()
		unsub()
	}()
	return ch, nil
}
