package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/zeitlos/lucity/services/gateway/graphql/model"
	"github.com/zeitlos/lucity/services/gateway/handler"
)

// SetSharedVariables is the resolver for the setSharedVariables field.
func (r *mutationResolver) SetSharedVariables(ctx context.Context, projectID string, environment string, variables []model.VariableInput) (bool, error) {
	vars := make([]handler.Variable, len(variables))
	for i, v := range variables {
		vars[i] = handler.Variable{Key: v.Key, Value: v.Value}
	}
	return r.API.SetSharedVariables(ctx, projectID, environment, vars)
}

// SetServiceVariables is the resolver for the setServiceVariables field.
func (r *mutationResolver) SetServiceVariables(ctx context.Context, projectID string, environment string, service string, variables []model.ServiceVariableInput) (bool, error) {
	var directVars []handler.Variable
	var sharedRefs []string
	dbRefs := make(map[string]handler.DatabaseRef)
	svcRefs := make(map[string]handler.ServiceRef)

	for _, v := range variables {
		switch {
		case v.DatabaseRef != nil:
			dbRefs[v.Key] = handler.DatabaseRef{Database: v.DatabaseRef.Database, Key: v.DatabaseRef.Key}
		case v.ServiceRef != nil:
			svcRefs[v.Key] = handler.ServiceRef{Service: v.ServiceRef.Service}
		case v.FromShared != nil && *v.FromShared:
			sharedRefs = append(sharedRefs, v.Key)
		default:
			val := ""
			if v.Value != nil {
				val = *v.Value
			}
			directVars = append(directVars, handler.Variable{Key: v.Key, Value: val})
		}
	}

	return r.API.SetServiceVariables(ctx, projectID, environment, service, directVars, sharedRefs, dbRefs, svcRefs)
}

// SharedVariables is the resolver for the sharedVariables field.
func (r *queryResolver) SharedVariables(ctx context.Context, projectID string, environment string) ([]model.Variable, error) {
	vars, err := r.API.SharedVariables(ctx, projectID, environment)
	if err != nil {
		return nil, err
	}

	result := make([]model.Variable, len(vars))
	for i, v := range vars {
		result[i] = model.Variable{Key: v.Key, Value: v.Value}
	}
	return result, nil
}

// ServiceVariables is the resolver for the serviceVariables field.
func (r *queryResolver) ServiceVariables(ctx context.Context, projectID string, environment string, service string) ([]model.ServiceVariable, error) {
	vars, err := r.API.ServiceVariables(ctx, projectID, environment, service)
	if err != nil {
		return nil, err
	}

	result := make([]model.ServiceVariable, len(vars))
	for i, v := range vars {
		sv := model.ServiceVariable{
			Key:        v.Key,
			Value:      v.Value,
			FromShared: v.FromShared,
		}
		if v.DatabaseRef != nil {
			sv.DatabaseRef = &model.DatabaseRef{
				Database: v.DatabaseRef.Database,
				Key:      v.DatabaseRef.Key,
			}
		}
		if v.ServiceRef != nil {
			sv.ServiceRef = &model.ServiceRef{
				Service: v.ServiceRef.Service,
			}
		}
		result[i] = sv
	}
	return result, nil
}
