package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/zeitlos/lucity/pkg/auth"
	"github.com/zeitlos/lucity/services/gateway/graphql/model"
)

// CreateWorkspace is the resolver for the createWorkspace field.
func (r *mutationResolver) CreateWorkspace(ctx context.Context, input model.CreateWorkspaceInput) (*model.Workspace, error) {
	ws, err := r.API.CreateWorkspace(ctx, input.ID, input.Name)
	if err != nil {
		return nil, err
	}
	return convertWorkspace(ws), nil
}

// CreateWorkspaceCheckout is the resolver for the createWorkspaceCheckout field.
func (r *mutationResolver) CreateWorkspaceCheckout(ctx context.Context, input model.CreateWorkspaceCheckoutInput) (*model.CheckoutSession, error) {
	url, err := r.API.CreateWorkspaceCheckout(ctx, input.ID, input.Name, string(input.Plan))
	if err != nil {
		return nil, err
	}
	return &model.CheckoutSession{URL: url}, nil
}

// CompleteWorkspaceCheckout is the resolver for the completeWorkspaceCheckout field.
func (r *mutationResolver) CompleteWorkspaceCheckout(ctx context.Context, sessionID string) (*model.Workspace, error) {
	ws, err := r.API.CompleteWorkspaceCheckout(ctx, sessionID)
	if err != nil {
		return nil, err
	}
	return convertWorkspace(ws), nil
}

// UpdateWorkspace is the resolver for the updateWorkspace field.
func (r *mutationResolver) UpdateWorkspace(ctx context.Context, input model.UpdateWorkspaceInput) (*model.Workspace, error) {
	ws, err := r.API.UpdateWorkspace(ctx, input.Name)
	if err != nil {
		return nil, err
	}
	return convertWorkspace(ws), nil
}

// DeleteWorkspace is the resolver for the deleteWorkspace field.
func (r *mutationResolver) DeleteWorkspace(ctx context.Context) (bool, error) {
	return r.API.DeleteWorkspace(ctx)
}

// InviteMember is the resolver for the inviteMember field.
func (r *mutationResolver) InviteMember(ctx context.Context, input model.InviteMemberInput) (*model.WorkspaceMember, error) {
	role := auth.WorkspaceRoleUser
	if input.Role == model.WorkspaceRoleAdmin {
		role = auth.WorkspaceRoleAdmin
	}
	m, err := r.API.InviteMember(ctx, input.Email, role)
	if err != nil {
		return nil, err
	}
	return convertWorkspaceMember(m), nil
}

// RemoveMember is the resolver for the removeMember field.
func (r *mutationResolver) RemoveMember(ctx context.Context, userID string) (bool, error) {
	return r.API.RemoveMember(ctx, userID)
}

// UpdateMemberRole is the resolver for the updateMemberRole field.
func (r *mutationResolver) UpdateMemberRole(ctx context.Context, input model.UpdateMemberRoleInput) (*model.WorkspaceMember, error) {
	role := auth.WorkspaceRoleUser
	if input.Role == model.WorkspaceRoleAdmin {
		role = auth.WorkspaceRoleAdmin
	}
	m, err := r.API.UpdateMemberRole(ctx, input.UserID, role)
	if err != nil {
		return nil, err
	}
	return convertWorkspaceMember(m), nil
}

// Workspace is the resolver for the workspace field.
func (r *queryResolver) Workspace(ctx context.Context) (*model.Workspace, error) {
	ws, err := r.API.Workspace(ctx)
	if err != nil {
		return nil, err
	}
	return convertWorkspace(ws), nil
}

// Workspaces is the resolver for the workspaces field.
func (r *queryResolver) Workspaces(ctx context.Context) ([]model.Workspace, error) {
	workspaces, err := r.API.Workspaces(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]model.Workspace, 0, len(workspaces))
	for _, ws := range workspaces {
		result = append(result, *convertWorkspace(&ws))
	}
	return result, nil
}
