# Lucity infrastructure values for minikube

zot:
  persistence: true
  pvc:
    create: true
    storage: 5Gi

softServe:
  persistence:
    size: 2Gi
  initialAdminKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHWFwhUiR9NfDEQYZpx5Th1WC+9wG7ZJAClNNt1Rmee2"
