# Lucity infrastructure values for minikube

zot:
  persistence: true
  pvc:
    create: true
    storage: 5Gi

softServe:
  persistence:
    size: 2Gi
  initialAdminKey: "" # TODO: set to your admin SSH public key
