registryPull:
  host: "10.96.100.100:5000"
  username: reader

routes:
  enabled: true

conductor:
  registryHost: lucity-infra-zot.lucity-system.svc.cluster.local:5000
  registryUsername: builder
  buildkit:
    enabled: true
  env:
    OIDC_ISSUER_URL: https://id.lucity.cloud/oidc
    OIDC_CLIENT_ID: 30ztkgeb1c7hwmnx6bf4s
    OIDC_CALLBACK_URL: https://lucity.cloud/auth/callback
    DASHBOARD_URL: https://lucity.cloud/app

    GITHUB_APP_ID: "2882801"
    GITHUB_PRIVATE_KEY_PATH: /secrets/github/github-app.pem
    GITHUB_APP_SLUG: lucity-platform
    GITHUB_CLIENT_ID: Iv23liMzm79VIgvNtglX
    GITHUB_OAUTH_CALLBACK_URL: https://lucity.cloud/auth/github/callback

    LOGTO_ENDPOINT: http://lucity-infra-logto.lucity-system.svc.cluster.local:3001

    INTERNAL_JWT_PRIVATE_KEY_PATH: /secrets/internal-jwt/private.pem
    INTERNAL_JWT_PUBLIC_KEY_PATH: /secrets/internal-jwt/public.pem

    CASHIER_ADDR: lucity-cashier:9005

    REGISTRY_URL: lucity-infra-zot.lucity-system.svc.cluster.local:5000
    REGISTRY_PUSH_URL: lucity-infra-zot.lucity-system.svc.cluster.local:5000
    REGISTRY_PULL_URL: 10.96.100.100:5000
    REGISTRY_AUTH_SECRET: lucity-registry-auth

    WORKLOAD_DOMAIN: lucity.app
    DATABASE_DOMAIN: db.lucity.app
    IP_ADDRESS: "46.225.47.40"
  envSecret:
    SESSION_SECRET: SESSION_SECRET
    GITHUB_CLIENT_SECRET: GITHUB_CLIENT_SECRET
    LOGTO_M2M_APP_ID: LOGTO_M2M_APP_ID
    LOGTO_M2M_APP_SECRET: LOGTO_M2M_APP_SECRET
    WEBHOOK_SECRET: GITHUB_WEBHOOK_SECRET

cashier:
  enabled: true
  env:
    INTERNAL_JWT_PUBLIC_KEY_PATH: /secrets/internal-jwt/public.pem
    INTERNAL_JWT_PRIVATE_KEY_PATH: /secrets/internal-jwt/private.pem
    CONDUCTOR_ADDR: lucity-conductor:9090
    LOGTO_ENDPOINT: http://lucity-infra-logto.lucity-system.svc.cluster.local:3001
    STRIPE_HOBBY_PRICE_ID: price_1TASy6AoheV3Drw6W13KVFYm
    STRIPE_PRO_PRICE_ID: price_1TASy7AoheV3Drw6t22UVU8C
    STRIPE_ECO_CPU_PRICE_ID: price_1TASyOAoheV3Drw6CUwBuS1L
    STRIPE_ECO_MEM_PRICE_ID: price_1TASyPAoheV3Drw6MLH0Qh0C
    STRIPE_ECO_DISK_PRICE_ID: price_1TFERsAoheV3Drw6VJeNcGdv
    STRIPE_PROD_CPU_PRICE_ID: price_1TF9qaAoheV3Drw6En35zCEK
    STRIPE_PROD_MEM_PRICE_ID: price_1TF9qmAoheV3Drw6zasPNVfM
    STRIPE_PROD_DISK_PRICE_ID: price_1TFERtAoheV3Drw6953EpJgr
    STRIPE_ECO_CPU_METER_EVENT: eco_cpu_usage
    STRIPE_ECO_MEM_METER_EVENT: eco_memory_usage
    STRIPE_ECO_DISK_METER_EVENT: eco_disk_usage
    STRIPE_PROD_CPU_METER_EVENT: prod_cpu_usage
    STRIPE_PROD_MEM_METER_EVENT: prod_memory_usage
    STRIPE_PROD_DISK_METER_EVENT: prod_disk_usage
    VICTORIA_METRICS_URL: http://lucity-infra-victoria-metrics-single-server.lucity-system.svc.cluster.local:8428
  envSecret:
    STRIPE_SECRET_KEY: STRIPE_SECRET_KEY
    STRIPE_WEBHOOK_SECRET: STRIPE_WEBHOOK_SECRET
    LOGTO_M2M_APP_ID: LOGTO_M2M_APP_ID
    LOGTO_M2M_APP_SECRET: LOGTO_M2M_APP_SECRET
