{{- range $name, $pg := .Values.databases.postgres }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "lucity-app.fullname" $ }}-pg-{{ $name }}
  labels:
    {{- include "lucity-app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: postgres-{{ $name }}
    {{- with $.Values.commonLabels }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with $pg.labels }}{{- toYaml . | nindent 4 }}{{- end }}
  annotations:
    cnpg.io/hibernation: {{ if $.Values.suspended }}"on"{{ else }}"off"{{ end }}
    {{- if $pg.publicHost }}
    lucity.dev/db-host: {{ $pg.publicHost | quote }}
    {{- end }}
    {{- with $.Values.commonAnnotations }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with $pg.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
spec:
  instances: {{ $pg.instances | default 1 }}
  imageName: ghcr.io/cloudnative-pg/postgresql:{{ $pg.version | default "17" }}-standard-bookworm
  storage:
    size: {{ $pg.size | default "10Gi" }}
  {{- if $pg.resources }}
  resources:
    {{- toYaml $pg.resources | nindent 4 }}
  {{- end }}
  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector
{{- end }}
