{{- if .Values.registryAuth }}
{{- $host := .Values.registryAuth.host }}
{{- $user := .Values.registryAuth.username }}
{{- $pass := .Values.registryAuth.password }}
{{- $auth := printf "%s:%s" $user $pass | b64enc }}
{{- $dockerConfig := printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" $host $auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lucity-app.fullname" . }}-registry-pull
  labels:
    {{- include "lucity-app.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerConfig | b64enc }}
{{- end }}
