{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lucity-app.fullname" $ }}-{{ $name }}-vars
  labels:
    {{- include "lucity-app.labels" $ | nindent 4 }}
    {{- with $.Values.commonLabels }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  .env: |
    {{- range $key, $val := $svc.env }}
    {{ $key }}={{ $val }}
    {{- end }}
{{- end }}