{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lucity-app.fullname" $ }}-{{ $name }}-variables
  labels:
    {{- include "lucity-app.labels" $ | nindent 4 }}
    {{- with $.Values.commonLabels }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with $svc.labels }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- if or $.Values.commonAnnotations $svc.annotations }}
  annotations:
    {{- with $.Values.commonAnnotations }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with $svc.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $val := $svc.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}