{{- if .Values.sharedVariables }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lucity-app.fullname" . }}-shared
  labels:
    {{- include "lucity-app.labels" . | nindent 4 }}
    lucity.dev/shared-variables: "true"
    {{- with .Values.commonLabels }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.sharedVariables }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
