// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: builder.proto

package builder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BuilderService_DetectServices_FullMethodName = "/builder.BuilderService/DetectServices"
	BuilderService_StartBuild_FullMethodName     = "/builder.BuilderService/StartBuild"
	BuilderService_BuildStatus_FullMethodName    = "/builder.BuilderService/BuildStatus"
	BuilderService_BuildLogs_FullMethodName      = "/builder.BuilderService/BuildLogs"
	BuilderService_DeleteImages_FullMethodName   = "/builder.BuilderService/DeleteImages"
)

// BuilderServiceClient is the client API for BuilderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuilderServiceClient interface {
	// DetectServices scans a source repository and returns detected services
	// with their language, framework, and suggested configuration.
	DetectServices(ctx context.Context, in *DetectServicesRequest, opts ...grpc.CallOption) (*DetectServicesResponse, error)
	// StartBuild starts an asynchronous container image build from source code
	// using railpack and returns a build ID for status polling.
	StartBuild(ctx context.Context, in *StartBuildRequest, opts ...grpc.CallOption) (*StartBuildResponse, error)
	// BuildStatus returns the current status of an in-progress or completed build.
	BuildStatus(ctx context.Context, in *BuildStatusRequest, opts ...grpc.CallOption) (*BuildStatusResponse, error)
	// BuildLogs streams build log lines in real time. Sends existing lines from
	// the given offset, then continues streaming new lines until the build completes.
	BuildLogs(ctx context.Context, in *BuildLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BuildLogEntry], error)
	// DeleteImages removes all OCI images for a project from the registry.
	DeleteImages(ctx context.Context, in *DeleteImagesRequest, opts ...grpc.CallOption) (*DeleteImagesResponse, error)
}

type builderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuilderServiceClient(cc grpc.ClientConnInterface) BuilderServiceClient {
	return &builderServiceClient{cc}
}

func (c *builderServiceClient) DetectServices(ctx context.Context, in *DetectServicesRequest, opts ...grpc.CallOption) (*DetectServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectServicesResponse)
	err := c.cc.Invoke(ctx, BuilderService_DetectServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderServiceClient) StartBuild(ctx context.Context, in *StartBuildRequest, opts ...grpc.CallOption) (*StartBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartBuildResponse)
	err := c.cc.Invoke(ctx, BuilderService_StartBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderServiceClient) BuildStatus(ctx context.Context, in *BuildStatusRequest, opts ...grpc.CallOption) (*BuildStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildStatusResponse)
	err := c.cc.Invoke(ctx, BuilderService_BuildStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderServiceClient) BuildLogs(ctx context.Context, in *BuildLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BuildLogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BuilderService_ServiceDesc.Streams[0], BuilderService_BuildLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BuildLogsRequest, BuildLogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BuilderService_BuildLogsClient = grpc.ServerStreamingClient[BuildLogEntry]

func (c *builderServiceClient) DeleteImages(ctx context.Context, in *DeleteImagesRequest, opts ...grpc.CallOption) (*DeleteImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteImagesResponse)
	err := c.cc.Invoke(ctx, BuilderService_DeleteImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuilderServiceServer is the server API for BuilderService service.
// All implementations must embed UnimplementedBuilderServiceServer
// for forward compatibility.
type BuilderServiceServer interface {
	// DetectServices scans a source repository and returns detected services
	// with their language, framework, and suggested configuration.
	DetectServices(context.Context, *DetectServicesRequest) (*DetectServicesResponse, error)
	// StartBuild starts an asynchronous container image build from source code
	// using railpack and returns a build ID for status polling.
	StartBuild(context.Context, *StartBuildRequest) (*StartBuildResponse, error)
	// BuildStatus returns the current status of an in-progress or completed build.
	BuildStatus(context.Context, *BuildStatusRequest) (*BuildStatusResponse, error)
	// BuildLogs streams build log lines in real time. Sends existing lines from
	// the given offset, then continues streaming new lines until the build completes.
	BuildLogs(*BuildLogsRequest, grpc.ServerStreamingServer[BuildLogEntry]) error
	// DeleteImages removes all OCI images for a project from the registry.
	DeleteImages(context.Context, *DeleteImagesRequest) (*DeleteImagesResponse, error)
	mustEmbedUnimplementedBuilderServiceServer()
}

// UnimplementedBuilderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuilderServiceServer struct{}

func (UnimplementedBuilderServiceServer) DetectServices(context.Context, *DetectServicesRequest) (*DetectServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectServices not implemented")
}
func (UnimplementedBuilderServiceServer) StartBuild(context.Context, *StartBuildRequest) (*StartBuildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartBuild not implemented")
}
func (UnimplementedBuilderServiceServer) BuildStatus(context.Context, *BuildStatusRequest) (*BuildStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildStatus not implemented")
}
func (UnimplementedBuilderServiceServer) BuildLogs(*BuildLogsRequest, grpc.ServerStreamingServer[BuildLogEntry]) error {
	return status.Errorf(codes.Unimplemented, "method BuildLogs not implemented")
}
func (UnimplementedBuilderServiceServer) DeleteImages(context.Context, *DeleteImagesRequest) (*DeleteImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteImages not implemented")
}
func (UnimplementedBuilderServiceServer) mustEmbedUnimplementedBuilderServiceServer() {}
func (UnimplementedBuilderServiceServer) testEmbeddedByValue()                        {}

// UnsafeBuilderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuilderServiceServer will
// result in compilation errors.
type UnsafeBuilderServiceServer interface {
	mustEmbedUnimplementedBuilderServiceServer()
}

func RegisterBuilderServiceServer(s grpc.ServiceRegistrar, srv BuilderServiceServer) {
	// If the following call pancis, it indicates UnimplementedBuilderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuilderService_ServiceDesc, srv)
}

func _BuilderService_DetectServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServiceServer).DetectServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderService_DetectServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServiceServer).DetectServices(ctx, req.(*DetectServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuilderService_StartBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServiceServer).StartBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderService_StartBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServiceServer).StartBuild(ctx, req.(*StartBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuilderService_BuildStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServiceServer).BuildStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderService_BuildStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServiceServer).BuildStatus(ctx, req.(*BuildStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuilderService_BuildLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BuilderServiceServer).BuildLogs(m, &grpc.GenericServerStream[BuildLogsRequest, BuildLogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BuilderService_BuildLogsServer = grpc.ServerStreamingServer[BuildLogEntry]

func _BuilderService_DeleteImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServiceServer).DeleteImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderService_DeleteImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServiceServer).DeleteImages(ctx, req.(*DeleteImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuilderService_ServiceDesc is the grpc.ServiceDesc for BuilderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuilderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "builder.BuilderService",
	HandlerType: (*BuilderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectServices",
			Handler:    _BuilderService_DetectServices_Handler,
		},
		{
			MethodName: "StartBuild",
			Handler:    _BuilderService_StartBuild_Handler,
		},
		{
			MethodName: "BuildStatus",
			Handler:    _BuilderService_BuildStatus_Handler,
		},
		{
			MethodName: "DeleteImages",
			Handler:    _BuilderService_DeleteImages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BuildLogs",
			Handler:       _BuilderService_BuildLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "builder.proto",
}
