{{- if .Values.builder.serviceAccount.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lucity.fullname" . }}-buildkit
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
    app.kubernetes.io/component: builder
data:
  buildkitd.toml: |
    [registry."{{ .Values.builder.registryHost | default "lucity-infra-zot.lucity-system.svc.cluster.local:5000" }}"]
      http = true
      insecure = true
{{- end }}
