{{- if .Values.conductor.buildkit.enabled }}
{{- $ns := .Values.conductor.buildNamespace | default "lucity-builds" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lucity.fullname" . }}-buildkit
  namespace: {{ $ns }}
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
    app.kubernetes.io/component: builder
data:
  buildkitd.toml: |
    [registry."{{ .Values.conductor.registryHost | default "lucity-infra-zot.lucity-system.svc.cluster.local:5000" }}"]
      http = true
      insecure = true
{{- end }}
