apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lucity.fullname" . }}-builder
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
    app.kubernetes.io/component: builder
spec:
  replicas: {{ .Values.builder.replicaCount }}
  selector:
    matchLabels:
      {{- include "lucity.selectorLabels" (dict "name" "builder" "release" .Release.Name) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "lucity.labels" . | nindent 8 }}
        {{- include "lucity.selectorLabels" (dict "name" "builder" "release" .Release.Name) | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.builder.serviceAccount.create }}
      serviceAccountName: {{ include "lucity.fullname" . }}-builder
      {{- end }}
      containers:
        - name: builder
          image: "{{ .Values.builder.image.repository }}:{{ .Values.builder.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.builder.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.builder.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.builder.port | quote }}
            {{- range $key, $value := .Values.builder.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.builder.envSecret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "lucity.fullname" $ }}
                  key: {{ $value }}
            {{- end }}
          resources:
            {{- toYaml .Values.builder.resources | nindent 12 }}
