{{- if .Values.builder.serviceAccount.create }}
{{- $ns := .Values.builder.buildNamespace | default "lucity-builds" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lucity.fullname" . }}-buildkit
  namespace: {{ $ns }}
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
    app.kubernetes.io/component: buildkit
spec:
  type: ClusterIP
  ports:
    - port: 1234
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "lucity.selectorLabels" (dict "name" "buildkit" "release" .Release.Name) | nindent 4 }}
{{- end }}
