{{- if .Values.conductor.buildkit.enabled }}
{{- $ns := .Values.conductor.buildNamespace | default "lucity-builds" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
    app.kubernetes.io/component: builds
{{- end }}
