apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lucity.fullname" . }}-deployer
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
    app.kubernetes.io/component: deployer
spec:
  replicas: {{ .Values.deployer.replicaCount }}
  selector:
    matchLabels:
      {{- include "lucity.selectorLabels" (dict "name" "deployer" "release" .Release.Name) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "lucity.labels" . | nindent 8 }}
        {{- include "lucity.selectorLabels" (dict "name" "deployer" "release" .Release.Name) | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployer.serviceAccount.create }}
      serviceAccountName: {{ include "lucity.fullname" . }}-deployer
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
        - name: deployer
          image: "{{ .Values.deployer.image.repository }}:{{ .Values.deployer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployer.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
          ports:
            - name: grpc
              containerPort: {{ .Values.deployer.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 3
            periodSeconds: 10
          env:
            - name: PORT
              value: {{ .Values.deployer.port | quote }}
            {{- range $key, $value := .Values.deployer.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.deployer.envSecret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "lucity.fullname" $ }}
                  key: {{ $value }}
            {{- end }}
          resources:
            {{- toYaml .Values.deployer.resources | nindent 12 }}
