{{- if .Values.secrets.EDGE_HEADER_SECRET }}
apiVersion: v1
kind: Secret
metadata:
  name: lucity-edge
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
type: Opaque
data:
  value: {{ .Values.secrets.EDGE_HEADER_SECRET | toString | b64enc | quote }}
{{- end }}
