apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lucity.fullname" . }}-gateway
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "lucity.selectorLabels" (dict "name" "gateway" "release" .Release.Name) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "lucity.labels" . | nindent 8 }}
        {{- include "lucity.selectorLabels" (dict "name" "gateway" "release" .Release.Name) | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.gateway.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.gateway.port | quote }}
            {{- range $key, $value := .Values.gateway.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.gateway.envSecret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "lucity.fullname" $ }}
                  key: {{ $value }}
            {{- end }}
          {{- if .Values.githubPrivateKey }}
          volumeMounts:
            - name: github-app-key
              mountPath: /secrets/github
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
      {{- if .Values.githubPrivateKey }}
      volumes:
        - name: github-app-key
          secret:
            secretName: {{ include "lucity.fullname" . }}-github-app
      {{- end }}
