apiVersion: v1
kind: Service
metadata:
  name: {{ include "lucity.fullname" . }}-gateway
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lucity.selectorLabels" (dict "name" "gateway" "release" .Release.Name) | nindent 4 }}
