apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lucity.fullname" . }}-packager
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
    app.kubernetes.io/component: packager
spec:
  replicas: {{ .Values.packager.replicaCount }}
  selector:
    matchLabels:
      {{- include "lucity.selectorLabels" (dict "name" "packager" "release" .Release.Name) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "lucity.labels" . | nindent 8 }}
        {{- include "lucity.selectorLabels" (dict "name" "packager" "release" .Release.Name) | nindent 8 }}
    spec:
      containers:
        - name: packager
          image: "{{ .Values.packager.image.repository }}:{{ .Values.packager.image.tag }}"
          imagePullPolicy: {{ .Values.packager.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.packager.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.packager.port | quote }}
            {{- range $key, $value := .Values.packager.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.packager.envSecret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "lucity.fullname" $ }}
                  key: {{ $value }}
            {{- end }}
          {{- if .Values.softserveKey }}
          volumeMounts:
            - name: softserve-key
              mountPath: /secrets/softserve
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.packager.resources | nindent 12 }}
      {{- if .Values.softserveKey }}
      volumes:
        - name: softserve-key
          secret:
            secretName: {{ include "lucity.fullname" . }}-softserve-key
      {{- end }}
