{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lucity.fullname" . }}
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.githubPrivateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lucity.fullname" . }}-github-app
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-app.pem: {{ .Values.githubPrivateKey | quote }}
{{- end }}
---
{{- if .Values.softserveKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lucity.fullname" . }}-softserve-key
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-key: {{ .Values.softserveKey | quote }}
{{- end }}
---
{{- if and .Values.registryPull .Values.registryPull.host .Values.registryPull.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lucity.fullname" . }}-registry-pull
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ printf `{"auths":{"%s":{"username":"%s","password":"%s"}}}` .Values.registryPull.host .Values.registryPull.username .Values.registryPull.password | quote }}
{{- end }}
