apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lucity.fullname" . }}-webhook
  labels:
    {{- include "lucity.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      {{- include "lucity.selectorLabels" (dict "name" "webhook" "release" .Release.Name) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "lucity.labels" . | nindent 8 }}
        {{- include "lucity.selectorLabels" (dict "name" "webhook" "release" .Release.Name) | nindent 8 }}
    spec:
      containers:
        - name: webhook
          image: "{{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag }}"
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webhook.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.webhook.port | quote }}
            {{- range $key, $value := .Values.webhook.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.webhook.envSecret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "lucity.fullname" $ }}
                  key: {{ $value }}
            {{- end }}
          {{- if .Values.githubPrivateKey }}
          volumeMounts:
            - name: github-app-key
              mountPath: /secrets/github
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
      {{- if .Values.githubPrivateKey }}
      volumes:
        - name: github-app-key
          secret:
            secretName: {{ include "lucity.fullname" . }}-github-app
      {{- end }}
