// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: deployer.proto

package deployer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeployerService_DeployEnvironment_FullMethodName   = "/deployer.DeployerService/DeployEnvironment"
	DeployerService_RemoveDeployment_FullMethodName    = "/deployer.DeployerService/RemoveDeployment"
	DeployerService_GetDeploymentStatus_FullMethodName = "/deployer.DeployerService/GetDeploymentStatus"
	DeployerService_SyncDeployment_FullMethodName      = "/deployer.DeployerService/SyncDeployment"
	DeployerService_DeleteRepository_FullMethodName    = "/deployer.DeployerService/DeleteRepository"
	DeployerService_ServiceLogs_FullMethodName         = "/deployer.DeployerService/ServiceLogs"
	DeployerService_DatabaseTables_FullMethodName      = "/deployer.DeployerService/DatabaseTables"
	DeployerService_DatabaseTableData_FullMethodName   = "/deployer.DeployerService/DatabaseTableData"
	DeployerService_DatabaseQuery_FullMethodName       = "/deployer.DeployerService/DatabaseQuery"
	DeployerService_DatabaseStatus_FullMethodName      = "/deployer.DeployerService/DatabaseStatus"
)

// DeployerServiceClient is the client API for DeployerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeployerServiceClient interface {
	// DeployEnvironment creates a deployment for an environment.
	DeployEnvironment(ctx context.Context, in *DeployEnvironmentRequest, opts ...grpc.CallOption) (*DeployEnvironmentResponse, error)
	// RemoveDeployment removes the deployment for an environment.
	RemoveDeployment(ctx context.Context, in *RemoveDeploymentRequest, opts ...grpc.CallOption) (*RemoveDeploymentResponse, error)
	// GetDeploymentStatus returns the current deployment status of an environment.
	GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error)
	// SyncDeployment triggers a sync for an environment's deployment.
	SyncDeployment(ctx context.Context, in *SyncDeploymentRequest, opts ...grpc.CallOption) (*SyncDeploymentResponse, error)
	// DeleteRepository removes the ArgoCD repository credential for a project.
	DeleteRepository(ctx context.Context, in *DeleteRepositoryRequest, opts ...grpc.CallOption) (*DeleteRepositoryResponse, error)
	// ServiceLogs streams real-time stdout/stderr from running pods for a service.
	ServiceLogs(ctx context.Context, in *ServiceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceLogEntry], error)
	// DatabaseTables returns the tables and their schema for a database.
	DatabaseTables(ctx context.Context, in *DatabaseTablesRequest, opts ...grpc.CallOption) (*DatabaseTablesResponse, error)
	// DatabaseTableData returns paginated rows from a table.
	DatabaseTableData(ctx context.Context, in *DatabaseTableDataRequest, opts ...grpc.CallOption) (*DatabaseTableDataResponse, error)
	// DatabaseQuery executes an arbitrary SQL query and returns results.
	DatabaseQuery(ctx context.Context, in *DatabaseQueryRequest, opts ...grpc.CallOption) (*DatabaseQueryResponse, error)
	// DatabaseStatus returns the runtime status of a database in an environment.
	DatabaseStatus(ctx context.Context, in *DatabaseStatusRequest, opts ...grpc.CallOption) (*DatabaseStatusResponse, error)
}

type deployerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployerServiceClient(cc grpc.ClientConnInterface) DeployerServiceClient {
	return &deployerServiceClient{cc}
}

func (c *deployerServiceClient) DeployEnvironment(ctx context.Context, in *DeployEnvironmentRequest, opts ...grpc.CallOption) (*DeployEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployEnvironmentResponse)
	err := c.cc.Invoke(ctx, DeployerService_DeployEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) RemoveDeployment(ctx context.Context, in *RemoveDeploymentRequest, opts ...grpc.CallOption) (*RemoveDeploymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveDeploymentResponse)
	err := c.cc.Invoke(ctx, DeployerService_RemoveDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeploymentStatusResponse)
	err := c.cc.Invoke(ctx, DeployerService_GetDeploymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) SyncDeployment(ctx context.Context, in *SyncDeploymentRequest, opts ...grpc.CallOption) (*SyncDeploymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncDeploymentResponse)
	err := c.cc.Invoke(ctx, DeployerService_SyncDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) DeleteRepository(ctx context.Context, in *DeleteRepositoryRequest, opts ...grpc.CallOption) (*DeleteRepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRepositoryResponse)
	err := c.cc.Invoke(ctx, DeployerService_DeleteRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) ServiceLogs(ctx context.Context, in *ServiceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceLogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeployerService_ServiceDesc.Streams[0], DeployerService_ServiceLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServiceLogsRequest, ServiceLogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeployerService_ServiceLogsClient = grpc.ServerStreamingClient[ServiceLogEntry]

func (c *deployerServiceClient) DatabaseTables(ctx context.Context, in *DatabaseTablesRequest, opts ...grpc.CallOption) (*DatabaseTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseTablesResponse)
	err := c.cc.Invoke(ctx, DeployerService_DatabaseTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) DatabaseTableData(ctx context.Context, in *DatabaseTableDataRequest, opts ...grpc.CallOption) (*DatabaseTableDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseTableDataResponse)
	err := c.cc.Invoke(ctx, DeployerService_DatabaseTableData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) DatabaseQuery(ctx context.Context, in *DatabaseQueryRequest, opts ...grpc.CallOption) (*DatabaseQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseQueryResponse)
	err := c.cc.Invoke(ctx, DeployerService_DatabaseQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) DatabaseStatus(ctx context.Context, in *DatabaseStatusRequest, opts ...grpc.CallOption) (*DatabaseStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseStatusResponse)
	err := c.cc.Invoke(ctx, DeployerService_DatabaseStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployerServiceServer is the server API for DeployerService service.
// All implementations must embed UnimplementedDeployerServiceServer
// for forward compatibility.
type DeployerServiceServer interface {
	// DeployEnvironment creates a deployment for an environment.
	DeployEnvironment(context.Context, *DeployEnvironmentRequest) (*DeployEnvironmentResponse, error)
	// RemoveDeployment removes the deployment for an environment.
	RemoveDeployment(context.Context, *RemoveDeploymentRequest) (*RemoveDeploymentResponse, error)
	// GetDeploymentStatus returns the current deployment status of an environment.
	GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error)
	// SyncDeployment triggers a sync for an environment's deployment.
	SyncDeployment(context.Context, *SyncDeploymentRequest) (*SyncDeploymentResponse, error)
	// DeleteRepository removes the ArgoCD repository credential for a project.
	DeleteRepository(context.Context, *DeleteRepositoryRequest) (*DeleteRepositoryResponse, error)
	// ServiceLogs streams real-time stdout/stderr from running pods for a service.
	ServiceLogs(*ServiceLogsRequest, grpc.ServerStreamingServer[ServiceLogEntry]) error
	// DatabaseTables returns the tables and their schema for a database.
	DatabaseTables(context.Context, *DatabaseTablesRequest) (*DatabaseTablesResponse, error)
	// DatabaseTableData returns paginated rows from a table.
	DatabaseTableData(context.Context, *DatabaseTableDataRequest) (*DatabaseTableDataResponse, error)
	// DatabaseQuery executes an arbitrary SQL query and returns results.
	DatabaseQuery(context.Context, *DatabaseQueryRequest) (*DatabaseQueryResponse, error)
	// DatabaseStatus returns the runtime status of a database in an environment.
	DatabaseStatus(context.Context, *DatabaseStatusRequest) (*DatabaseStatusResponse, error)
	mustEmbedUnimplementedDeployerServiceServer()
}

// UnimplementedDeployerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeployerServiceServer struct{}

func (UnimplementedDeployerServiceServer) DeployEnvironment(context.Context, *DeployEnvironmentRequest) (*DeployEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployEnvironment not implemented")
}
func (UnimplementedDeployerServiceServer) RemoveDeployment(context.Context, *RemoveDeploymentRequest) (*RemoveDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDeployment not implemented")
}
func (UnimplementedDeployerServiceServer) GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentStatus not implemented")
}
func (UnimplementedDeployerServiceServer) SyncDeployment(context.Context, *SyncDeploymentRequest) (*SyncDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncDeployment not implemented")
}
func (UnimplementedDeployerServiceServer) DeleteRepository(context.Context, *DeleteRepositoryRequest) (*DeleteRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRepository not implemented")
}
func (UnimplementedDeployerServiceServer) ServiceLogs(*ServiceLogsRequest, grpc.ServerStreamingServer[ServiceLogEntry]) error {
	return status.Errorf(codes.Unimplemented, "method ServiceLogs not implemented")
}
func (UnimplementedDeployerServiceServer) DatabaseTables(context.Context, *DatabaseTablesRequest) (*DatabaseTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatabaseTables not implemented")
}
func (UnimplementedDeployerServiceServer) DatabaseTableData(context.Context, *DatabaseTableDataRequest) (*DatabaseTableDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatabaseTableData not implemented")
}
func (UnimplementedDeployerServiceServer) DatabaseQuery(context.Context, *DatabaseQueryRequest) (*DatabaseQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatabaseQuery not implemented")
}
func (UnimplementedDeployerServiceServer) DatabaseStatus(context.Context, *DatabaseStatusRequest) (*DatabaseStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatabaseStatus not implemented")
}
func (UnimplementedDeployerServiceServer) mustEmbedUnimplementedDeployerServiceServer() {}
func (UnimplementedDeployerServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeployerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeployerServiceServer will
// result in compilation errors.
type UnsafeDeployerServiceServer interface {
	mustEmbedUnimplementedDeployerServiceServer()
}

func RegisterDeployerServiceServer(s grpc.ServiceRegistrar, srv DeployerServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeployerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeployerService_ServiceDesc, srv)
}

func _DeployerService_DeployEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DeployEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DeployEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DeployEnvironment(ctx, req.(*DeployEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_RemoveDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).RemoveDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_RemoveDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).RemoveDeployment(ctx, req.(*RemoveDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_GetDeploymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).GetDeploymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_GetDeploymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).GetDeploymentStatus(ctx, req.(*GetDeploymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_SyncDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).SyncDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_SyncDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).SyncDeployment(ctx, req.(*SyncDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_DeleteRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DeleteRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DeleteRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DeleteRepository(ctx, req.(*DeleteRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_ServiceLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeployerServiceServer).ServiceLogs(m, &grpc.GenericServerStream[ServiceLogsRequest, ServiceLogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeployerService_ServiceLogsServer = grpc.ServerStreamingServer[ServiceLogEntry]

func _DeployerService_DatabaseTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DatabaseTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DatabaseTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DatabaseTables(ctx, req.(*DatabaseTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_DatabaseTableData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseTableDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DatabaseTableData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DatabaseTableData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DatabaseTableData(ctx, req.(*DatabaseTableDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_DatabaseQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DatabaseQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DatabaseQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DatabaseQuery(ctx, req.(*DatabaseQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_DatabaseStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DatabaseStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DatabaseStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DatabaseStatus(ctx, req.(*DatabaseStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeployerService_ServiceDesc is the grpc.ServiceDesc for DeployerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeployerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deployer.DeployerService",
	HandlerType: (*DeployerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployEnvironment",
			Handler:    _DeployerService_DeployEnvironment_Handler,
		},
		{
			MethodName: "RemoveDeployment",
			Handler:    _DeployerService_RemoveDeployment_Handler,
		},
		{
			MethodName: "GetDeploymentStatus",
			Handler:    _DeployerService_GetDeploymentStatus_Handler,
		},
		{
			MethodName: "SyncDeployment",
			Handler:    _DeployerService_SyncDeployment_Handler,
		},
		{
			MethodName: "DeleteRepository",
			Handler:    _DeployerService_DeleteRepository_Handler,
		},
		{
			MethodName: "DatabaseTables",
			Handler:    _DeployerService_DatabaseTables_Handler,
		},
		{
			MethodName: "DatabaseTableData",
			Handler:    _DeployerService_DatabaseTableData_Handler,
		},
		{
			MethodName: "DatabaseQuery",
			Handler:    _DeployerService_DatabaseQuery_Handler,
		},
		{
			MethodName: "DatabaseStatus",
			Handler:    _DeployerService_DatabaseStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServiceLogs",
			Handler:       _DeployerService_ServiceLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "deployer.proto",
}
