// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: deployer.proto

package deployer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeployerService_DeployEnvironment_FullMethodName         = "/deployer.DeployerService/DeployEnvironment"
	DeployerService_RemoveDeployment_FullMethodName          = "/deployer.DeployerService/RemoveDeployment"
	DeployerService_GetDeploymentStatus_FullMethodName       = "/deployer.DeployerService/GetDeploymentStatus"
	DeployerService_SyncDeployment_FullMethodName            = "/deployer.DeployerService/SyncDeployment"
	DeployerService_DeleteRepository_FullMethodName          = "/deployer.DeployerService/DeleteRepository"
	DeployerService_ServiceLogs_FullMethodName               = "/deployer.DeployerService/ServiceLogs"
	DeployerService_DatabaseTables_FullMethodName            = "/deployer.DeployerService/DatabaseTables"
	DeployerService_DatabaseTableData_FullMethodName         = "/deployer.DeployerService/DatabaseTableData"
	DeployerService_DatabaseQuery_FullMethodName             = "/deployer.DeployerService/DatabaseQuery"
	DeployerService_DatabaseStatus_FullMethodName            = "/deployer.DeployerService/DatabaseStatus"
	DeployerService_ServiceStatus_FullMethodName             = "/deployer.DeployerService/ServiceStatus"
	DeployerService_SetServiceScaling_FullMethodName         = "/deployer.DeployerService/SetServiceScaling"
	DeployerService_DatabaseCredentials_FullMethodName       = "/deployer.DeployerService/DatabaseCredentials"
	DeployerService_WorkspaceByInstallationID_FullMethodName = "/deployer.DeployerService/WorkspaceByInstallationID"
	DeployerService_SetResourceQuota_FullMethodName          = "/deployer.DeployerService/SetResourceQuota"
	DeployerService_ResourceQuota_FullMethodName             = "/deployer.DeployerService/ResourceQuota"
	DeployerService_ListResourceAllocations_FullMethodName   = "/deployer.DeployerService/ListResourceAllocations"
	DeployerService_StoreUserGitHubToken_FullMethodName      = "/deployer.DeployerService/StoreUserGitHubToken"
	DeployerService_UserGitHubToken_FullMethodName           = "/deployer.DeployerService/UserGitHubToken"
	DeployerService_DeleteUserGitHubToken_FullMethodName     = "/deployer.DeployerService/DeleteUserGitHubToken"
	DeployerService_SuspendWorkspace_FullMethodName          = "/deployer.DeployerService/SuspendWorkspace"
	DeployerService_ProvisionCustomDomain_FullMethodName     = "/deployer.DeployerService/ProvisionCustomDomain"
	DeployerService_DeleteCustomDomain_FullMethodName        = "/deployer.DeployerService/DeleteCustomDomain"
	DeployerService_CustomDomainStatus_FullMethodName        = "/deployer.DeployerService/CustomDomainStatus"
)

// DeployerServiceClient is the client API for DeployerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeployerServiceClient interface {
	// DeployEnvironment creates a deployment for an environment.
	DeployEnvironment(ctx context.Context, in *DeployEnvironmentRequest, opts ...grpc.CallOption) (*DeployEnvironmentResponse, error)
	// RemoveDeployment removes the deployment for an environment.
	RemoveDeployment(ctx context.Context, in *RemoveDeploymentRequest, opts ...grpc.CallOption) (*RemoveDeploymentResponse, error)
	// GetDeploymentStatus returns the current deployment status of an environment.
	GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error)
	// SyncDeployment triggers a sync for an environment's deployment.
	SyncDeployment(ctx context.Context, in *SyncDeploymentRequest, opts ...grpc.CallOption) (*SyncDeploymentResponse, error)
	// DeleteRepository removes the ArgoCD repository credential for a project.
	DeleteRepository(ctx context.Context, in *DeleteRepositoryRequest, opts ...grpc.CallOption) (*DeleteRepositoryResponse, error)
	// ServiceLogs streams real-time stdout/stderr from running pods for a service.
	ServiceLogs(ctx context.Context, in *ServiceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceLogEntry], error)
	// DatabaseTables returns the tables and their schema for a database.
	DatabaseTables(ctx context.Context, in *DatabaseTablesRequest, opts ...grpc.CallOption) (*DatabaseTablesResponse, error)
	// DatabaseTableData returns paginated rows from a table.
	DatabaseTableData(ctx context.Context, in *DatabaseTableDataRequest, opts ...grpc.CallOption) (*DatabaseTableDataResponse, error)
	// DatabaseQuery executes an arbitrary SQL query and returns results.
	DatabaseQuery(ctx context.Context, in *DatabaseQueryRequest, opts ...grpc.CallOption) (*DatabaseQueryResponse, error)
	// DatabaseStatus returns the runtime status of a database in an environment.
	DatabaseStatus(ctx context.Context, in *DatabaseStatusRequest, opts ...grpc.CallOption) (*DatabaseStatusResponse, error)
	// ServiceStatus returns the runtime status of a service's K8s Deployment in an environment.
	ServiceStatus(ctx context.Context, in *ServiceStatusRequest, opts ...grpc.CallOption) (*ServiceStatusResponse, error)
	// SetServiceScaling sets the replica count or creates/updates an HPA for a service.
	SetServiceScaling(ctx context.Context, in *SetServiceScalingRequest, opts ...grpc.CallOption) (*SetServiceScalingResponse, error)
	// DatabaseCredentials returns the resolved connection credentials for a database.
	DatabaseCredentials(ctx context.Context, in *DatabaseCredentialsRequest, opts ...grpc.CallOption) (*DatabaseCredentialsResponse, error)
	// WorkspaceByInstallationID finds a workspace by its GitHub App installation ID.
	WorkspaceByInstallationID(ctx context.Context, in *WorkspaceByInstallationIDRequest, opts ...grpc.CallOption) (*WorkspaceByInstallationIDResponse, error)
	// SetResourceQuota creates or updates a ResourceQuota, LimitRange, and tier label on a namespace.
	SetResourceQuota(ctx context.Context, in *SetResourceQuotaRequest, opts ...grpc.CallOption) (*SetResourceQuotaResponse, error)
	// ResourceQuota returns the current resource quota and tier for an environment namespace.
	ResourceQuota(ctx context.Context, in *ResourceQuotaRequest, opts ...grpc.CallOption) (*ResourceQuotaResponse, error)
	// ListResourceAllocations returns resource quotas and tiers for all managed namespaces.
	ListResourceAllocations(ctx context.Context, in *ListResourceAllocationsRequest, opts ...grpc.CallOption) (*ListResourceAllocationsResponse, error)
	// StoreUserGitHubToken stores a GitHub OAuth token for a user in a K8s Secret.
	StoreUserGitHubToken(ctx context.Context, in *StoreUserGitHubTokenRequest, opts ...grpc.CallOption) (*StoreUserGitHubTokenResponse, error)
	// UserGitHubToken retrieves a user's stored GitHub OAuth token.
	UserGitHubToken(ctx context.Context, in *UserGitHubTokenRequest, opts ...grpc.CallOption) (*UserGitHubTokenResponse, error)
	// DeleteUserGitHubToken removes a user's stored GitHub OAuth token.
	DeleteUserGitHubToken(ctx context.Context, in *DeleteUserGitHubTokenRequest, opts ...grpc.CallOption) (*DeleteUserGitHubTokenResponse, error)
	// SuspendWorkspace suspends or resumes all workloads in a workspace.
	SuspendWorkspace(ctx context.Context, in *SuspendWorkspaceRequest, opts ...grpc.CallOption) (*SuspendWorkspaceResponse, error)
	// ProvisionCustomDomain creates a cert-manager Certificate for a custom domain and patches the Gateway.
	ProvisionCustomDomain(ctx context.Context, in *ProvisionCustomDomainRequest, opts ...grpc.CallOption) (*ProvisionCustomDomainResponse, error)
	// DeleteCustomDomain removes the Certificate and Gateway cert ref for a custom domain.
	DeleteCustomDomain(ctx context.Context, in *DeleteCustomDomainRequest, opts ...grpc.CallOption) (*DeleteCustomDomainResponse, error)
	// CustomDomainStatus returns the TLS certificate status for a custom domain.
	CustomDomainStatus(ctx context.Context, in *CustomDomainStatusRequest, opts ...grpc.CallOption) (*CustomDomainStatusResponse, error)
}

type deployerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployerServiceClient(cc grpc.ClientConnInterface) DeployerServiceClient {
	return &deployerServiceClient{cc}
}

func (c *deployerServiceClient) DeployEnvironment(ctx context.Context, in *DeployEnvironmentRequest, opts ...grpc.CallOption) (*DeployEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployEnvironmentResponse)
	err := c.cc.Invoke(ctx, DeployerService_DeployEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) RemoveDeployment(ctx context.Context, in *RemoveDeploymentRequest, opts ...grpc.CallOption) (*RemoveDeploymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveDeploymentResponse)
	err := c.cc.Invoke(ctx, DeployerService_RemoveDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeploymentStatusResponse)
	err := c.cc.Invoke(ctx, DeployerService_GetDeploymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) SyncDeployment(ctx context.Context, in *SyncDeploymentRequest, opts ...grpc.CallOption) (*SyncDeploymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncDeploymentResponse)
	err := c.cc.Invoke(ctx, DeployerService_SyncDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) DeleteRepository(ctx context.Context, in *DeleteRepositoryRequest, opts ...grpc.CallOption) (*DeleteRepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRepositoryResponse)
	err := c.cc.Invoke(ctx, DeployerService_DeleteRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) ServiceLogs(ctx context.Context, in *ServiceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceLogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeployerService_ServiceDesc.Streams[0], DeployerService_ServiceLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServiceLogsRequest, ServiceLogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeployerService_ServiceLogsClient = grpc.ServerStreamingClient[ServiceLogEntry]

func (c *deployerServiceClient) DatabaseTables(ctx context.Context, in *DatabaseTablesRequest, opts ...grpc.CallOption) (*DatabaseTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseTablesResponse)
	err := c.cc.Invoke(ctx, DeployerService_DatabaseTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) DatabaseTableData(ctx context.Context, in *DatabaseTableDataRequest, opts ...grpc.CallOption) (*DatabaseTableDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseTableDataResponse)
	err := c.cc.Invoke(ctx, DeployerService_DatabaseTableData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) DatabaseQuery(ctx context.Context, in *DatabaseQueryRequest, opts ...grpc.CallOption) (*DatabaseQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseQueryResponse)
	err := c.cc.Invoke(ctx, DeployerService_DatabaseQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) DatabaseStatus(ctx context.Context, in *DatabaseStatusRequest, opts ...grpc.CallOption) (*DatabaseStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseStatusResponse)
	err := c.cc.Invoke(ctx, DeployerService_DatabaseStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) ServiceStatus(ctx context.Context, in *ServiceStatusRequest, opts ...grpc.CallOption) (*ServiceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceStatusResponse)
	err := c.cc.Invoke(ctx, DeployerService_ServiceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) SetServiceScaling(ctx context.Context, in *SetServiceScalingRequest, opts ...grpc.CallOption) (*SetServiceScalingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetServiceScalingResponse)
	err := c.cc.Invoke(ctx, DeployerService_SetServiceScaling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) DatabaseCredentials(ctx context.Context, in *DatabaseCredentialsRequest, opts ...grpc.CallOption) (*DatabaseCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseCredentialsResponse)
	err := c.cc.Invoke(ctx, DeployerService_DatabaseCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) WorkspaceByInstallationID(ctx context.Context, in *WorkspaceByInstallationIDRequest, opts ...grpc.CallOption) (*WorkspaceByInstallationIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceByInstallationIDResponse)
	err := c.cc.Invoke(ctx, DeployerService_WorkspaceByInstallationID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) SetResourceQuota(ctx context.Context, in *SetResourceQuotaRequest, opts ...grpc.CallOption) (*SetResourceQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResourceQuotaResponse)
	err := c.cc.Invoke(ctx, DeployerService_SetResourceQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) ResourceQuota(ctx context.Context, in *ResourceQuotaRequest, opts ...grpc.CallOption) (*ResourceQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceQuotaResponse)
	err := c.cc.Invoke(ctx, DeployerService_ResourceQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) ListResourceAllocations(ctx context.Context, in *ListResourceAllocationsRequest, opts ...grpc.CallOption) (*ListResourceAllocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourceAllocationsResponse)
	err := c.cc.Invoke(ctx, DeployerService_ListResourceAllocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) StoreUserGitHubToken(ctx context.Context, in *StoreUserGitHubTokenRequest, opts ...grpc.CallOption) (*StoreUserGitHubTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreUserGitHubTokenResponse)
	err := c.cc.Invoke(ctx, DeployerService_StoreUserGitHubToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) UserGitHubToken(ctx context.Context, in *UserGitHubTokenRequest, opts ...grpc.CallOption) (*UserGitHubTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGitHubTokenResponse)
	err := c.cc.Invoke(ctx, DeployerService_UserGitHubToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) DeleteUserGitHubToken(ctx context.Context, in *DeleteUserGitHubTokenRequest, opts ...grpc.CallOption) (*DeleteUserGitHubTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserGitHubTokenResponse)
	err := c.cc.Invoke(ctx, DeployerService_DeleteUserGitHubToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) SuspendWorkspace(ctx context.Context, in *SuspendWorkspaceRequest, opts ...grpc.CallOption) (*SuspendWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendWorkspaceResponse)
	err := c.cc.Invoke(ctx, DeployerService_SuspendWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) ProvisionCustomDomain(ctx context.Context, in *ProvisionCustomDomainRequest, opts ...grpc.CallOption) (*ProvisionCustomDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionCustomDomainResponse)
	err := c.cc.Invoke(ctx, DeployerService_ProvisionCustomDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) DeleteCustomDomain(ctx context.Context, in *DeleteCustomDomainRequest, opts ...grpc.CallOption) (*DeleteCustomDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCustomDomainResponse)
	err := c.cc.Invoke(ctx, DeployerService_DeleteCustomDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) CustomDomainStatus(ctx context.Context, in *CustomDomainStatusRequest, opts ...grpc.CallOption) (*CustomDomainStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomDomainStatusResponse)
	err := c.cc.Invoke(ctx, DeployerService_CustomDomainStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployerServiceServer is the server API for DeployerService service.
// All implementations must embed UnimplementedDeployerServiceServer
// for forward compatibility.
type DeployerServiceServer interface {
	// DeployEnvironment creates a deployment for an environment.
	DeployEnvironment(context.Context, *DeployEnvironmentRequest) (*DeployEnvironmentResponse, error)
	// RemoveDeployment removes the deployment for an environment.
	RemoveDeployment(context.Context, *RemoveDeploymentRequest) (*RemoveDeploymentResponse, error)
	// GetDeploymentStatus returns the current deployment status of an environment.
	GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error)
	// SyncDeployment triggers a sync for an environment's deployment.
	SyncDeployment(context.Context, *SyncDeploymentRequest) (*SyncDeploymentResponse, error)
	// DeleteRepository removes the ArgoCD repository credential for a project.
	DeleteRepository(context.Context, *DeleteRepositoryRequest) (*DeleteRepositoryResponse, error)
	// ServiceLogs streams real-time stdout/stderr from running pods for a service.
	ServiceLogs(*ServiceLogsRequest, grpc.ServerStreamingServer[ServiceLogEntry]) error
	// DatabaseTables returns the tables and their schema for a database.
	DatabaseTables(context.Context, *DatabaseTablesRequest) (*DatabaseTablesResponse, error)
	// DatabaseTableData returns paginated rows from a table.
	DatabaseTableData(context.Context, *DatabaseTableDataRequest) (*DatabaseTableDataResponse, error)
	// DatabaseQuery executes an arbitrary SQL query and returns results.
	DatabaseQuery(context.Context, *DatabaseQueryRequest) (*DatabaseQueryResponse, error)
	// DatabaseStatus returns the runtime status of a database in an environment.
	DatabaseStatus(context.Context, *DatabaseStatusRequest) (*DatabaseStatusResponse, error)
	// ServiceStatus returns the runtime status of a service's K8s Deployment in an environment.
	ServiceStatus(context.Context, *ServiceStatusRequest) (*ServiceStatusResponse, error)
	// SetServiceScaling sets the replica count or creates/updates an HPA for a service.
	SetServiceScaling(context.Context, *SetServiceScalingRequest) (*SetServiceScalingResponse, error)
	// DatabaseCredentials returns the resolved connection credentials for a database.
	DatabaseCredentials(context.Context, *DatabaseCredentialsRequest) (*DatabaseCredentialsResponse, error)
	// WorkspaceByInstallationID finds a workspace by its GitHub App installation ID.
	WorkspaceByInstallationID(context.Context, *WorkspaceByInstallationIDRequest) (*WorkspaceByInstallationIDResponse, error)
	// SetResourceQuota creates or updates a ResourceQuota, LimitRange, and tier label on a namespace.
	SetResourceQuota(context.Context, *SetResourceQuotaRequest) (*SetResourceQuotaResponse, error)
	// ResourceQuota returns the current resource quota and tier for an environment namespace.
	ResourceQuota(context.Context, *ResourceQuotaRequest) (*ResourceQuotaResponse, error)
	// ListResourceAllocations returns resource quotas and tiers for all managed namespaces.
	ListResourceAllocations(context.Context, *ListResourceAllocationsRequest) (*ListResourceAllocationsResponse, error)
	// StoreUserGitHubToken stores a GitHub OAuth token for a user in a K8s Secret.
	StoreUserGitHubToken(context.Context, *StoreUserGitHubTokenRequest) (*StoreUserGitHubTokenResponse, error)
	// UserGitHubToken retrieves a user's stored GitHub OAuth token.
	UserGitHubToken(context.Context, *UserGitHubTokenRequest) (*UserGitHubTokenResponse, error)
	// DeleteUserGitHubToken removes a user's stored GitHub OAuth token.
	DeleteUserGitHubToken(context.Context, *DeleteUserGitHubTokenRequest) (*DeleteUserGitHubTokenResponse, error)
	// SuspendWorkspace suspends or resumes all workloads in a workspace.
	SuspendWorkspace(context.Context, *SuspendWorkspaceRequest) (*SuspendWorkspaceResponse, error)
	// ProvisionCustomDomain creates a cert-manager Certificate for a custom domain and patches the Gateway.
	ProvisionCustomDomain(context.Context, *ProvisionCustomDomainRequest) (*ProvisionCustomDomainResponse, error)
	// DeleteCustomDomain removes the Certificate and Gateway cert ref for a custom domain.
	DeleteCustomDomain(context.Context, *DeleteCustomDomainRequest) (*DeleteCustomDomainResponse, error)
	// CustomDomainStatus returns the TLS certificate status for a custom domain.
	CustomDomainStatus(context.Context, *CustomDomainStatusRequest) (*CustomDomainStatusResponse, error)
	mustEmbedUnimplementedDeployerServiceServer()
}

// UnimplementedDeployerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeployerServiceServer struct{}

func (UnimplementedDeployerServiceServer) DeployEnvironment(context.Context, *DeployEnvironmentRequest) (*DeployEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployEnvironment not implemented")
}
func (UnimplementedDeployerServiceServer) RemoveDeployment(context.Context, *RemoveDeploymentRequest) (*RemoveDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDeployment not implemented")
}
func (UnimplementedDeployerServiceServer) GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentStatus not implemented")
}
func (UnimplementedDeployerServiceServer) SyncDeployment(context.Context, *SyncDeploymentRequest) (*SyncDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncDeployment not implemented")
}
func (UnimplementedDeployerServiceServer) DeleteRepository(context.Context, *DeleteRepositoryRequest) (*DeleteRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRepository not implemented")
}
func (UnimplementedDeployerServiceServer) ServiceLogs(*ServiceLogsRequest, grpc.ServerStreamingServer[ServiceLogEntry]) error {
	return status.Errorf(codes.Unimplemented, "method ServiceLogs not implemented")
}
func (UnimplementedDeployerServiceServer) DatabaseTables(context.Context, *DatabaseTablesRequest) (*DatabaseTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatabaseTables not implemented")
}
func (UnimplementedDeployerServiceServer) DatabaseTableData(context.Context, *DatabaseTableDataRequest) (*DatabaseTableDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatabaseTableData not implemented")
}
func (UnimplementedDeployerServiceServer) DatabaseQuery(context.Context, *DatabaseQueryRequest) (*DatabaseQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatabaseQuery not implemented")
}
func (UnimplementedDeployerServiceServer) DatabaseStatus(context.Context, *DatabaseStatusRequest) (*DatabaseStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatabaseStatus not implemented")
}
func (UnimplementedDeployerServiceServer) ServiceStatus(context.Context, *ServiceStatusRequest) (*ServiceStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceStatus not implemented")
}
func (UnimplementedDeployerServiceServer) SetServiceScaling(context.Context, *SetServiceScalingRequest) (*SetServiceScalingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetServiceScaling not implemented")
}
func (UnimplementedDeployerServiceServer) DatabaseCredentials(context.Context, *DatabaseCredentialsRequest) (*DatabaseCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatabaseCredentials not implemented")
}
func (UnimplementedDeployerServiceServer) WorkspaceByInstallationID(context.Context, *WorkspaceByInstallationIDRequest) (*WorkspaceByInstallationIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkspaceByInstallationID not implemented")
}
func (UnimplementedDeployerServiceServer) SetResourceQuota(context.Context, *SetResourceQuotaRequest) (*SetResourceQuotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetResourceQuota not implemented")
}
func (UnimplementedDeployerServiceServer) ResourceQuota(context.Context, *ResourceQuotaRequest) (*ResourceQuotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResourceQuota not implemented")
}
func (UnimplementedDeployerServiceServer) ListResourceAllocations(context.Context, *ListResourceAllocationsRequest) (*ListResourceAllocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResourceAllocations not implemented")
}
func (UnimplementedDeployerServiceServer) StoreUserGitHubToken(context.Context, *StoreUserGitHubTokenRequest) (*StoreUserGitHubTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreUserGitHubToken not implemented")
}
func (UnimplementedDeployerServiceServer) UserGitHubToken(context.Context, *UserGitHubTokenRequest) (*UserGitHubTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGitHubToken not implemented")
}
func (UnimplementedDeployerServiceServer) DeleteUserGitHubToken(context.Context, *DeleteUserGitHubTokenRequest) (*DeleteUserGitHubTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserGitHubToken not implemented")
}
func (UnimplementedDeployerServiceServer) SuspendWorkspace(context.Context, *SuspendWorkspaceRequest) (*SuspendWorkspaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendWorkspace not implemented")
}
func (UnimplementedDeployerServiceServer) ProvisionCustomDomain(context.Context, *ProvisionCustomDomainRequest) (*ProvisionCustomDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionCustomDomain not implemented")
}
func (UnimplementedDeployerServiceServer) DeleteCustomDomain(context.Context, *DeleteCustomDomainRequest) (*DeleteCustomDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCustomDomain not implemented")
}
func (UnimplementedDeployerServiceServer) CustomDomainStatus(context.Context, *CustomDomainStatusRequest) (*CustomDomainStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomDomainStatus not implemented")
}
func (UnimplementedDeployerServiceServer) mustEmbedUnimplementedDeployerServiceServer() {}
func (UnimplementedDeployerServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeployerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeployerServiceServer will
// result in compilation errors.
type UnsafeDeployerServiceServer interface {
	mustEmbedUnimplementedDeployerServiceServer()
}

func RegisterDeployerServiceServer(s grpc.ServiceRegistrar, srv DeployerServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeployerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeployerService_ServiceDesc, srv)
}

func _DeployerService_DeployEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DeployEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DeployEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DeployEnvironment(ctx, req.(*DeployEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_RemoveDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).RemoveDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_RemoveDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).RemoveDeployment(ctx, req.(*RemoveDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_GetDeploymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).GetDeploymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_GetDeploymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).GetDeploymentStatus(ctx, req.(*GetDeploymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_SyncDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).SyncDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_SyncDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).SyncDeployment(ctx, req.(*SyncDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_DeleteRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DeleteRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DeleteRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DeleteRepository(ctx, req.(*DeleteRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_ServiceLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeployerServiceServer).ServiceLogs(m, &grpc.GenericServerStream[ServiceLogsRequest, ServiceLogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeployerService_ServiceLogsServer = grpc.ServerStreamingServer[ServiceLogEntry]

func _DeployerService_DatabaseTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DatabaseTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DatabaseTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DatabaseTables(ctx, req.(*DatabaseTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_DatabaseTableData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseTableDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DatabaseTableData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DatabaseTableData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DatabaseTableData(ctx, req.(*DatabaseTableDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_DatabaseQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DatabaseQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DatabaseQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DatabaseQuery(ctx, req.(*DatabaseQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_DatabaseStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DatabaseStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DatabaseStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DatabaseStatus(ctx, req.(*DatabaseStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_ServiceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).ServiceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_ServiceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).ServiceStatus(ctx, req.(*ServiceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_SetServiceScaling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetServiceScalingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).SetServiceScaling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_SetServiceScaling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).SetServiceScaling(ctx, req.(*SetServiceScalingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_DatabaseCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DatabaseCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DatabaseCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DatabaseCredentials(ctx, req.(*DatabaseCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_WorkspaceByInstallationID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceByInstallationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).WorkspaceByInstallationID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_WorkspaceByInstallationID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).WorkspaceByInstallationID(ctx, req.(*WorkspaceByInstallationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_SetResourceQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetResourceQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).SetResourceQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_SetResourceQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).SetResourceQuota(ctx, req.(*SetResourceQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_ResourceQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).ResourceQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_ResourceQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).ResourceQuota(ctx, req.(*ResourceQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_ListResourceAllocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourceAllocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).ListResourceAllocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_ListResourceAllocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).ListResourceAllocations(ctx, req.(*ListResourceAllocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_StoreUserGitHubToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreUserGitHubTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).StoreUserGitHubToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_StoreUserGitHubToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).StoreUserGitHubToken(ctx, req.(*StoreUserGitHubTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_UserGitHubToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGitHubTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).UserGitHubToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_UserGitHubToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).UserGitHubToken(ctx, req.(*UserGitHubTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_DeleteUserGitHubToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserGitHubTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DeleteUserGitHubToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DeleteUserGitHubToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DeleteUserGitHubToken(ctx, req.(*DeleteUserGitHubTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_SuspendWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).SuspendWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_SuspendWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).SuspendWorkspace(ctx, req.(*SuspendWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_ProvisionCustomDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionCustomDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).ProvisionCustomDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_ProvisionCustomDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).ProvisionCustomDomain(ctx, req.(*ProvisionCustomDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_DeleteCustomDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCustomDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DeleteCustomDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DeleteCustomDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DeleteCustomDomain(ctx, req.(*DeleteCustomDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_CustomDomainStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomDomainStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).CustomDomainStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_CustomDomainStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).CustomDomainStatus(ctx, req.(*CustomDomainStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeployerService_ServiceDesc is the grpc.ServiceDesc for DeployerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeployerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deployer.DeployerService",
	HandlerType: (*DeployerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployEnvironment",
			Handler:    _DeployerService_DeployEnvironment_Handler,
		},
		{
			MethodName: "RemoveDeployment",
			Handler:    _DeployerService_RemoveDeployment_Handler,
		},
		{
			MethodName: "GetDeploymentStatus",
			Handler:    _DeployerService_GetDeploymentStatus_Handler,
		},
		{
			MethodName: "SyncDeployment",
			Handler:    _DeployerService_SyncDeployment_Handler,
		},
		{
			MethodName: "DeleteRepository",
			Handler:    _DeployerService_DeleteRepository_Handler,
		},
		{
			MethodName: "DatabaseTables",
			Handler:    _DeployerService_DatabaseTables_Handler,
		},
		{
			MethodName: "DatabaseTableData",
			Handler:    _DeployerService_DatabaseTableData_Handler,
		},
		{
			MethodName: "DatabaseQuery",
			Handler:    _DeployerService_DatabaseQuery_Handler,
		},
		{
			MethodName: "DatabaseStatus",
			Handler:    _DeployerService_DatabaseStatus_Handler,
		},
		{
			MethodName: "ServiceStatus",
			Handler:    _DeployerService_ServiceStatus_Handler,
		},
		{
			MethodName: "SetServiceScaling",
			Handler:    _DeployerService_SetServiceScaling_Handler,
		},
		{
			MethodName: "DatabaseCredentials",
			Handler:    _DeployerService_DatabaseCredentials_Handler,
		},
		{
			MethodName: "WorkspaceByInstallationID",
			Handler:    _DeployerService_WorkspaceByInstallationID_Handler,
		},
		{
			MethodName: "SetResourceQuota",
			Handler:    _DeployerService_SetResourceQuota_Handler,
		},
		{
			MethodName: "ResourceQuota",
			Handler:    _DeployerService_ResourceQuota_Handler,
		},
		{
			MethodName: "ListResourceAllocations",
			Handler:    _DeployerService_ListResourceAllocations_Handler,
		},
		{
			MethodName: "StoreUserGitHubToken",
			Handler:    _DeployerService_StoreUserGitHubToken_Handler,
		},
		{
			MethodName: "UserGitHubToken",
			Handler:    _DeployerService_UserGitHubToken_Handler,
		},
		{
			MethodName: "DeleteUserGitHubToken",
			Handler:    _DeployerService_DeleteUserGitHubToken_Handler,
		},
		{
			MethodName: "SuspendWorkspace",
			Handler:    _DeployerService_SuspendWorkspace_Handler,
		},
		{
			MethodName: "ProvisionCustomDomain",
			Handler:    _DeployerService_ProvisionCustomDomain_Handler,
		},
		{
			MethodName: "DeleteCustomDomain",
			Handler:    _DeployerService_DeleteCustomDomain_Handler,
		},
		{
			MethodName: "CustomDomainStatus",
			Handler:    _DeployerService_CustomDomainStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServiceLogs",
			Handler:       _DeployerService_ServiceLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "deployer.proto",
}
