// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: deployer.proto

package deployer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeployerService_DeployEnvironment_FullMethodName   = "/deployer.DeployerService/DeployEnvironment"
	DeployerService_RemoveDeployment_FullMethodName    = "/deployer.DeployerService/RemoveDeployment"
	DeployerService_GetDeploymentStatus_FullMethodName = "/deployer.DeployerService/GetDeploymentStatus"
	DeployerService_SyncDeployment_FullMethodName      = "/deployer.DeployerService/SyncDeployment"
)

// DeployerServiceClient is the client API for DeployerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeployerServiceClient interface {
	// DeployEnvironment creates a deployment for an environment.
	DeployEnvironment(ctx context.Context, in *DeployEnvironmentRequest, opts ...grpc.CallOption) (*DeployEnvironmentResponse, error)
	// RemoveDeployment removes the deployment for an environment.
	RemoveDeployment(ctx context.Context, in *RemoveDeploymentRequest, opts ...grpc.CallOption) (*RemoveDeploymentResponse, error)
	// GetDeploymentStatus returns the current deployment status of an environment.
	GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error)
	// SyncDeployment triggers a sync for an environment's deployment.
	SyncDeployment(ctx context.Context, in *SyncDeploymentRequest, opts ...grpc.CallOption) (*SyncDeploymentResponse, error)
}

type deployerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployerServiceClient(cc grpc.ClientConnInterface) DeployerServiceClient {
	return &deployerServiceClient{cc}
}

func (c *deployerServiceClient) DeployEnvironment(ctx context.Context, in *DeployEnvironmentRequest, opts ...grpc.CallOption) (*DeployEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployEnvironmentResponse)
	err := c.cc.Invoke(ctx, DeployerService_DeployEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) RemoveDeployment(ctx context.Context, in *RemoveDeploymentRequest, opts ...grpc.CallOption) (*RemoveDeploymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveDeploymentResponse)
	err := c.cc.Invoke(ctx, DeployerService_RemoveDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeploymentStatusResponse)
	err := c.cc.Invoke(ctx, DeployerService_GetDeploymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) SyncDeployment(ctx context.Context, in *SyncDeploymentRequest, opts ...grpc.CallOption) (*SyncDeploymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncDeploymentResponse)
	err := c.cc.Invoke(ctx, DeployerService_SyncDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployerServiceServer is the server API for DeployerService service.
// All implementations must embed UnimplementedDeployerServiceServer
// for forward compatibility.
type DeployerServiceServer interface {
	// DeployEnvironment creates a deployment for an environment.
	DeployEnvironment(context.Context, *DeployEnvironmentRequest) (*DeployEnvironmentResponse, error)
	// RemoveDeployment removes the deployment for an environment.
	RemoveDeployment(context.Context, *RemoveDeploymentRequest) (*RemoveDeploymentResponse, error)
	// GetDeploymentStatus returns the current deployment status of an environment.
	GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error)
	// SyncDeployment triggers a sync for an environment's deployment.
	SyncDeployment(context.Context, *SyncDeploymentRequest) (*SyncDeploymentResponse, error)
	mustEmbedUnimplementedDeployerServiceServer()
}

// UnimplementedDeployerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeployerServiceServer struct{}

func (UnimplementedDeployerServiceServer) DeployEnvironment(context.Context, *DeployEnvironmentRequest) (*DeployEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployEnvironment not implemented")
}
func (UnimplementedDeployerServiceServer) RemoveDeployment(context.Context, *RemoveDeploymentRequest) (*RemoveDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDeployment not implemented")
}
func (UnimplementedDeployerServiceServer) GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentStatus not implemented")
}
func (UnimplementedDeployerServiceServer) SyncDeployment(context.Context, *SyncDeploymentRequest) (*SyncDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncDeployment not implemented")
}
func (UnimplementedDeployerServiceServer) mustEmbedUnimplementedDeployerServiceServer() {}
func (UnimplementedDeployerServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeployerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeployerServiceServer will
// result in compilation errors.
type UnsafeDeployerServiceServer interface {
	mustEmbedUnimplementedDeployerServiceServer()
}

func RegisterDeployerServiceServer(s grpc.ServiceRegistrar, srv DeployerServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeployerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeployerService_ServiceDesc, srv)
}

func _DeployerService_DeployEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DeployEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_DeployEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DeployEnvironment(ctx, req.(*DeployEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_RemoveDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).RemoveDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_RemoveDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).RemoveDeployment(ctx, req.(*RemoveDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_GetDeploymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).GetDeploymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_GetDeploymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).GetDeploymentStatus(ctx, req.(*GetDeploymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_SyncDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).SyncDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_SyncDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).SyncDeployment(ctx, req.(*SyncDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeployerService_ServiceDesc is the grpc.ServiceDesc for DeployerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeployerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deployer.DeployerService",
	HandlerType: (*DeployerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployEnvironment",
			Handler:    _DeployerService_DeployEnvironment_Handler,
		},
		{
			MethodName: "RemoveDeployment",
			Handler:    _DeployerService_RemoveDeployment_Handler,
		},
		{
			MethodName: "GetDeploymentStatus",
			Handler:    _DeployerService_GetDeploymentStatus_Handler,
		},
		{
			MethodName: "SyncDeployment",
			Handler:    _DeployerService_SyncDeployment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deployer.proto",
}
