// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddServiceInput struct {
	ProjectID   string  `json:"projectId"`
	Name        string  `json:"name"`
	Port        int     `json:"port"`
	Framework   *string `json:"framework,omitempty"`
	SourceURL   *string `json:"sourceUrl,omitempty"`
	ContextPath *string `json:"contextPath,omitempty"`
}

type Build struct {
	ID       string     `json:"id"`
	Phase    BuildPhase `json:"phase"`
	ImageRef *string    `json:"imageRef,omitempty"`
	Digest   *string    `json:"digest,omitempty"`
	Error    *string    `json:"error,omitempty"`
}

type BuildServiceInput struct {
	ProjectID string  `json:"projectId"`
	Service   string  `json:"service"`
	GitRef    *string `json:"gitRef,omitempty"`
}

type CreateDatabaseInput struct {
	ProjectID string  `json:"projectId"`
	Name      string  `json:"name"`
	Version   *string `json:"version,omitempty"`
	Instances *int    `json:"instances,omitempty"`
	Size      *string `json:"size,omitempty"`
}

type CreateEnvironmentInput struct {
	ProjectID       string  `json:"projectId"`
	Name            string  `json:"name"`
	FromEnvironment *string `json:"fromEnvironment,omitempty"`
}

type CreateProjectInput struct {
	Name string `json:"name"`
}

type Database struct {
	Name      string `json:"name"`
	Version   string `json:"version"`
	Instances int    `json:"instances"`
	Size      string `json:"size"`
}

type DatabaseColumn struct {
	Name       string `json:"name"`
	Type       string `json:"type"`
	Nullable   bool   `json:"nullable"`
	PrimaryKey bool   `json:"primaryKey"`
}

type DatabaseInstance struct {
	Name        string  `json:"name"`
	Environment string  `json:"environment"`
	Ready       bool    `json:"ready"`
	Instances   int     `json:"instances"`
	Version     string  `json:"version"`
	Size        string  `json:"size"`
	Volume      *Volume `json:"volume,omitempty"`
}

type DatabaseQueryInput struct {
	ProjectID   string `json:"projectId"`
	Environment string `json:"environment"`
	Database    string `json:"database"`
	Query       string `json:"query"`
}

// A reference to a CNPG database secret key (resolved at pod startup via secretKeyRef).
type DatabaseRef struct {
	Database string `json:"database"`
	Key      string `json:"key"`
}

type DatabaseRefInput struct {
	Database string `json:"database"`
	Key      string `json:"key"`
}

type DatabaseTable struct {
	Name          string           `json:"name"`
	Schema        string           `json:"schema"`
	EstimatedRows int              `json:"estimatedRows"`
	Columns       []DatabaseColumn `json:"columns"`
}

type DatabaseTableData struct {
	Columns            []string    `json:"columns"`
	Rows               [][]*string `json:"rows"`
	TotalEstimatedRows int         `json:"totalEstimatedRows"`
}

type DeployBuildInput struct {
	ProjectID   string  `json:"projectId"`
	Service     string  `json:"service"`
	Environment string  `json:"environment"`
	Tag         string  `json:"tag"`
	Digest      *string `json:"digest,omitempty"`
}

type DeployInput struct {
	ProjectID   string  `json:"projectId"`
	Service     string  `json:"service"`
	Environment string  `json:"environment"`
	GitRef      *string `json:"gitRef,omitempty"`
}

type DeployRun struct {
	ID       string      `json:"id"`
	Phase    DeployPhase `json:"phase"`
	BuildID  *string     `json:"buildId,omitempty"`
	ImageRef *string     `json:"imageRef,omitempty"`
	Digest   *string     `json:"digest,omitempty"`
	Error    *string     `json:"error,omitempty"`
	// Rollout health status from the deployment system.
	RolloutHealth *SyncStatus `json:"rolloutHealth,omitempty"`
	// Rollout status detail, e.g. ImagePullBackOff, CrashLoopBackOff.
	RolloutMessage *string `json:"rolloutMessage,omitempty"`
}

type Deployment struct {
	ID        string     `json:"id"`
	ImageTag  string     `json:"imageTag"`
	Active    bool       `json:"active"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Revision  *string    `json:"revision,omitempty"`
	Message   *string    `json:"message,omitempty"`
	// First line of the source commit message (fetched from GitHub).
	SourceCommitMessage *string `json:"sourceCommitMessage,omitempty"`
	// URL to the source commit on GitHub.
	SourceURL *string `json:"sourceUrl,omitempty"`
}

type DetectedService struct {
	Name          string `json:"name"`
	Language      string `json:"language"`
	Framework     string `json:"framework"`
	StartCommand  string `json:"startCommand"`
	SuggestedPort int    `json:"suggestedPort"`
}

type Environment struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Namespace  string             `json:"namespace"`
	Ephemeral  bool               `json:"ephemeral"`
	SyncStatus SyncStatus         `json:"syncStatus"`
	Services   []ServiceInstance  `json:"services"`
	Databases  []DatabaseInstance `json:"databases"`
}

type GitHubRepository struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	FullName      string `json:"fullName"`
	HTMLURL       string `json:"htmlUrl"`
	DefaultBranch string `json:"defaultBranch"`
	Private       bool   `json:"private"`
}

type Mutation struct {
}

type Project struct {
	ID             string        `json:"id"`
	Name           string        `json:"name"`
	Environments   []Environment `json:"environments"`
	Services       []Service     `json:"services"`
	Databases      []Database    `json:"databases"`
	CreatedAt      time.Time     `json:"createdAt"`
	InitialDeploys []DeployRun   `json:"initialDeploys,omitempty"`
}

type PromoteInput struct {
	ProjectID       string `json:"projectId"`
	Service         string `json:"service"`
	FromEnvironment string `json:"fromEnvironment"`
	ToEnvironment   string `json:"toEnvironment"`
}

type Query struct {
}

type QueryResult struct {
	Columns      []string    `json:"columns"`
	Rows         [][]*string `json:"rows"`
	AffectedRows int         `json:"affectedRows"`
}

type RollbackInput struct {
	ProjectID   string `json:"projectId"`
	Service     string `json:"service"`
	Environment string `json:"environment"`
	// Image tag to roll back to (typically a short git SHA).
	ImageTag string `json:"imageTag"`
}

type Service struct {
	Name        string            `json:"name"`
	Image       string            `json:"image"`
	Port        *int              `json:"port,omitempty"`
	Framework   *string           `json:"framework,omitempty"`
	SourceURL   *string           `json:"sourceUrl,omitempty"`
	ContextPath *string           `json:"contextPath,omitempty"`
	Instances   []ServiceInstance `json:"instances"`
}

type ServiceInstance struct {
	Name        string       `json:"name"`
	Environment string       `json:"environment"`
	ImageTag    string       `json:"imageTag"`
	Ready       bool         `json:"ready"`
	Replicas    int          `json:"replicas"`
	Host        *string      `json:"host,omitempty"`
	Deployments []Deployment `json:"deployments"`
}

type ServiceLogEntry struct {
	// Log line text. Prefixed with [pod-suffix] when multiple replicas exist.
	Line string `json:"line"`
	// Name of the pod that produced this line.
	Pod string `json:"pod"`
}

// A reference to another service's internal URL (computed by Helm template).
type ServiceRef struct {
	Service string `json:"service"`
}

type ServiceRefInput struct {
	Service string `json:"service"`
}

type ServiceVariable struct {
	Key         string       `json:"key"`
	Value       string       `json:"value"`
	FromShared  bool         `json:"fromShared"`
	DatabaseRef *DatabaseRef `json:"databaseRef,omitempty"`
	ServiceRef  *ServiceRef  `json:"serviceRef,omitempty"`
}

type ServiceVariableInput struct {
	Key string `json:"key"`
	// Direct value. Required when no ref is set.
	Value *string `json:"value,omitempty"`
	// If true, value is resolved from the shared variable with the same key.
	FromShared *bool `json:"fromShared,omitempty"`
	// Reference to a database secret key.
	DatabaseRef *DatabaseRefInput `json:"databaseRef,omitempty"`
	// Reference to another service's internal URL.
	ServiceRef *ServiceRefInput `json:"serviceRef,omitempty"`
}

type SetServiceDomainInput struct {
	ProjectID   string `json:"projectId"`
	Service     string `json:"service"`
	Environment string `json:"environment"`
	// Domain hostname to set, or empty string to remove.
	Host string `json:"host"`
}

type Subscription struct {
}

type User struct {
	Login     string  `json:"login"`
	Name      *string `json:"name,omitempty"`
	Email     *string `json:"email,omitempty"`
	AvatarURL string  `json:"avatarUrl"`
}

type Variable struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type VariableInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Volume struct {
	Name          string `json:"name"`
	Size          string `json:"size"`
	RequestedSize string `json:"requestedSize"`
	UsedBytes     int    `json:"usedBytes"`
	CapacityBytes int    `json:"capacityBytes"`
}

type BuildPhase string

const (
	BuildPhaseQueued    BuildPhase = "QUEUED"
	BuildPhaseCloning   BuildPhase = "CLONING"
	BuildPhaseBuilding  BuildPhase = "BUILDING"
	BuildPhasePushing   BuildPhase = "PUSHING"
	BuildPhaseSucceeded BuildPhase = "SUCCEEDED"
	BuildPhaseFailed    BuildPhase = "FAILED"
)

var AllBuildPhase = []BuildPhase{
	BuildPhaseQueued,
	BuildPhaseCloning,
	BuildPhaseBuilding,
	BuildPhasePushing,
	BuildPhaseSucceeded,
	BuildPhaseFailed,
}

func (e BuildPhase) IsValid() bool {
	switch e {
	case BuildPhaseQueued, BuildPhaseCloning, BuildPhaseBuilding, BuildPhasePushing, BuildPhaseSucceeded, BuildPhaseFailed:
		return true
	}
	return false
}

func (e BuildPhase) String() string {
	return string(e)
}

func (e *BuildPhase) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BuildPhase(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BuildPhase", str)
	}
	return nil
}

func (e BuildPhase) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BuildPhase) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BuildPhase) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DeployPhase string

const (
	DeployPhaseQueued    DeployPhase = "QUEUED"
	DeployPhaseCloning   DeployPhase = "CLONING"
	DeployPhaseBuilding  DeployPhase = "BUILDING"
	DeployPhasePushing   DeployPhase = "PUSHING"
	DeployPhaseDeploying DeployPhase = "DEPLOYING"
	DeployPhaseSucceeded DeployPhase = "SUCCEEDED"
	DeployPhaseFailed    DeployPhase = "FAILED"
)

var AllDeployPhase = []DeployPhase{
	DeployPhaseQueued,
	DeployPhaseCloning,
	DeployPhaseBuilding,
	DeployPhasePushing,
	DeployPhaseDeploying,
	DeployPhaseSucceeded,
	DeployPhaseFailed,
}

func (e DeployPhase) IsValid() bool {
	switch e {
	case DeployPhaseQueued, DeployPhaseCloning, DeployPhaseBuilding, DeployPhasePushing, DeployPhaseDeploying, DeployPhaseSucceeded, DeployPhaseFailed:
		return true
	}
	return false
}

func (e DeployPhase) String() string {
	return string(e)
}

func (e *DeployPhase) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeployPhase(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeployPhase", str)
	}
	return nil
}

func (e DeployPhase) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DeployPhase) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DeployPhase) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleAnonymous Role = "ANONYMOUS"
	RoleUser      Role = "USER"
	RoleAdmin     Role = "ADMIN"
)

var AllRole = []Role{
	RoleAnonymous,
	RoleUser,
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAnonymous, RoleUser, RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SyncStatus string

const (
	SyncStatusSynced      SyncStatus = "SYNCED"
	SyncStatusOutOfSync   SyncStatus = "OUT_OF_SYNC"
	SyncStatusProgressing SyncStatus = "PROGRESSING"
	SyncStatusDegraded    SyncStatus = "DEGRADED"
	SyncStatusUnknown     SyncStatus = "UNKNOWN"
)

var AllSyncStatus = []SyncStatus{
	SyncStatusSynced,
	SyncStatusOutOfSync,
	SyncStatusProgressing,
	SyncStatusDegraded,
	SyncStatusUnknown,
}

func (e SyncStatus) IsValid() bool {
	switch e {
	case SyncStatusSynced, SyncStatusOutOfSync, SyncStatusProgressing, SyncStatusDegraded, SyncStatusUnknown:
		return true
	}
	return false
}

func (e SyncStatus) String() string {
	return string(e)
}

func (e *SyncStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SyncStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SyncStatus", str)
	}
	return nil
}

func (e SyncStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SyncStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SyncStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
