// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddCustomDomainInput struct {
	ProjectID   string `json:"projectId"`
	Service     string `json:"service"`
	Environment string `json:"environment"`
	Hostname    string `json:"hostname"`
}

type AddServiceInput struct {
	ProjectID string `json:"projectId"`
	// Service name. If omitted when image is set, derived from the image (e.g. nginx:1.25 → nginx).
	Name *string `json:"name,omitempty"`
	// Container port. If omitted when image is set, uses well-known defaults (e.g. redis → 6379).
	Port           *int    `json:"port,omitempty"`
	Framework      *string `json:"framework,omitempty"`
	SourceURL      *string `json:"sourceUrl,omitempty"`
	ContextPath    *string `json:"contextPath,omitempty"`
	InstallationID *string `json:"installationId,omitempty"`
	// External container image reference (e.g. nginx:1.25, ghcr.io/foo/bar:v1). Skips the build step.
	Image *string `json:"image,omitempty"`
	// Custom command to start the service (e.g. "npm run start", "stress --cpu 2 --timeout 60s"). Overrides the image entrypoint.
	CustomStartCommand *string `json:"customStartCommand,omitempty"`
}

type AutoscalingConfig struct {
	Enabled     bool `json:"enabled"`
	MinReplicas int  `json:"minReplicas"`
	MaxReplicas int  `json:"maxReplicas"`
	TargetCPU   int  `json:"targetCPU"`
}

type AutoscalingInput struct {
	Enabled     bool `json:"enabled"`
	MinReplicas int  `json:"minReplicas"`
	MaxReplicas int  `json:"maxReplicas"`
	TargetCPU   int  `json:"targetCPU"`
}

type BillingPortalURL struct {
	URL string `json:"url"`
}

type BillingSubscription struct {
	Plan              Plan               `json:"plan"`
	Status            SubscriptionStatus `json:"status"`
	CurrentPeriodEnd  time.Time          `json:"currentPeriodEnd"`
	CreditAmountCents int                `json:"creditAmountCents"`
	TrialEnd          *time.Time         `json:"trialEnd,omitempty"`
}

type CreateDatabaseInput struct {
	ProjectID string  `json:"projectId"`
	Name      string  `json:"name"`
	Version   *string `json:"version,omitempty"`
	Instances *int    `json:"instances,omitempty"`
	Size      *string `json:"size,omitempty"`
}

type CreateEnvironmentInput struct {
	ProjectID       string        `json:"projectId"`
	Name            string        `json:"name"`
	FromEnvironment *string       `json:"fromEnvironment,omitempty"`
	Tier            *ResourceTier `json:"tier,omitempty"`
}

type CreateProjectInput struct {
	Name string `json:"name"`
}

type CreateWorkspaceInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Database struct {
	Name      string `json:"name"`
	Version   string `json:"version"`
	Instances int    `json:"instances"`
	Size      string `json:"size"`
}

type DatabaseColumn struct {
	Name       string `json:"name"`
	Type       string `json:"type"`
	Nullable   bool   `json:"nullable"`
	PrimaryKey bool   `json:"primaryKey"`
}

type DatabaseCredentials struct {
	Host     string `json:"host"`
	Port     string `json:"port"`
	Dbname   string `json:"dbname"`
	User     string `json:"user"`
	Password string `json:"password"`
	URI      string `json:"uri"`
}

type DatabaseInstance struct {
	Name        string  `json:"name"`
	Environment string  `json:"environment"`
	Ready       bool    `json:"ready"`
	Instances   int     `json:"instances"`
	Version     string  `json:"version"`
	Size        string  `json:"size"`
	Volume      *Volume `json:"volume,omitempty"`
}

type DatabaseQueryInput struct {
	ProjectID   string `json:"projectId"`
	Environment string `json:"environment"`
	Database    string `json:"database"`
	Query       string `json:"query"`
}

// A reference to a CNPG database secret key (resolved at pod startup via secretKeyRef).
type DatabaseRef struct {
	Database string `json:"database"`
	Key      string `json:"key"`
}

type DatabaseRefInput struct {
	Database string `json:"database"`
	Key      string `json:"key"`
}

type DatabaseTable struct {
	Name          string           `json:"name"`
	Schema        string           `json:"schema"`
	EstimatedRows int              `json:"estimatedRows"`
	Columns       []DatabaseColumn `json:"columns"`
}

type DatabaseTableData struct {
	Columns            []string    `json:"columns"`
	Rows               [][]*string `json:"rows"`
	TotalEstimatedRows int         `json:"totalEstimatedRows"`
}

type DeployInput struct {
	ProjectID   string  `json:"projectId"`
	Service     string  `json:"service"`
	Environment string  `json:"environment"`
	GitRef      *string `json:"gitRef,omitempty"`
}

type DeployRun struct {
	ID       string      `json:"id"`
	Phase    DeployPhase `json:"phase"`
	BuildID  *string     `json:"buildId,omitempty"`
	ImageRef *string     `json:"imageRef,omitempty"`
	Digest   *string     `json:"digest,omitempty"`
	Error    *string     `json:"error,omitempty"`
	// When the deploy operation started.
	StartedAt *time.Time `json:"startedAt,omitempty"`
	// Rollout health status from the deployment system.
	RolloutHealth *SyncStatus `json:"rolloutHealth,omitempty"`
	// Rollout status detail, e.g. ImagePullBackOff, CrashLoopBackOff.
	RolloutMessage *string `json:"rolloutMessage,omitempty"`
}

type Deployment struct {
	ID        string     `json:"id"`
	ImageTag  string     `json:"imageTag"`
	Active    bool       `json:"active"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Revision  *string    `json:"revision,omitempty"`
	Message   *string    `json:"message,omitempty"`
	// First line of the source commit message (fetched from GitHub).
	SourceCommitMessage *string `json:"sourceCommitMessage,omitempty"`
	// URL to the source commit on GitHub.
	SourceURL *string `json:"sourceUrl,omitempty"`
}

type DetectedService struct {
	Name          string `json:"name"`
	Language      string `json:"language"`
	Framework     string `json:"framework"`
	StartCommand  string `json:"startCommand"`
	SuggestedPort int    `json:"suggestedPort"`
}

// Result of a live DNS verification for a custom domain.
type DNSCheck struct {
	Hostname string `json:"hostname"`
	// Current DNS status after live lookup.
	Status DNSStatus `json:"status"`
	// The CNAME target found in DNS, if any.
	CnameTarget *string `json:"cnameTarget,omitempty"`
	// The expected CNAME target for this platform.
	ExpectedTarget string `json:"expectedTarget"`
	// Human-readable message explaining the current status.
	Message *string `json:"message,omitempty"`
}

type Domain struct {
	Hostname string `json:"hostname"`
	// PLATFORM domains use wildcard DNS on the workload domain. CUSTOM domains require user DNS config.
	Type DomainType `json:"type"`
	// DNS resolution status. Always VALID for platform domains. Checked via DNS lookup for custom domains.
	DNSStatus DNSStatus `json:"dnsStatus"`
}

type Environment struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Namespace    string             `json:"namespace"`
	Ephemeral    bool               `json:"ephemeral"`
	SyncStatus   SyncStatus         `json:"syncStatus"`
	ResourceTier *ResourceTier      `json:"resourceTier,omitempty"`
	Services     []ServiceInstance  `json:"services"`
	Databases    []DatabaseInstance `json:"databases"`
}

type EnvironmentResources struct {
	Tier       ResourceTier        `json:"tier"`
	Allocation *ResourceAllocation `json:"allocation"`
}

type GenerateDomainInput struct {
	ProjectID   string `json:"projectId"`
	Service     string `json:"service"`
	Environment string `json:"environment"`
}

type GitHubInstallation struct {
	ID               string            `json:"id"`
	AccountLogin     string            `json:"accountLogin"`
	AccountAvatarURL string            `json:"accountAvatarUrl"`
	AccountType      GitHubAccountType `json:"accountType"`
}

type GitHubRepository struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	FullName      string `json:"fullName"`
	HTMLURL       string `json:"htmlUrl"`
	DefaultBranch string `json:"defaultBranch"`
	Private       bool   `json:"private"`
}

// A container image from a public registry (Docker Hub).
type ImageSearchResult struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	StarCount   int    `json:"starCount"`
	PullCount   int    `json:"pullCount"`
	Official    bool   `json:"official"`
}

type InviteMemberInput struct {
	Email string        `json:"email"`
	Role  WorkspaceRole `json:"role"`
}

type Mutation struct {
}

type PlatformConfig struct {
	WorkloadDomain string `json:"workloadDomain"`
	// CNAME target for custom domains. Empty if not configured.
	DomainTarget string `json:"domainTarget"`
}

type Project struct {
	ID             string        `json:"id"`
	Name           string        `json:"name"`
	Environments   []Environment `json:"environments"`
	Services       []Service     `json:"services"`
	Databases      []Database    `json:"databases"`
	CreatedAt      time.Time     `json:"createdAt"`
	InitialDeploys []DeployRun   `json:"initialDeploys,omitempty"`
}

type PromoteInput struct {
	ProjectID       string        `json:"projectId"`
	Service         string        `json:"service"`
	FromEnvironment string        `json:"fromEnvironment"`
	Tier            *ResourceTier `json:"tier,omitempty"`
	ToEnvironment   string        `json:"toEnvironment"`
}

type Query struct {
}

type QueryResult struct {
	Columns      []string    `json:"columns"`
	Rows         [][]*string `json:"rows"`
	AffectedRows int         `json:"affectedRows"`
}

type RemoveDomainInput struct {
	ProjectID   string `json:"projectId"`
	Service     string `json:"service"`
	Environment string `json:"environment"`
	Hostname    string `json:"hostname"`
}

type ResourceAllocation struct {
	CPUMillicores int `json:"cpuMillicores"`
	MemoryMb      int `json:"memoryMB"`
	DiskMb        int `json:"diskMB"`
}

type RollbackInput struct {
	ProjectID   string `json:"projectId"`
	Service     string `json:"service"`
	Environment string `json:"environment"`
	// Image tag to roll back to (typically a short git SHA).
	ImageTag string `json:"imageTag"`
}

type ScalingConfig struct {
	Replicas    int                `json:"replicas"`
	Autoscaling *AutoscalingConfig `json:"autoscaling,omitempty"`
}

type Service struct {
	Name               string            `json:"name"`
	Image              string            `json:"image"`
	Port               *int              `json:"port,omitempty"`
	Framework          *string           `json:"framework,omitempty"`
	SourceURL          *string           `json:"sourceUrl,omitempty"`
	ContextPath        *string           `json:"contextPath,omitempty"`
	CustomStartCommand *string           `json:"customStartCommand,omitempty"`
	Instances          []ServiceInstance `json:"instances"`
	// Deploy automatically triggered when the service was added. Null for image-based services.
	InitialDeploy *DeployRun `json:"initialDeploy,omitempty"`
}

type ServiceInstance struct {
	Name        string         `json:"name"`
	Environment string         `json:"environment"`
	ImageTag    string         `json:"imageTag"`
	Ready       bool           `json:"ready"`
	Replicas    int            `json:"replicas"`
	Scaling     *ScalingConfig `json:"scaling"`
	Domains     []Domain       `json:"domains"`
	Deployments []Deployment   `json:"deployments"`
}

type ServiceLogEntry struct {
	// Log line text. Prefixed with [pod-suffix] when multiple replicas exist.
	Line string `json:"line"`
	// Name of the pod that produced this line.
	Pod string `json:"pod"`
}

// A reference to another service's internal URL (computed by Helm template).
type ServiceRef struct {
	Service string `json:"service"`
}

type ServiceRefInput struct {
	Service string `json:"service"`
}

type ServiceVariable struct {
	Key         string       `json:"key"`
	Value       string       `json:"value"`
	FromShared  bool         `json:"fromShared"`
	DatabaseRef *DatabaseRef `json:"databaseRef,omitempty"`
	ServiceRef  *ServiceRef  `json:"serviceRef,omitempty"`
}

type ServiceVariableInput struct {
	Key string `json:"key"`
	// Direct value. Required when no ref is set.
	Value *string `json:"value,omitempty"`
	// If true, value is resolved from the shared variable with the same key.
	FromShared *bool `json:"fromShared,omitempty"`
	// Reference to a database secret key.
	DatabaseRef *DatabaseRefInput `json:"databaseRef,omitempty"`
	// Reference to another service's internal URL.
	ServiceRef *ServiceRefInput `json:"serviceRef,omitempty"`
}

type SetEnvironmentResourcesInput struct {
	ProjectID     string       `json:"projectId"`
	Environment   string       `json:"environment"`
	Tier          ResourceTier `json:"tier"`
	CPUMillicores int          `json:"cpuMillicores"`
	MemoryMb      int          `json:"memoryMB"`
	DiskMb        int          `json:"diskMB"`
}

type SetServiceScalingInput struct {
	ProjectID   string            `json:"projectId"`
	Environment string            `json:"environment"`
	Service     string            `json:"service"`
	Replicas    int               `json:"replicas"`
	Autoscaling *AutoscalingInput `json:"autoscaling,omitempty"`
}

type Subscription struct {
}

type UpdateMemberRoleInput struct {
	UserID string        `json:"userId"`
	Role   WorkspaceRole `json:"role"`
}

type UpdateWorkspaceInput struct {
	Name string `json:"name"`
}

type UsageSummary struct {
	ResourceCostCents   int `json:"resourceCostCents"`
	CreditsCents        int `json:"creditsCents"`
	EstimatedTotalCents int `json:"estimatedTotalCents"`
}

type User struct {
	Name       *string               `json:"name,omitempty"`
	Email      *string               `json:"email,omitempty"`
	AvatarURL  string                `json:"avatarUrl"`
	Workspaces []WorkspaceMembership `json:"workspaces"`
}

type Variable struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type VariableInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Volume struct {
	Name          string `json:"name"`
	Size          string `json:"size"`
	RequestedSize string `json:"requestedSize"`
	UsedBytes     int    `json:"usedBytes"`
	CapacityBytes int    `json:"capacityBytes"`
}

type Workspace struct {
	ID        string            `json:"id"`
	Name      string            `json:"name"`
	Personal  bool              `json:"personal"`
	Suspended bool              `json:"suspended"`
	Members   []WorkspaceMember `json:"members"`
}

type WorkspaceMember struct {
	ID    string        `json:"id"`
	Email string        `json:"email"`
	Name  *string       `json:"name,omitempty"`
	Role  WorkspaceRole `json:"role"`
}

type WorkspaceMembership struct {
	Workspace string        `json:"workspace"`
	Role      WorkspaceRole `json:"role"`
}

type DeployPhase string

const (
	DeployPhaseQueued    DeployPhase = "QUEUED"
	DeployPhaseCloning   DeployPhase = "CLONING"
	DeployPhaseBuilding  DeployPhase = "BUILDING"
	DeployPhasePushing   DeployPhase = "PUSHING"
	DeployPhaseDeploying DeployPhase = "DEPLOYING"
	DeployPhaseSucceeded DeployPhase = "SUCCEEDED"
	DeployPhaseFailed    DeployPhase = "FAILED"
)

var AllDeployPhase = []DeployPhase{
	DeployPhaseQueued,
	DeployPhaseCloning,
	DeployPhaseBuilding,
	DeployPhasePushing,
	DeployPhaseDeploying,
	DeployPhaseSucceeded,
	DeployPhaseFailed,
}

func (e DeployPhase) IsValid() bool {
	switch e {
	case DeployPhaseQueued, DeployPhaseCloning, DeployPhaseBuilding, DeployPhasePushing, DeployPhaseDeploying, DeployPhaseSucceeded, DeployPhaseFailed:
		return true
	}
	return false
}

func (e DeployPhase) String() string {
	return string(e)
}

func (e *DeployPhase) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeployPhase(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeployPhase", str)
	}
	return nil
}

func (e DeployPhase) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DeployPhase) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DeployPhase) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DNSStatus string

const (
	DNSStatusValid         DNSStatus = "VALID"
	DNSStatusPending       DNSStatus = "PENDING"
	DNSStatusMisconfigured DNSStatus = "MISCONFIGURED"
	DNSStatusError         DNSStatus = "ERROR"
)

var AllDNSStatus = []DNSStatus{
	DNSStatusValid,
	DNSStatusPending,
	DNSStatusMisconfigured,
	DNSStatusError,
}

func (e DNSStatus) IsValid() bool {
	switch e {
	case DNSStatusValid, DNSStatusPending, DNSStatusMisconfigured, DNSStatusError:
		return true
	}
	return false
}

func (e DNSStatus) String() string {
	return string(e)
}

func (e *DNSStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DNSStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DnsStatus", str)
	}
	return nil
}

func (e DNSStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DNSStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DNSStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DomainType string

const (
	DomainTypePlatform DomainType = "PLATFORM"
	DomainTypeCustom   DomainType = "CUSTOM"
)

var AllDomainType = []DomainType{
	DomainTypePlatform,
	DomainTypeCustom,
}

func (e DomainType) IsValid() bool {
	switch e {
	case DomainTypePlatform, DomainTypeCustom:
		return true
	}
	return false
}

func (e DomainType) String() string {
	return string(e)
}

func (e *DomainType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DomainType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DomainType", str)
	}
	return nil
}

func (e DomainType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DomainType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DomainType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GitHubAccountType string

const (
	GitHubAccountTypeOrganization GitHubAccountType = "ORGANIZATION"
	GitHubAccountTypeUser         GitHubAccountType = "USER"
)

var AllGitHubAccountType = []GitHubAccountType{
	GitHubAccountTypeOrganization,
	GitHubAccountTypeUser,
}

func (e GitHubAccountType) IsValid() bool {
	switch e {
	case GitHubAccountTypeOrganization, GitHubAccountTypeUser:
		return true
	}
	return false
}

func (e GitHubAccountType) String() string {
	return string(e)
}

func (e *GitHubAccountType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GitHubAccountType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GitHubAccountType", str)
	}
	return nil
}

func (e GitHubAccountType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GitHubAccountType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GitHubAccountType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Plan string

const (
	PlanHobby Plan = "HOBBY"
	PlanPro   Plan = "PRO"
)

var AllPlan = []Plan{
	PlanHobby,
	PlanPro,
}

func (e Plan) IsValid() bool {
	switch e {
	case PlanHobby, PlanPro:
		return true
	}
	return false
}

func (e Plan) String() string {
	return string(e)
}

func (e *Plan) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Plan(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Plan", str)
	}
	return nil
}

func (e Plan) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Plan) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Plan) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ResourceTier string

const (
	ResourceTierEco        ResourceTier = "ECO"
	ResourceTierProduction ResourceTier = "PRODUCTION"
)

var AllResourceTier = []ResourceTier{
	ResourceTierEco,
	ResourceTierProduction,
}

func (e ResourceTier) IsValid() bool {
	switch e {
	case ResourceTierEco, ResourceTierProduction:
		return true
	}
	return false
}

func (e ResourceTier) String() string {
	return string(e)
}

func (e *ResourceTier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ResourceTier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ResourceTier", str)
	}
	return nil
}

func (e ResourceTier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ResourceTier) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ResourceTier) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleAnonymous Role = "ANONYMOUS"
	RoleUser      Role = "USER"
	RoleAdmin     Role = "ADMIN"
)

var AllRole = []Role{
	RoleAnonymous,
	RoleUser,
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAnonymous, RoleUser, RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusActive     SubscriptionStatus = "ACTIVE"
	SubscriptionStatusPastDue    SubscriptionStatus = "PAST_DUE"
	SubscriptionStatusCanceled   SubscriptionStatus = "CANCELED"
	SubscriptionStatusIncomplete SubscriptionStatus = "INCOMPLETE"
	SubscriptionStatusTrialing   SubscriptionStatus = "TRIALING"
)

var AllSubscriptionStatus = []SubscriptionStatus{
	SubscriptionStatusActive,
	SubscriptionStatusPastDue,
	SubscriptionStatusCanceled,
	SubscriptionStatusIncomplete,
	SubscriptionStatusTrialing,
}

func (e SubscriptionStatus) IsValid() bool {
	switch e {
	case SubscriptionStatusActive, SubscriptionStatusPastDue, SubscriptionStatusCanceled, SubscriptionStatusIncomplete, SubscriptionStatusTrialing:
		return true
	}
	return false
}

func (e SubscriptionStatus) String() string {
	return string(e)
}

func (e *SubscriptionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SubscriptionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SubscriptionStatus", str)
	}
	return nil
}

func (e SubscriptionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SubscriptionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SubscriptionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SyncStatus string

const (
	SyncStatusSynced      SyncStatus = "SYNCED"
	SyncStatusOutOfSync   SyncStatus = "OUT_OF_SYNC"
	SyncStatusProgressing SyncStatus = "PROGRESSING"
	SyncStatusDegraded    SyncStatus = "DEGRADED"
	SyncStatusUnknown     SyncStatus = "UNKNOWN"
)

var AllSyncStatus = []SyncStatus{
	SyncStatusSynced,
	SyncStatusOutOfSync,
	SyncStatusProgressing,
	SyncStatusDegraded,
	SyncStatusUnknown,
}

func (e SyncStatus) IsValid() bool {
	switch e {
	case SyncStatusSynced, SyncStatusOutOfSync, SyncStatusProgressing, SyncStatusDegraded, SyncStatusUnknown:
		return true
	}
	return false
}

func (e SyncStatus) String() string {
	return string(e)
}

func (e *SyncStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SyncStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SyncStatus", str)
	}
	return nil
}

func (e SyncStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SyncStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SyncStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkspaceRole string

const (
	WorkspaceRoleUser  WorkspaceRole = "USER"
	WorkspaceRoleAdmin WorkspaceRole = "ADMIN"
)

var AllWorkspaceRole = []WorkspaceRole{
	WorkspaceRoleUser,
	WorkspaceRoleAdmin,
}

func (e WorkspaceRole) IsValid() bool {
	switch e {
	case WorkspaceRoleUser, WorkspaceRoleAdmin:
		return true
	}
	return false
}

func (e WorkspaceRole) String() string {
	return string(e)
}

func (e *WorkspaceRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkspaceRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkspaceRole", str)
	}
	return nil
}

func (e WorkspaceRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkspaceRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkspaceRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
