// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type CreateEnvironmentInput struct {
	ProjectID       string  `json:"projectId"`
	Name            string  `json:"name"`
	FromEnvironment *string `json:"fromEnvironment,omitempty"`
}

type CreateProjectInput struct {
	Name      string `json:"name"`
	SourceURL string `json:"sourceUrl"`
}

type DeployedService struct {
	Name     string `json:"name"`
	ImageTag string `json:"imageTag"`
	Ready    bool   `json:"ready"`
	Replicas int    `json:"replicas"`
}

type Environment struct {
	ID         string            `json:"id"`
	Name       string            `json:"name"`
	Namespace  string            `json:"namespace"`
	Ephemeral  bool              `json:"ephemeral"`
	SyncStatus SyncStatus        `json:"syncStatus"`
	Services   []DeployedService `json:"services"`
}

type GitHubRepository struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	FullName      string `json:"fullName"`
	HTMLURL       string `json:"htmlUrl"`
	DefaultBranch string `json:"defaultBranch"`
	Private       bool   `json:"private"`
}

type Mutation struct {
}

type Project struct {
	ID           string        `json:"id"`
	Name         string        `json:"name"`
	SourceURL    string        `json:"sourceUrl"`
	Environments []Environment `json:"environments"`
	Services     []Service     `json:"services"`
	CreatedAt    time.Time     `json:"createdAt"`
}

type PromoteInput struct {
	ProjectID       string `json:"projectId"`
	Service         string `json:"service"`
	FromEnvironment string `json:"fromEnvironment"`
	ToEnvironment   string `json:"toEnvironment"`
}

type Query struct {
}

type Service struct {
	Name   string `json:"name"`
	Image  string `json:"image"`
	Port   *int   `json:"port,omitempty"`
	Public bool   `json:"public"`
}

type User struct {
	Login     string  `json:"login"`
	Name      *string `json:"name,omitempty"`
	Email     *string `json:"email,omitempty"`
	AvatarURL string  `json:"avatarUrl"`
}

type Role string

const (
	RoleAnonymous Role = "ANONYMOUS"
	RoleUser      Role = "USER"
	RoleAdmin     Role = "ADMIN"
)

var AllRole = []Role{
	RoleAnonymous,
	RoleUser,
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAnonymous, RoleUser, RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SyncStatus string

const (
	SyncStatusSynced      SyncStatus = "SYNCED"
	SyncStatusOutOfSync   SyncStatus = "OUT_OF_SYNC"
	SyncStatusProgressing SyncStatus = "PROGRESSING"
	SyncStatusDegraded    SyncStatus = "DEGRADED"
	SyncStatusUnknown     SyncStatus = "UNKNOWN"
)

var AllSyncStatus = []SyncStatus{
	SyncStatusSynced,
	SyncStatusOutOfSync,
	SyncStatusProgressing,
	SyncStatusDegraded,
	SyncStatusUnknown,
}

func (e SyncStatus) IsValid() bool {
	switch e {
	case SyncStatusSynced, SyncStatusOutOfSync, SyncStatusProgressing, SyncStatusDegraded, SyncStatusUnknown:
		return true
	}
	return false
}

func (e SyncStatus) String() string {
	return string(e)
}

func (e *SyncStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SyncStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SyncStatus", str)
	}
	return nil
}

func (e SyncStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SyncStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SyncStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
