type Database {
  id: DatabaseID!
  name: String!
  version: String!
  instances: Int!
  size: String!
}

type DatabaseInstance {
  name: String!
  ready: Boolean!
  instances: Int!
  version: String!
  size: String!
  volume: Volume
}

type Volume {
  id: VolumeID!
  name: String!
  size: String!
  requestedSize: String!
  usedBytes: Int!
  capacityBytes: Int!
}

type DatabaseTable {
  name: String!
  schema: String!
  estimatedRows: Int!
  columns: [DatabaseColumn!]!
}

type DatabaseColumn {
  name: String!
  type: String!
  nullable: Boolean!
  primaryKey: Boolean!
}

type DatabaseTableData {
  columns: [String!]!
  rows: [[String]]!
  totalEstimatedRows: Int!
}

type QueryResult {
  columns: [String!]!
  rows: [[String]]!
  affectedRows: Int!
}

type DatabaseCredentials {
  host: String!
  port: String!
  dbname: String!
  user: String!
  password: String!
  uri: String!
}

input CreateDatabaseInput {
  environment: EnvironmentID!
  name: String! @constraint(constraint: "resource_name,min=2,max=63")
  version: String
  instances: Int
  size: String
}

extend type Query {
  databaseTables(database: DatabaseID!): [DatabaseTable!]! @hasRole(role: [USER])
  databaseTableData(
    database: DatabaseID!
    table: String!
    schema: String
    limit: Int
    offset: Int
  ): DatabaseTableData! @hasRole(role: [USER])
  databaseCredentials(database: DatabaseID!): DatabaseCredentials! @hasRole(role: [USER])
}

extend type Mutation {
  createDatabase(input: CreateDatabaseInput!): Database! @hasRole(role: [USER])
  deleteDatabase(database: DatabaseID!): Boolean! @hasRole(role: [USER])
  executeQuery(database: DatabaseID!, query: String!): QueryResult! @hasRole(role: [USER])
}
