type Deployment {
  id: DeploymentID!

  image: String!
  imageDigest: String

  commit: String!
  commitMessage: String!
  ref: String!
  sourceUrl: String!
  contextPath: String!

  resources: Resources!
  command: String!

  buildId: String!

  status: DeploymentStatus!
  replicas: ReplicaCount!

  createdAt: Time!
}

enum DeploymentStatus {
  DEPLOYING
  ACTIVE
  SUPERSEDED
  FAILED
}

extend type Query {
  deployment(id: DeploymentID!): Deployment! @hasRole(role: WORKSPACE_MEMBER)
}

extend type Mutation {
  deploy(service: ServiceID!, gitRef: String): Release! @hasRole(role: WORKSPACE_MEMBER)
}