type Environment {
  id: EnvironmentID!
  name: String!
  resourceTier: ResourceTier
  services: [ServiceInstance!]! @goField(forceResolver: true)
  databases: [DatabaseInstance!]! @goField(forceResolver: true)
}

input CreateEnvironmentInput {
  project: ProjectID!
  name: String! @constraint(constraint: "resource_name,min=2,max=63")
  fromEnvironment: EnvironmentID
  tier: ResourceTier
}

input PromoteInput {
  service: ServiceID!
  tier: ResourceTier
  toEnvironment: EnvironmentID!
}

extend type Mutation {
  createEnvironment(input: CreateEnvironmentInput!): Environment! @hasRole(role: [USER])
  deleteEnvironment(environment: EnvironmentID!): Boolean! @hasRole(role: [USER])
  promote(input: PromoteInput!): ServiceInstance! @hasRole(role: [USER])
}
