type Service
@goExtraField(name: "PlatformService", type: "github.com/zeitlos/lucity/services/conductor/internal/platform.Service"){
  id: ServiceID!
  name: String!

  status: ServiceStatus!
  replicas: ReplicaCount!
  autoscaling: AutoscalingSettings

  port: Int!
  endpoints: [Endpoint!]! @goField(forceResolver: true)

  sourceUrl: String!
  branch: String
  autoDeploy: Boolean!
  ciDeploy: Boolean!
  contextPath: String!
  resources: Resources!
  command: String!
  defaultCommand: String! @goField(forceResolver: true)

  activeDeployment: Deployment
  deployments: [Deployment!]! @goField(forceResolver: true)

  builds: [Build!]! @goField(forceResolver: true)

  metrics(metrics: [ResourceMetric!]!, range: MetricsRange!, grouping: MetricGrouping! = TOTAL): [MetricSeries!]! @goField(forceResolver: true)

  lastDeployedAt: Time
  createdAt: Time!
}

type ReplicaCount {
  desired: Int!
  ready: Int!
}

type AutoscalingSettings {
  minReplicas: Int!
  maxReplicas: Int!
  targetCpu: Int!
}

type Resources {
  cpu: String!
  memory: String!
}

type Endpoint {
  host: String!
  port: Int!
  protocol: Protocol!
  type: EndpointType!
  dns: DnsState!
  tls: TlsStatus!
}

type DnsState {
  status: DnsStatus!
  requiredRecords: [DnsRecord!]!
}

enum EndpointType {
  PLATFORM
  CUSTOM
  INTERNAL
}

enum Protocol {
  HTTP
  HTTPS
  TCP
}

enum ServiceStatus {
  HEALTHY
  DEGRADED
  DEPLOYING
  FAILED
  STOPPED
  BUILDING
}

type DnsRecord {
  type: DnsRecordType!
  host: String!
  value: String!
}

enum DnsRecordType {
  TXT
  CNAME
  A
}

enum TlsStatus {
  NONE
  PROVISIONING
  ACTIVE
  ERROR
}

enum DnsStatus {
  VALID
  PENDING
  MISCONFIGURED
  ERROR
}

type DetectedService {
  name: String!
  language: String!
  framework: String!
  contextPath: String!
  startCommand: String!
  suggestedPort: Int!
}

input AddServiceInput {
  name: String @constraint(constraint: "resource_name,min=2,max=16")
  repository: String @constraint(constraint: "min=3,max=200")
  contextPath: String
  image: String
  variables: [VariableInput!]
}

input SetServiceScalingInput {
  service: ServiceID!
  replicas: Int! @constraint(constraint: "min=1,max=20")
  autoscaling: AutoscalingInput
}

input ResourcesInput {
  cpu: String!
  memory: String!
}

input AutoscalingInput {
  enabled: Boolean!
  minReplicas: Int! @constraint(constraint: "min=1,max=20")
  maxReplicas: Int! @constraint(constraint: "min=1,max=20")
  targetCPU: Int! @constraint(constraint: "min=10,max=95")
}

extend type Query {
  service(id: ServiceID!): Service! @hasRole(role: WORKSPACE_DEPLOYER)
  detectServices(repositoryUrl: String!): [DetectedService!]! @hasRole(role: WORKSPACE_MEMBER)
  repositoryBranches(repositoryUrl: String!): [String!]! @hasRole(role: WORKSPACE_MEMBER)
}

extend type Mutation {
  addService(environment: EnvironmentID!, input: AddServiceInput!): Service! @hasRole(role: WORKSPACE_MEMBER)
  removeService(service: ServiceID!): Boolean! @hasRole(role: WORKSPACE_MEMBER)
  setCustomStartCommand(service: ServiceID!, command: String!): Service! @hasRole(role: WORKSPACE_MEMBER)
  setServiceBranch(service: ServiceID!, branch: String @constraint(constraint: "min=1,max=250")): Service! @hasRole(role: WORKSPACE_MEMBER)
  setAutoDeploy(service: ServiceID!, enabled: Boolean!): Service! @hasRole(role: WORKSPACE_MEMBER)
  setCIDeploy(service: ServiceID!, enabled: Boolean!): Service! @hasRole(role: WORKSPACE_MEMBER)
  setServicePort(service: ServiceID!, port: Int @constraint(constraint: "min=1,max=65535")): Service! @hasRole(role: WORKSPACE_MEMBER)
  setServiceScaling(input: SetServiceScalingInput!): Service! @hasRole(role: WORKSPACE_MEMBER)
  setServiceResources(service: ServiceID!, resources: ResourcesInput!): Service! @hasRole(role: WORKSPACE_MEMBER)
  rollback(deployment: DeploymentID!): Boolean! @hasRole(role: WORKSPACE_MEMBER)
  generateDomain(service: ServiceID!): Service! @hasRole(role: WORKSPACE_MEMBER)
  addCustomDomain(service: ServiceID!, hostname: String! @constraint(constraint: "min=4,max=253")): Service! @hasRole(role: WORKSPACE_MEMBER)
  removeDomain(service: ServiceID!, hostname: String!): Service! @hasRole(role: WORKSPACE_MEMBER)
}
