type Mount {
  service: ServiceID!
  path: String!
}

type Volume {
  id: VolumeID!
  name: String!
  size: String!
  mount: Mount
  metrics(metrics: [ResourceMetric!]!, range: MetricsRange!): [MetricSeries!]! @goField(forceResolver: true)
}

extend type Query {
  volume(id: VolumeID!): Volume! @hasRole(role: WORKSPACE_MEMBER)
}

extend type Mutation {
  createVolume(environment: EnvironmentID!, name: String! @constraint(constraint: "resource_name,min=2,max=16"), size: String!): Volume! @hasRole(role: WORKSPACE_MEMBER)
  expandVolume(volume: VolumeID!, size: String!): Volume! @hasRole(role: WORKSPACE_MEMBER)
  mountVolume(volume: VolumeID!, service: ServiceID!, path: String!): Volume! @hasRole(role: WORKSPACE_MEMBER)
  unmountVolume(volume: VolumeID!): Volume! @hasRole(role: WORKSPACE_MEMBER)
  deleteVolume(volume: VolumeID!): Boolean! @hasRole(role: WORKSPACE_MEMBER)
}
