type Workspace {
  id: ID!
  name: String!
  personal: Boolean!
  suspended: Boolean!
  members: [WorkspaceMember!]!
}

type WorkspaceMember {
  id: ID!
  email: String!
  name: String
  role: WorkspaceRole!
}

input UpdateWorkspaceInput {
  name: String!
}

input InviteMemberInput {
  email: String!
  role: WorkspaceRole!
}

input UpdateMemberRoleInput {
  userId: ID!
  role: WorkspaceRole!
}

extend type Query {
  workspace: Workspace! @hasRole(role: [USER])
  workspaces: [Workspace!]! @hasRole(role: [USER])
}

input CreateWorkspaceCheckoutInput {
  id: String!
  name: String!
  plan: Plan!
}

type CheckoutSession {
  url: String!
}

extend type Mutation {
  createWorkspaceCheckout(input: CreateWorkspaceCheckoutInput!): CheckoutSession! @hasRole(role: [USER])
  completeWorkspaceCheckout(sessionId: String!): Workspace! @hasRole(role: [USER])
  updateWorkspace(input: UpdateWorkspaceInput!): Workspace! @allowSuspended @hasRole(role: [ADMIN])
  deleteWorkspace: Boolean! @allowSuspended @hasRole(role: [ADMIN])
  inviteMember(input: InviteMemberInput!): WorkspaceMember! @hasRole(role: [ADMIN])
  removeMember(userId: ID!): Boolean! @hasRole(role: [ADMIN])
  updateMemberRole(input: UpdateMemberRoleInput!): WorkspaceMember! @hasRole(role: [ADMIN])
}
