package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
)

// CreateAPIToken is the resolver for the createApiToken field.
func (r *mutationResolver) CreateAPIToken(ctx context.Context, input model.CreateAPITokenInput) (*model.CreatedAPIToken, error) {
	created, err := r.Conductor.CreateAPIToken(ctx, input.Name, convertModelWorkspaceRole(input.Role))
	if err != nil {
		return nil, err
	}
	return convertCreatedAPIToken(created), nil
}

// RevokeAPIToken is the resolver for the revokeApiToken field.
func (r *mutationResolver) RevokeAPIToken(ctx context.Context, id string) (bool, error) {
	if err := r.Conductor.RevokeAPIToken(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// APITokens is the resolver for the apiTokens field.
func (r *queryResolver) APITokens(ctx context.Context) ([]model.APIToken, error) {
	tokens, err := r.Conductor.APITokens(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.APIToken, 0, len(tokens))
	for i := range tokens {
		out = append(out, *convertAPIToken(&tokens[i]))
	}
	return out, nil
}
