package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// Backups is the resolver for the backups field.
func (r *databaseResolver) Backups(ctx context.Context, obj *model.Database) (*model.DatabaseBackups, error) {
	backups, err := r.Conductor.DatabaseBackups(ctx, obj.ID)

	if err != nil {
		return nil, err
	}

	return new(convertDatabaseBackups(*backups)), nil
}

// CreateDatabaseBackup is the resolver for the createDatabaseBackup field.
func (r *mutationResolver) CreateDatabaseBackup(ctx context.Context, database platform.DatabaseID) (*model.DatabaseBackup, error) {
	backup, err := r.Conductor.CreateDatabaseBackup(ctx, database)

	if err != nil {
		return nil, err
	}

	return new(convertDatabaseBackup(*backup)), nil
}

// RestoreDatabase is the resolver for the restoreDatabase field.
func (r *mutationResolver) RestoreDatabase(ctx context.Context, input model.RestoreDatabaseInput) (*model.RestoreDatabaseResult, error) {
	result, err := r.Conductor.RestoreDatabase(ctx, input.Database, input.Name, input.TargetTime)

	if err != nil {
		return nil, err
	}

	return &model.RestoreDatabaseResult{
		Database:        new(convertDatabase(result.Database)),
		ClampedToLatest: result.Clamped,
	}, nil
}
