package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/zeitlos/lucity/pkg/tenant"
	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// SetEnvironmentResources is the resolver for the setEnvironmentResources field.
func (r *mutationResolver) SetEnvironmentResources(ctx context.Context, input model.SetEnvironmentResourcesInput) (*model.Environment, error) {
	tier, err := parseResourceTier(input.Tier)

	if err != nil {
		return nil, err
	}

	result, err := r.Conductor.SetEnvironmentResources(ctx, input.Environment, tier, input.CPUMillicores, input.MemoryMb, input.DiskMb)

	if err != nil {
		return nil, err
	}

	return new(convertEnvironment(*result)), nil
}

// ChangePlan is the resolver for the changePlan field.
func (r *mutationResolver) ChangePlan(ctx context.Context, plan model.Plan) (*model.BillingSubscription, error) {
	ws, err := tenant.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	res, err := r.Conductor.ChangePlan(ctx, ws, string(plan))
	if err != nil {
		return nil, err
	}
	return convertBillingSubscription(res), nil
}

// BillingPortalURL is the resolver for the billingPortalUrl field.
func (r *mutationResolver) BillingPortalURL(ctx context.Context) (*model.BillingPortalURL, error) {
	ws, err := tenant.FromContext(ctx)

	if err != nil {
		return nil, err
	}

	url, err := r.Conductor.BillingPortalURL(ctx, ws)

	if err != nil {
		return nil, err
	}

	return &model.BillingPortalURL{URL: url}, nil
}

// CreatePlanCheckout is the resolver for the createPlanCheckout field.
func (r *mutationResolver) CreatePlanCheckout(ctx context.Context, plan model.Plan) (*model.CheckoutSession, error) {
	ws, err := tenant.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	url, err := r.Conductor.CreatePlanCheckout(ctx, ws, string(plan))
	if err != nil {
		return nil, err
	}
	return &model.CheckoutSession{URL: url}, nil
}

// CompletePlanCheckout is the resolver for the completePlanCheckout field.
func (r *mutationResolver) CompletePlanCheckout(ctx context.Context, sessionID string) (*model.BillingSubscription, error) {
	ws, err := tenant.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	res, err := r.Conductor.CompletePlanCheckout(ctx, ws, sessionID)
	if err != nil {
		return nil, err
	}
	return convertBillingSubscription(res), nil
}

// EnvironmentResources is the resolver for the environmentResources field.
func (r *queryResolver) EnvironmentResources(ctx context.Context, environment platform.EnvironmentID) (*model.EnvironmentResources, error) {
	res, err := r.Conductor.EnvironmentResources(ctx, environment)
	if err != nil {
		return nil, err
	}
	result := convertEnvironmentResources(*res)
	return &result, nil
}

// Subscription is the resolver for the subscription field.
func (r *queryResolver) Subscription(ctx context.Context) (*model.BillingSubscription, error) {
	ws, err := tenant.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	res, err := r.Conductor.Subscription(ctx, ws)
	if err != nil {
		return nil, err
	}
	return convertBillingSubscription(res), nil
}

// UsageSummary is the resolver for the usageSummary field.
func (r *queryResolver) UsageSummary(ctx context.Context) (*model.UsageSummary, error) {
	ws, err := tenant.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	res, err := r.Conductor.UsageSummary(ctx, ws)
	if err != nil {
		return nil, err
	}
	return &model.UsageSummary{
		ResourceCostCents:   res.ResourceCostCents,
		CreditsCents:        res.CreditsCents,
		EstimatedTotalCents: res.EstimatedTotalCents,
	}, nil
}
