package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/buildjob"
)

// Build is the resolver for the build field.
func (r *queryResolver) Build(ctx context.Context, id buildjob.BuildID) (*model.Build, error) {
	build, err := r.Conductor.Build(ctx, id)

	if err != nil {
		return nil, err
	}

	return new(convertBuild(*build)), nil
}

// BuildLogs is the resolver for the buildLogs field.
func (r *subscriptionResolver) BuildLogs(ctx context.Context, id buildjob.BuildID) (<-chan string, error) {
	return r.Conductor.BuildLogs(ctx, id)
}
