package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// CreateDatabase is the resolver for the createDatabase field.
func (r *mutationResolver) CreateDatabase(ctx context.Context, input model.CreateDatabaseInput) (*model.Database, error) {
	version := ""
	if input.Version != nil {
		version = *input.Version
	}
	instances := 0
	if input.Instances != nil {
		instances = *input.Instances
	}
	size := ""
	if input.Size != nil {
		size = *input.Size
	}
	db, err := r.Conductor.CreateDatabase(ctx, input.Environment, input.Name, version, instances, size)
	if err != nil {
		return nil, err
	}
	result := convertDatabase(*db)
	return &result, nil
}

// DeleteDatabase is the resolver for the deleteDatabase field.
func (r *mutationResolver) DeleteDatabase(ctx context.Context, database platform.DatabaseID) (bool, error) {
	return r.Conductor.DeleteDatabase(ctx, database)
}

// ExecuteQuery is the resolver for the executeQuery field.
func (r *mutationResolver) ExecuteQuery(ctx context.Context, database platform.DatabaseID, query string) (*model.QueryResult, error) {
	result, err := r.Conductor.ExecuteQuery(ctx, database, query)
	if err != nil {
		return nil, err
	}
	return convertQueryResult(result), nil
}

// DatabaseTables is the resolver for the databaseTables field.
func (r *queryResolver) DatabaseTables(ctx context.Context, database platform.DatabaseID) ([]model.DatabaseTable, error) {
	tables, err := r.Conductor.DatabaseTables(ctx, database)
	if err != nil {
		return nil, err
	}
	result := make([]model.DatabaseTable, 0, len(tables))
	for _, t := range tables {
		result = append(result, convertDatabaseTable(t))
	}
	return result, nil
}

// DatabaseTableData is the resolver for the databaseTableData field.
func (r *queryResolver) DatabaseTableData(ctx context.Context, database platform.DatabaseID, table string, schema *string, limit *int, offset *int) (*model.DatabaseTableData, error) {
	s := "public"
	if schema != nil {
		s = *schema
	}
	l := 50
	if limit != nil {
		l = *limit
	}
	o := 0
	if offset != nil {
		o = *offset
	}
	data, err := r.Conductor.DatabaseTableData(ctx, database, table, s, l, o)
	if err != nil {
		return nil, err
	}
	return convertDatabaseTableData(data), nil
}

// DatabaseCredentials is the resolver for the databaseCredentials field.
func (r *queryResolver) DatabaseCredentials(ctx context.Context, database platform.DatabaseID) (*model.DatabaseCredentials, error) {
	creds, err := r.Conductor.DatabaseCredentials(ctx, database)
	if err != nil {
		return nil, err
	}
	return &model.DatabaseCredentials{
		Host:     creds.Host,
		Port:     creds.Port,
		Dbname:   creds.DBName,
		User:     creds.User,
		Password: creds.Password,
		URI:      creds.URI,
	}, nil
}
