package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// CommitMessage is the resolver for the commitMessage field.
func (r *deploymentResolver) CommitMessage(ctx context.Context, obj *model.Deployment) (string, error) {
	if obj.GitHubInstallationID == "" || obj.SourceURL == "" || obj.Commit == "" {
		return "", nil
	}

	return r.Conductor.CommitMessage(ctx, obj.GitHubInstallationID, obj.SourceURL, obj.Commit)
}

// Deployment is the resolver for the deployment field.
func (r *queryResolver) Deployment(ctx context.Context, id platform.DeploymentID) (*model.Deployment, error) {
	result, err := r.Conductor.Deployment(ctx, id)

	if err != nil {
		return nil, err
	}

	return new(convertDeployment(*result)), nil
}

// Deployment returns DeploymentResolver implementation.
func (r *Resolver) Deployment() DeploymentResolver { return &deploymentResolver{r} }

type deploymentResolver struct{ *Resolver }
