package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/zeitlos/lucity/pkg/to"
	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// Deploy is the resolver for the deploy field.
func (r *mutationResolver) Deploy(ctx context.Context, service platform.ServiceID, gitRef *string) (*model.Release, error) {
	if err := r.requireServiceDeployBinding(ctx, service); err != nil {
		return nil, err
	}

	release, err := r.Conductor.Deploy(ctx, service, to.Val(gitRef))

	if err != nil {
		return nil, err
	}
	result := convertRelease(*release)
	return &result, nil
}

// Deployment is the resolver for the deployment field.
func (r *queryResolver) Deployment(ctx context.Context, id platform.DeploymentID) (*model.Deployment, error) {
	result, err := r.Conductor.Deployment(ctx, id)

	if err != nil {
		return nil, err
	}

	return new(convertDeployment(*result)), nil
}
