package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"encoding/base64"
	"log/slog"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// EjectProject is the resolver for the ejectProject field.
func (r *queryResolver) EjectProject(ctx context.Context, id platform.ProjectID) (*model.EjectArtifact, error) {
	archive, err := r.Conductor.Eject(ctx, id)

	if err != nil {
		return nil, err
	}

	slog.InfoContext(ctx, "project ejected", "project", id.String())

	return &model.EjectArtifact{
		Filename:    id.Name + "-ejected.zip",
		ContentType: "application/zip",
		Content:     base64.StdEncoding.EncodeToString(archive),
	}, nil
}
