package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// ResourceTier is the resolver for the resourceTier field.
func (r *environmentResolver) ResourceTier(ctx context.Context, obj *model.Environment) (*model.ResourceTier, error) {
	panic(fmt.Errorf("not implemented: ResourceTier - resourceTier"))
}

// Services is the resolver for the services field.
func (r *environmentResolver) Services(ctx context.Context, obj *model.Environment) ([]model.Service, error) {
	panic(fmt.Errorf("not implemented: Services - services"))
}

// Databases is the resolver for the databases field.
func (r *environmentResolver) Databases(ctx context.Context, obj *model.Environment) ([]model.Database, error) {
	databases, err := r.Conductor.Databases(ctx, obj.ID)

	if err != nil {
		return nil, err
	}

	result := make([]model.Database, 0, len(databases))

	for _, db := range databases {
		result = append(result, convertDatabase(db))
	}

	return result, nil
}

// CreateEnvironment is the resolver for the createEnvironment field.
func (r *mutationResolver) CreateEnvironment(ctx context.Context, input model.CreateEnvironmentInput) (*model.Environment, error) {
	tier := ""
	if input.Tier != nil {
		tier = string(*input.Tier)
	}
	e, err := r.Conductor.CreateEnvironment(ctx, input.Project, input.Name, input.FromEnvironment, tier)
	if err != nil {
		return nil, err
	}
	result := convertEnvironment(*e, r.Conductor.Config.WorkloadDomain)
	return &result, nil
}

// DeleteEnvironment is the resolver for the deleteEnvironment field.
func (r *mutationResolver) DeleteEnvironment(ctx context.Context, environment platform.EnvironmentID) (bool, error) {
	return r.Conductor.DeleteEnvironment(ctx, environment)
}

// Environments is the resolver for the environments field.
func (r *queryResolver) Environments(ctx context.Context, project platform.ProjectID) ([]model.Environment, error) {
	panic(fmt.Errorf("not implemented: Environments - environments"))
}

// Environment is the resolver for the environment field.
func (r *queryResolver) Environment(ctx context.Context, environment platform.EnvironmentID) (*model.Environment, error) {
	panic(fmt.Errorf("not implemented: Environment - environment"))
}

// Environment returns EnvironmentResolver implementation.
func (r *Resolver) Environment() EnvironmentResolver { return &environmentResolver{r} }

type environmentResolver struct{ *Resolver }
