package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
)

// ResourceTier is the resolver for the resourceTier field.
func (r *environmentResolver) ResourceTier(ctx context.Context, obj *model.Environment) (*model.ResourceTier, error) {
	panic(fmt.Errorf("not implemented: ResourceTier - resourceTier"))
}

// CreateEnvironment is the resolver for the createEnvironment field.
func (r *mutationResolver) CreateEnvironment(ctx context.Context, input model.CreateEnvironmentInput) (*model.Environment, error) {
	fromEnv := ""
	if input.FromEnvironment != nil {
		fromEnv = *input.FromEnvironment
	}
	tier := ""
	if input.Tier != nil {
		tier = string(*input.Tier)
	}
	e, err := r.Conductor.CreateEnvironment(ctx, input.ProjectID, input.Name, fromEnv, tier)
	if err != nil {
		return nil, err
	}
	result := convertEnvironment(*e, r.Conductor.Config.WorkloadDomain)
	return &result, nil
}

// DeleteEnvironment is the resolver for the deleteEnvironment field.
func (r *mutationResolver) DeleteEnvironment(ctx context.Context, projectID string, environment string) (bool, error) {
	return r.Conductor.DeleteEnvironment(ctx, projectID, environment)
}

// Promote is the resolver for the promote field.
func (r *mutationResolver) Promote(ctx context.Context, input model.PromoteInput) (*model.ServiceInstance, error) {
	si, err := r.Conductor.Promote(ctx, input.ProjectID, input.Service, input.FromEnvironment, input.ToEnvironment)
	if err != nil {
		return nil, err
	}
	result := convertServiceInstance(*si, r.Conductor.Config.WorkloadDomain)
	return &result, nil
}

// Environment returns EnvironmentResolver implementation.
func (r *Resolver) Environment() EnvironmentResolver { return &environmentResolver{r} }

type environmentResolver struct{ *Resolver }
