package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// KeyValueStores is the resolver for the keyValueStores field.
func (r *environmentResolver) KeyValueStores(ctx context.Context, obj *model.Environment) ([]model.KeyValueStore, error) {
	stores, err := r.Conductor.KeyValueStores(ctx, obj.ID)

	if err != nil {
		return nil, err
	}

	result := make([]model.KeyValueStore, 0, len(stores))

	for _, store := range stores {
		result = append(result, convertKeyValueStore(store))
	}

	return result, nil
}

// CreateKeyValueStore is the resolver for the createKeyValueStore field.
func (r *mutationResolver) CreateKeyValueStore(ctx context.Context, input model.CreateKeyValueStoreInput) (*model.KeyValueStore, error) {
	version := ""
	if input.Version != nil {
		version = *input.Version
	}

	size := ""
	if input.Size != nil {
		size = *input.Size
	}

	store, err := r.Conductor.CreateKeyValueStore(ctx, input.Environment, input.Name, version, size)

	if err != nil {
		return nil, err
	}

	return new(convertKeyValueStore(*store)), nil
}

// DeleteKeyValueStore is the resolver for the deleteKeyValueStore field.
func (r *mutationResolver) DeleteKeyValueStore(ctx context.Context, keyValueStore platform.KeyValueStoreID) (bool, error) {
	return r.Conductor.DeleteKeyValueStore(ctx, keyValueStore)
}

// KeyValueStore is the resolver for the keyValueStore field.
func (r *queryResolver) KeyValueStore(ctx context.Context, id platform.KeyValueStoreID) (*model.KeyValueStore, error) {
	result, err := r.Conductor.KeyValueStore(ctx, id)

	if err != nil {
		return nil, err
	}

	return new(convertKeyValueStore(*result)), nil
}

// KeyValueStoreCredentials is the resolver for the keyValueStoreCredentials field.
func (r *queryResolver) KeyValueStoreCredentials(ctx context.Context, keyValueStore platform.KeyValueStoreID) ([]model.KeyValueStoreCredentials, error) {
	creds, err := r.Conductor.KeyValueStoreCredentials(ctx, keyValueStore)

	if err != nil {
		return nil, err
	}

	result := make([]model.KeyValueStoreCredentials, 0, len(creds))

	for _, c := range creds {
		result = append(result, convertKeyValueStoreCredentials(c))
	}

	return result, nil
}
