package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// ServiceLogs is the resolver for the serviceLogs field.
func (r *subscriptionResolver) ServiceLogs(ctx context.Context, service platform.ServiceID, tailLines *int) (<-chan *model.ServiceLogEntry, error) {
	ch, err := r.Conductor.ServiceLogs(ctx, service, tailLines)
	if err != nil {
		return nil, err
	}

	out := make(chan *model.ServiceLogEntry, 128)
	go func() {
		defer close(out)
		for entry := range ch {
			select {
			case out <- convertServiceLogEntry(entry):
			case <-ctx.Done():
				return
			}
		}
	}()

	return out, nil
}
