package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/zeitlos/lucity/pkg/to"
	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// Buckets is the resolver for the buckets field.
func (r *environmentResolver) Buckets(ctx context.Context, obj *model.Environment) ([]model.Bucket, error) {
	buckets, err := r.Conductor.Buckets(ctx, obj.ID)

	if err != nil {
		return nil, err
	}

	result := make([]model.Bucket, 0, len(buckets))

	for _, bucket := range buckets {
		result = append(result, convertBucket(bucket))
	}

	return result, nil
}

// CreateBucket is the resolver for the createBucket field.
func (r *mutationResolver) CreateBucket(ctx context.Context, input model.CreateBucketInput) (*model.Bucket, error) {
	bucket, err := r.Conductor.CreateBucket(ctx, input.Environment, input.Name)

	if err != nil {
		return nil, err
	}

	result := convertBucket(*bucket)

	return &result, nil
}

// DeleteBucket is the resolver for the deleteBucket field.
func (r *mutationResolver) DeleteBucket(ctx context.Context, bucket platform.BucketID) (bool, error) {
	return r.Conductor.DeleteBucket(ctx, bucket)
}

// SetBucketPublic is the resolver for the setBucketPublic field.
func (r *mutationResolver) SetBucketPublic(ctx context.Context, bucket platform.BucketID, public bool) (*model.Bucket, error) {
	result, err := r.Conductor.SetBucketPublic(ctx, bucket, public)

	if err != nil {
		return nil, err
	}

	converted := convertBucket(*result)

	return &converted, nil
}

// BucketObjectUploadURL is the resolver for the bucketObjectUploadUrl field.
func (r *mutationResolver) BucketObjectUploadURL(ctx context.Context, bucket platform.BucketID, key string) (string, error) {
	return r.Conductor.BucketObjectUploadURL(ctx, bucket, key)
}

// DeleteBucketObject is the resolver for the deleteBucketObject field.
func (r *mutationResolver) DeleteBucketObject(ctx context.Context, bucket platform.BucketID, key string) (bool, error) {
	return r.Conductor.DeleteBucketObject(ctx, bucket, key)
}

// Bucket is the resolver for the bucket field.
func (r *queryResolver) Bucket(ctx context.Context, id platform.BucketID) (*model.Bucket, error) {
	bucket, err := r.Conductor.Bucket(ctx, id)

	if err != nil {
		return nil, err
	}

	result := convertBucket(*bucket)

	return &result, nil
}

// BucketCredentials is the resolver for the bucketCredentials field.
func (r *queryResolver) BucketCredentials(ctx context.Context, bucket platform.BucketID) (*model.BucketCredentials, error) {
	creds, err := r.Conductor.BucketCredentials(ctx, bucket)

	if err != nil {
		return nil, err
	}

	result := convertBucketCredentials(*creds)

	return &result, nil
}

// BucketObjects is the resolver for the bucketObjects field.
func (r *queryResolver) BucketObjects(ctx context.Context, bucket platform.BucketID, prefix *string) (*model.BucketObjectListing, error) {
	listing, err := r.Conductor.BucketObjects(ctx, bucket, to.Val(prefix))

	if err != nil {
		return nil, err
	}

	result := convertBucketObjectListing(*listing)

	return &result, nil
}

// BucketObjectDownloadURL is the resolver for the bucketObjectDownloadUrl field.
func (r *queryResolver) BucketObjectDownloadURL(ctx context.Context, bucket platform.BucketID, key string) (string, error) {
	return r.Conductor.BucketObjectDownloadURL(ctx, bucket, key)
}
