package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/zeitlos/lucity/pkg/tenant"
	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/conductor"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	ws, err := tenant.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	slug := ""
	if input.ID != nil {
		slug = *input.ID
	}
	p, err := r.Conductor.CreateProject(ctx, ws, slug, input.Name)
	if err != nil {
		return nil, err
	}
	result := convertProject(*p, r.Conductor.Config.WorkloadDomain)
	return &result, nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id platform.ProjectID) (bool, error) {
	return r.Conductor.DeleteProject(ctx, id)
}

// SetServiceScaling is the resolver for the setServiceScaling field.
func (r *mutationResolver) SetServiceScaling(ctx context.Context, input model.SetServiceScalingInput) (*model.ScalingConfig, error) {
	var autoscaling *conductor.AutoscalingConfig
	if input.Autoscaling != nil {
		autoscaling = &conductor.AutoscalingConfig{
			Enabled:     input.Autoscaling.Enabled,
			MinReplicas: input.Autoscaling.MinReplicas,
			MaxReplicas: input.Autoscaling.MaxReplicas,
			TargetCPU:   input.Autoscaling.TargetCPU,
		}
	}
	sc, err := r.Conductor.SetServiceScaling(ctx, input.Service, input.Replicas, autoscaling)
	if err != nil {
		return nil, err
	}
	result := convertScalingConfig(*sc)
	return &result, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]model.Project, error) {
	ws, err := tenant.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	projects, err := r.Conductor.Projects(ctx, ws)
	if err != nil {
		return nil, err
	}
	result := make([]model.Project, 0, len(projects))
	for _, p := range projects {
		result = append(result, convertProject(p, r.Conductor.Config.WorkloadDomain))
	}
	return result, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id platform.ProjectID) (*model.Project, error) {
	p, err := r.Conductor.Project(ctx, id)
	if err != nil {
		return nil, err
	}
	result := convertProject(*p, r.Conductor.Config.WorkloadDomain)
	return &result, nil
}
