package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
)

// Releases is the resolver for the releases field.
func (r *serviceResolver) Releases(ctx context.Context, obj *model.Service) ([]model.Release, error) {
	releases, err := r.Conductor.Releases(ctx, obj.PlatformService)

	if err != nil {
		return nil, err
	}

	result := make([]model.Release, 0, len(releases))

	for _, release := range releases {
		result = append(result, convertRelease(release))
	}

	return result, nil
}
