package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/scanjob"
)

// SecretScanReport is the resolver for the secretScanReport field.
func (r *serviceResolver) SecretScanReport(ctx context.Context, obj *model.Service) (*model.SecretScanReport, error) {
	report, err := r.Conductor.SecretScanReport(ctx, obj.ID)

	if err != nil {
		return nil, err
	}

	if report == nil {
		return nil, nil
	}

	converted := convertSecretScanReport(*report)

	return &converted, nil
}

// ScanLogs is the resolver for the scanLogs field.
func (r *subscriptionResolver) ScanLogs(ctx context.Context, id scanjob.ScanID) (<-chan string, error) {
	return r.Conductor.ScanLogs(ctx, id)
}
