package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/scanjob"
)

// SecretScanReports is the resolver for the secretScanReports field.
func (r *serviceResolver) SecretScanReports(ctx context.Context, obj *model.Service) ([]model.SecretScanReport, error) {
	reports, err := r.Conductor.SecretScanReports(ctx, obj.ID)

	if err != nil {
		return nil, err
	}

	result := make([]model.SecretScanReport, 0, len(reports))

	for _, report := range reports {
		result = append(result, convertSecretScanReport(report))
	}

	return result, nil
}

// ScanLogs is the resolver for the scanLogs field.
func (r *subscriptionResolver) ScanLogs(ctx context.Context, id scanjob.ScanID) (<-chan string, error) {
	return r.Conductor.ScanLogs(ctx, id)
}
