package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
)

// PlatformConfig is the resolver for the platformConfig field.
func (r *queryResolver) PlatformConfig(ctx context.Context) (*model.PlatformConfig, error) {
	wd, dt, ip := r.Conductor.PlatformConfig()
	return &model.PlatformConfig{
		WorkloadDomain: wd,
		DomainTarget:   dt,
		IPAddress:      ip,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
