package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strconv"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/conductor"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// AddService is the resolver for the addService field.
func (r *mutationResolver) AddService(ctx context.Context, input model.AddServiceInput) (*model.Service, error) {
	framework := ""
	if input.Framework != nil {
		framework = *input.Framework
	}
	startCommand := ""
	if input.StartCommand != nil {
		startCommand = *input.StartCommand
	}
	repository := ""
	if input.Repository != nil {
		repository = *input.Repository
	}
	contextPath := ""
	if input.ContextPath != nil {
		contextPath = *input.ContextPath
	}
	var installationID *int64
	if input.InstallationID != nil {
		id, err := strconv.ParseInt(*input.InstallationID, 10, 64)
		if err != nil {
			return nil, fmt.Errorf("invalid installation ID: %w", err)
		}
		installationID = &id
	}
	name := ""
	if input.Name != nil {
		name = *input.Name
	}
	port := 0
	if input.Port != nil {
		port = *input.Port
	}
	externalImage := ""
	if input.Image != nil {
		externalImage = *input.Image
	}
	customStartCommand := ""
	if input.CustomStartCommand != nil {
		customStartCommand = *input.CustomStartCommand
	}
	si, err := r.Conductor.AddService(ctx, input.Environment, name, port, framework, startCommand, repository, contextPath, installationID, externalImage, customStartCommand)
	if err != nil {
		return nil, err
	}
	result := convertService(*si)
	return &result, nil
}

// RemoveService is the resolver for the removeService field.
func (r *mutationResolver) RemoveService(ctx context.Context, service platform.ServiceID) (bool, error) {
	return r.Conductor.RemoveService(ctx, service)
}

// SetCustomStartCommand is the resolver for the setCustomStartCommand field.
func (r *mutationResolver) SetCustomStartCommand(ctx context.Context, service platform.ServiceID, command string) (*model.Service, error) {
	result, err := r.Conductor.SetCustomStartCommand(ctx, service, command)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// SetServiceScaling is the resolver for the setServiceScaling field.
func (r *mutationResolver) SetServiceScaling(ctx context.Context, input model.SetServiceScalingInput) (*model.Service, error) {
	var autoscaling *conductor.AutoscalingConfig
	if input.Autoscaling != nil {
		autoscaling = &conductor.AutoscalingConfig{
			Enabled:     input.Autoscaling.Enabled,
			MinReplicas: input.Autoscaling.MinReplicas,
			MaxReplicas: input.Autoscaling.MaxReplicas,
			TargetCPU:   input.Autoscaling.TargetCPU,
		}
	}

	result, err := r.Conductor.SetServiceScaling(ctx, input.Service, input.Replicas, autoscaling)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// Deploy is the resolver for the deploy field.
func (r *mutationResolver) Deploy(ctx context.Context, service platform.ServiceID, gitRef *string) (*model.DeployRun, error) {
	ref := ""
	if gitRef != nil {
		ref = *gitRef
	}
	d, err := r.Conductor.Deploy(ctx, service, ref)
	if err != nil {
		return nil, err
	}
	result := convertDeploymentOp(*d)
	return &result, nil
}

// Rollback is the resolver for the rollback field.
func (r *mutationResolver) Rollback(ctx context.Context, deployment platform.DeploymentID) (bool, error) {
	return r.Conductor.Rollback(ctx, deployment)
}

// GenerateDomain is the resolver for the generateDomain field.
func (r *mutationResolver) GenerateDomain(ctx context.Context, service platform.ServiceID) (*model.Service, error) {
	result, err := r.Conductor.GenerateDomain(ctx, service)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// AddCustomDomain is the resolver for the addCustomDomain field.
func (r *mutationResolver) AddCustomDomain(ctx context.Context, service platform.ServiceID, hostname string) (*model.Service, error) {
	result, err := r.Conductor.AddCustomDomain(ctx, service, hostname)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// RemoveDomain is the resolver for the removeDomain field.
func (r *mutationResolver) RemoveDomain(ctx context.Context, service platform.ServiceID, hostname string) (*model.Service, error) {
	result, err := r.Conductor.RemoveDomain(ctx, service, hostname)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// Service is the resolver for the service field.
func (r *queryResolver) Service(ctx context.Context, id platform.ServiceID) (*model.Service, error) {
	result, err := r.Conductor.Service(ctx, id)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// DetectServices is the resolver for the detectServices field.
func (r *queryResolver) DetectServices(ctx context.Context, installationID string, repository string) ([]model.DetectedService, error) {
	instID, err := strconv.ParseInt(installationID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid installation ID: %w", err)
	}
	services, err := r.Conductor.DetectServices(ctx, repository, instID)
	if err != nil {
		return nil, err
	}
	result := make([]model.DetectedService, 0, len(services))
	for _, s := range services {
		result = append(result, convertDetectedService(s))
	}
	return result, nil
}

// DeployStatus is the resolver for the deployStatus field.
func (r *queryResolver) DeployStatus(ctx context.Context, id string) (*model.DeployRun, error) {
	d, err := r.Conductor.DeployStatus(ctx, id)
	if err != nil {
		return nil, err
	}
	result := convertDeploymentOp(*d)
	return &result, nil
}

// ActiveDeployment is the resolver for the activeDeployment field.
func (r *queryResolver) ActiveDeployment(ctx context.Context, service platform.ServiceID) (*model.DeployRun, error) {
	d, err := r.Conductor.ActiveDeployment(ctx, service)
	if err != nil {
		return nil, err
	}
	if d == nil {
		return nil, nil
	}
	result := convertDeploymentOp(*d)
	return &result, nil
}

// CheckDNSStatus is the resolver for the checkDnsStatus field.
func (r *queryResolver) CheckDNSStatus(ctx context.Context, hostname string) (*model.DNSCheck, error) {
	check := r.Conductor.CheckDns(ctx, hostname)
	return convertDnsCheck(check), nil
}

// DefaultCommand is the resolver for the defaultCommand field.
func (r *serviceResolver) DefaultCommand(ctx context.Context, obj *model.Service) (string, error) {
	return r.Conductor.DefaultCommand(ctx, obj.ActiveDeployment.Image)
}

// Deployments is the resolver for the deployments field.
func (r *serviceResolver) Deployments(ctx context.Context, obj *model.Service) ([]model.Deployment, error) {
	deployments, err := r.Conductor.Deployments(ctx, obj.ID)

	if err != nil {
		return nil, err
	}

	var result []model.Deployment

	for _, deployment := range deployments {
		result = append(result, convertDeployment(deployment))
	}

	return result, nil
}

// DeployLogs is the resolver for the deployLogs field.
func (r *subscriptionResolver) DeployLogs(ctx context.Context, id string) (<-chan string, error) {
	ch, unsub, err := r.Conductor.DeployLogs(ctx, id)
	if err != nil {
		return nil, err
	}
	// Unsubscribe when the client disconnects.
	go func() {
		<-ctx.Done()
		unsub()
	}()
	return ch, nil
}

// Service returns ServiceResolver implementation.
func (r *Resolver) Service() ServiceResolver { return &serviceResolver{r} }

type serviceResolver struct{ *Resolver }
