package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"log/slog"

	"github.com/zeitlos/lucity/pkg/to"
	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/conductor"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// AddService is the resolver for the addService field.
func (r *mutationResolver) AddService(ctx context.Context, environment platform.EnvironmentID, input model.AddServiceInput) (*model.Service, error) {
	variables := make(map[string]string, len(input.Variables))
	for _, variable := range input.Variables {
		variables[variable.Key] = variable.Value
	}

	service, err := r.Conductor.AddService(ctx, environment, to.Val(input.Name), to.Val(input.Repository), to.Val(input.ContextPath), to.Val(input.Image), variables)

	if err != nil {
		return nil, err
	}

	return new(convertService(*service)), nil
}

// RemoveService is the resolver for the removeService field.
func (r *mutationResolver) RemoveService(ctx context.Context, service platform.ServiceID) (bool, error) {
	return r.Conductor.RemoveService(ctx, service)
}

// SetCustomStartCommand is the resolver for the setCustomStartCommand field.
func (r *mutationResolver) SetCustomStartCommand(ctx context.Context, service platform.ServiceID, command string) (*model.Service, error) {
	result, err := r.Conductor.SetCustomStartCommand(ctx, service, command)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// SetServiceBranch is the resolver for the setServiceBranch field.
func (r *mutationResolver) SetServiceBranch(ctx context.Context, service platform.ServiceID, branch *string) (*model.Service, error) {
	result, err := r.Conductor.SetServiceBranch(ctx, service, to.Val(branch))

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// SetAutoDeploy is the resolver for the setAutoDeploy field.
func (r *mutationResolver) SetAutoDeploy(ctx context.Context, service platform.ServiceID, enabled bool) (*model.Service, error) {
	result, err := r.Conductor.SetAutoDeploy(ctx, service, enabled)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// SetServicePort is the resolver for the setServicePort field.
func (r *mutationResolver) SetServicePort(ctx context.Context, service platform.ServiceID, port *int) (*model.Service, error) {
	p := 0
	if port != nil {
		p = *port
	}

	result, err := r.Conductor.SetServicePort(ctx, service, p)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// SetServiceScaling is the resolver for the setServiceScaling field.
func (r *mutationResolver) SetServiceScaling(ctx context.Context, input model.SetServiceScalingInput) (*model.Service, error) {
	var autoscaling *conductor.AutoscalingConfig
	if input.Autoscaling != nil {
		autoscaling = &conductor.AutoscalingConfig{
			Enabled:     input.Autoscaling.Enabled,
			MinReplicas: input.Autoscaling.MinReplicas,
			MaxReplicas: input.Autoscaling.MaxReplicas,
			TargetCPU:   input.Autoscaling.TargetCPU,
		}
	}

	result, err := r.Conductor.SetServiceScaling(ctx, input.Service, input.Replicas, autoscaling)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// SetServiceResources is the resolver for the setServiceResources field.
func (r *mutationResolver) SetServiceResources(ctx context.Context, service platform.ServiceID, resources model.ResourcesInput) (*model.Service, error) {
	result, err := r.Conductor.SetServiceResources(ctx, service, resources.CPU, resources.Memory)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// Rollback is the resolver for the rollback field.
func (r *mutationResolver) Rollback(ctx context.Context, deployment platform.DeploymentID) (bool, error) {
	return r.Conductor.Rollback(ctx, deployment)
}

// GenerateDomain is the resolver for the generateDomain field.
func (r *mutationResolver) GenerateDomain(ctx context.Context, service platform.ServiceID) (*model.Service, error) {
	result, err := r.Conductor.GenerateDomain(ctx, service)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// AddCustomDomain is the resolver for the addCustomDomain field.
func (r *mutationResolver) AddCustomDomain(ctx context.Context, service platform.ServiceID, hostname string) (*model.Service, error) {
	result, err := r.Conductor.AddCustomDomain(ctx, service, hostname)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// RemoveDomain is the resolver for the removeDomain field.
func (r *mutationResolver) RemoveDomain(ctx context.Context, service platform.ServiceID, hostname string) (*model.Service, error) {
	result, err := r.Conductor.RemoveDomain(ctx, service, hostname)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// Service is the resolver for the service field.
func (r *queryResolver) Service(ctx context.Context, id platform.ServiceID) (*model.Service, error) {
	result, err := r.Conductor.Service(ctx, id)

	if err != nil {
		return nil, err
	}

	return new(convertService(*result)), nil
}

// DetectServices is the resolver for the detectServices field.
func (r *queryResolver) DetectServices(ctx context.Context, repositoryURL string) ([]model.DetectedService, error) {
	services, err := r.Conductor.DetectServices(ctx, repositoryURL)
	if err != nil {
		return nil, err
	}
	result := make([]model.DetectedService, 0, len(services))
	for _, s := range services {
		result = append(result, convertDetectedService(s))
	}
	return result, nil
}

// RepositoryBranches is the resolver for the repositoryBranches field.
func (r *queryResolver) RepositoryBranches(ctx context.Context, repositoryURL string) ([]string, error) {
	return r.Conductor.RepositoryBranches(ctx, repositoryURL)
}

// Endpoints is the resolver for the endpoints field.
func (r *serviceResolver) Endpoints(ctx context.Context, obj *model.Service) ([]model.Endpoint, error) {
	endpoints, err := r.Conductor.Endpoints(ctx, obj.ID, obj.PlatformService.Endpoints)

	if err != nil {
		return nil, err
	}

	result := make([]model.Endpoint, 0, len(endpoints))

	for _, endpoint := range endpoints {
		result = append(result, convertEndpoint(endpoint))
	}

	return result, nil
}

// DefaultCommand is the resolver for the defaultCommand field.
func (r *serviceResolver) DefaultCommand(ctx context.Context, obj *model.Service) (string, error) {
	if obj.ActiveDeployment == nil || obj.Status == model.ServiceStatusBuilding {
		return "", nil
	}

	command, err := r.Conductor.DefaultCommand(ctx, obj.ActiveDeployment.Image)
	if err != nil {
		slog.Warn("could not resolve default command", "service", obj.ID, "image", obj.ActiveDeployment.Image, "error", err)
		return "", nil
	}

	return command, nil
}

// Deployments is the resolver for the deployments field.
func (r *serviceResolver) Deployments(ctx context.Context, obj *model.Service) ([]model.Deployment, error) {
	result := make([]model.Deployment, 0, len(obj.PlatformService.Deployments))

	for _, deployment := range obj.PlatformService.Deployments {
		result = append(result, convertDeployment(deployment))
	}

	return result, nil
}

// Builds is the resolver for the builds field.
func (r *serviceResolver) Builds(ctx context.Context, obj *model.Service) ([]model.Build, error) {
	builds, err := r.Conductor.Builds(ctx, obj.ID.Workspace, obj.SourceURL, obj.ContextPath)

	if err != nil {
		return nil, err
	}

	var result []model.Build

	for _, build := range builds {
		result = append(result, convertBuild(build))
	}

	return result, nil
}

// Metrics is the resolver for the metrics field.
func (r *serviceResolver) Metrics(ctx context.Context, obj *model.Service, metrics []model.ResourceMetric, rangeArg model.MetricsRange, grouping model.MetricGrouping) ([]model.MetricSeries, error) {
	window, err := convertMetricWindow(rangeArg.Window)

	if err != nil {
		return nil, err
	}

	series, err := r.Conductor.ServiceUsage(ctx, obj.ID, serviceMetricKinds(metrics), window, grouping == model.MetricGroupingPerReplica)

	if err != nil {
		return nil, err
	}

	return convertMetricSeries(series), nil
}

// Service returns ServiceResolver implementation.
func (r *Resolver) Service() ServiceResolver { return &serviceResolver{r} }

type serviceResolver struct{ *Resolver }
