package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// CreateVolume is the resolver for the createVolume field.
func (r *mutationResolver) CreateVolume(ctx context.Context, environment platform.EnvironmentID, name string, size string) (*model.Volume, error) {
	volume, err := r.Conductor.CreateVolume(ctx, environment, name, size)

	if err != nil {
		return nil, err
	}

	return new(convertVolume(*volume)), nil
}

// ExpandVolume is the resolver for the expandVolume field.
func (r *mutationResolver) ExpandVolume(ctx context.Context, volume platform.VolumeID, size string) (*model.Volume, error) {
	result, err := r.Conductor.ExpandVolume(ctx, volume, size)

	if err != nil {
		return nil, err
	}

	return new(convertVolume(*result)), nil
}

// MountVolume is the resolver for the mountVolume field.
func (r *mutationResolver) MountVolume(ctx context.Context, volume platform.VolumeID, service platform.ServiceID, path string) (*model.Volume, error) {
	result, err := r.Conductor.MountVolume(ctx, volume, service, path)

	if err != nil {
		return nil, err
	}

	return new(convertVolume(*result)), nil
}

// UnmountVolume is the resolver for the unmountVolume field.
func (r *mutationResolver) UnmountVolume(ctx context.Context, volume platform.VolumeID) (*model.Volume, error) {
	result, err := r.Conductor.UnmountVolume(ctx, volume)

	if err != nil {
		return nil, err
	}

	return new(convertVolume(*result)), nil
}

// DeleteVolume is the resolver for the deleteVolume field.
func (r *mutationResolver) DeleteVolume(ctx context.Context, volume platform.VolumeID) (bool, error) {
	return r.Conductor.DeleteVolume(ctx, volume)
}

// Volume is the resolver for the volume field.
func (r *queryResolver) Volume(ctx context.Context, id platform.VolumeID) (*model.Volume, error) {
	result, err := r.Conductor.Volume(ctx, id)

	if err != nil {
		return nil, err
	}

	return new(convertVolume(*result)), nil
}

// Metrics is the resolver for the metrics field.
func (r *volumeResolver) Metrics(ctx context.Context, obj *model.Volume, metrics []model.ResourceMetric, rangeArg model.MetricsRange) ([]model.MetricSeries, error) {
	window, err := convertMetricWindow(rangeArg.Window)

	if err != nil {
		return nil, err
	}

	series := make([]model.MetricSeries, 0, len(metrics))

	for _, metric := range metrics {
		if metric != model.ResourceMetricStorageUsed {
			continue
		}

		used, err := r.Conductor.VolumeStorageUsed(ctx, obj.ID, window)

		if err != nil {
			return nil, err
		}

		series = append(series, model.MetricSeries{
			Metric: model.ResourceMetricStorageUsed,
			Unit:   model.MetricUnitBytes,
			Points: convertMetricPoints(used.Points),
		})
	}

	return series, nil
}

// Volume returns VolumeResolver implementation.
func (r *Resolver) Volume() VolumeResolver { return &volumeResolver{r} }

type volumeResolver struct{ *Resolver }
