package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/zeitlos/lucity/services/conductor/internal/api/graphql/model"
	"github.com/zeitlos/lucity/services/conductor/internal/platform"
)

// CreateVolume is the resolver for the createVolume field.
func (r *mutationResolver) CreateVolume(ctx context.Context, name string, size string) (*model.Volume, error) {
	panic(fmt.Errorf("not implemented: CreateVolume - createVolume"))
}

// MountVolume is the resolver for the mountVolume field.
func (r *mutationResolver) MountVolume(ctx context.Context, volume platform.VolumeID, service platform.ServiceID, path string) (*model.Volume, error) {
	panic(fmt.Errorf("not implemented: MountVolume - mountVolume"))
}

// UnmountVolume is the resolver for the unmountVolume field.
func (r *mutationResolver) UnmountVolume(ctx context.Context, volume platform.VolumeID) (*model.Volume, error) {
	panic(fmt.Errorf("not implemented: UnmountVolume - unmountVolume"))
}

// DeleteVolume is the resolver for the deleteVolume field.
func (r *mutationResolver) DeleteVolume(ctx context.Context, volume platform.VolumeID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteVolume - deleteVolume"))
}

// Volume is the resolver for the volume field.
func (r *queryResolver) Volume(ctx context.Context, id platform.VolumeID) (*model.Volume, error) {
	panic(fmt.Errorf("not implemented: Volume - volume"))
}
