// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: cashier.proto

package cashier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CashierService_CreateCustomer_FullMethodName          = "/cashier.CashierService/CreateCustomer"
	CashierService_CreateSubscription_FullMethodName      = "/cashier.CashierService/CreateSubscription"
	CashierService_ChangePlan_FullMethodName              = "/cashier.CashierService/ChangePlan"
	CashierService_Subscription_FullMethodName            = "/cashier.CashierService/Subscription"
	CashierService_BillingPortalURL_FullMethodName        = "/cashier.CashierService/BillingPortalURL"
	CashierService_UsageSummary_FullMethodName            = "/cashier.CashierService/UsageSummary"
	CashierService_CreateCheckoutSession_FullMethodName   = "/cashier.CashierService/CreateCheckoutSession"
	CashierService_RetrieveCheckoutSession_FullMethodName = "/cashier.CashierService/RetrieveCheckoutSession"
)

// CashierServiceClient is the client API for CashierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CashierServiceClient interface {
	// CreateCustomer creates a Stripe Customer for a workspace.
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error)
	// CreateSubscription creates a Stripe Subscription for a workspace.
	CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error)
	// ChangePlan switches a workspace between Hobby and Pro plans.
	ChangePlan(ctx context.Context, in *ChangePlanRequest, opts ...grpc.CallOption) (*ChangePlanResponse, error)
	// Subscription returns the current subscription for a workspace.
	Subscription(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	// BillingPortalURL returns a Stripe Billing Portal session URL.
	BillingPortalURL(ctx context.Context, in *BillingPortalURLRequest, opts ...grpc.CallOption) (*BillingPortalURLResponse, error)
	// UsageSummary returns the current billing period's usage summary.
	UsageSummary(ctx context.Context, in *UsageSummaryRequest, opts ...grpc.CallOption) (*UsageSummaryResponse, error)
	// CreateCheckoutSession creates a Stripe Checkout Session in subscription mode.
	CreateCheckoutSession(ctx context.Context, in *CreateCheckoutSessionRequest, opts ...grpc.CallOption) (*CreateCheckoutSessionResponse, error)
	// RetrieveCheckoutSession retrieves a completed Checkout Session for verification.
	RetrieveCheckoutSession(ctx context.Context, in *RetrieveCheckoutSessionRequest, opts ...grpc.CallOption) (*RetrieveCheckoutSessionResponse, error)
}

type cashierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCashierServiceClient(cc grpc.ClientConnInterface) CashierServiceClient {
	return &cashierServiceClient{cc}
}

func (c *cashierServiceClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCustomerResponse)
	err := c.cc.Invoke(ctx, CashierService_CreateCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierServiceClient) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubscriptionResponse)
	err := c.cc.Invoke(ctx, CashierService_CreateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierServiceClient) ChangePlan(ctx context.Context, in *ChangePlanRequest, opts ...grpc.CallOption) (*ChangePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangePlanResponse)
	err := c.cc.Invoke(ctx, CashierService_ChangePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierServiceClient) Subscription(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, CashierService_Subscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierServiceClient) BillingPortalURL(ctx context.Context, in *BillingPortalURLRequest, opts ...grpc.CallOption) (*BillingPortalURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BillingPortalURLResponse)
	err := c.cc.Invoke(ctx, CashierService_BillingPortalURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierServiceClient) UsageSummary(ctx context.Context, in *UsageSummaryRequest, opts ...grpc.CallOption) (*UsageSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsageSummaryResponse)
	err := c.cc.Invoke(ctx, CashierService_UsageSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierServiceClient) CreateCheckoutSession(ctx context.Context, in *CreateCheckoutSessionRequest, opts ...grpc.CallOption) (*CreateCheckoutSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCheckoutSessionResponse)
	err := c.cc.Invoke(ctx, CashierService_CreateCheckoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashierServiceClient) RetrieveCheckoutSession(ctx context.Context, in *RetrieveCheckoutSessionRequest, opts ...grpc.CallOption) (*RetrieveCheckoutSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveCheckoutSessionResponse)
	err := c.cc.Invoke(ctx, CashierService_RetrieveCheckoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CashierServiceServer is the server API for CashierService service.
// All implementations must embed UnimplementedCashierServiceServer
// for forward compatibility.
type CashierServiceServer interface {
	// CreateCustomer creates a Stripe Customer for a workspace.
	CreateCustomer(context.Context, *CreateCustomerRequest) (*CreateCustomerResponse, error)
	// CreateSubscription creates a Stripe Subscription for a workspace.
	CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error)
	// ChangePlan switches a workspace between Hobby and Pro plans.
	ChangePlan(context.Context, *ChangePlanRequest) (*ChangePlanResponse, error)
	// Subscription returns the current subscription for a workspace.
	Subscription(context.Context, *SubscriptionRequest) (*SubscriptionResponse, error)
	// BillingPortalURL returns a Stripe Billing Portal session URL.
	BillingPortalURL(context.Context, *BillingPortalURLRequest) (*BillingPortalURLResponse, error)
	// UsageSummary returns the current billing period's usage summary.
	UsageSummary(context.Context, *UsageSummaryRequest) (*UsageSummaryResponse, error)
	// CreateCheckoutSession creates a Stripe Checkout Session in subscription mode.
	CreateCheckoutSession(context.Context, *CreateCheckoutSessionRequest) (*CreateCheckoutSessionResponse, error)
	// RetrieveCheckoutSession retrieves a completed Checkout Session for verification.
	RetrieveCheckoutSession(context.Context, *RetrieveCheckoutSessionRequest) (*RetrieveCheckoutSessionResponse, error)
	mustEmbedUnimplementedCashierServiceServer()
}

// UnimplementedCashierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCashierServiceServer struct{}

func (UnimplementedCashierServiceServer) CreateCustomer(context.Context, *CreateCustomerRequest) (*CreateCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (UnimplementedCashierServiceServer) CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedCashierServiceServer) ChangePlan(context.Context, *ChangePlanRequest) (*ChangePlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePlan not implemented")
}
func (UnimplementedCashierServiceServer) Subscription(context.Context, *SubscriptionRequest) (*SubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscription not implemented")
}
func (UnimplementedCashierServiceServer) BillingPortalURL(context.Context, *BillingPortalURLRequest) (*BillingPortalURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BillingPortalURL not implemented")
}
func (UnimplementedCashierServiceServer) UsageSummary(context.Context, *UsageSummaryRequest) (*UsageSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsageSummary not implemented")
}
func (UnimplementedCashierServiceServer) CreateCheckoutSession(context.Context, *CreateCheckoutSessionRequest) (*CreateCheckoutSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCheckoutSession not implemented")
}
func (UnimplementedCashierServiceServer) RetrieveCheckoutSession(context.Context, *RetrieveCheckoutSessionRequest) (*RetrieveCheckoutSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveCheckoutSession not implemented")
}
func (UnimplementedCashierServiceServer) mustEmbedUnimplementedCashierServiceServer() {}
func (UnimplementedCashierServiceServer) testEmbeddedByValue()                        {}

// UnsafeCashierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CashierServiceServer will
// result in compilation errors.
type UnsafeCashierServiceServer interface {
	mustEmbedUnimplementedCashierServiceServer()
}

func RegisterCashierServiceServer(s grpc.ServiceRegistrar, srv CashierServiceServer) {
	// If the following call pancis, it indicates UnimplementedCashierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CashierService_ServiceDesc, srv)
}

func _CashierService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierService_CreateCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierServiceServer).CreateCustomer(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierService_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierServiceServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierService_CreateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierServiceServer).CreateSubscription(ctx, req.(*CreateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierService_ChangePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierServiceServer).ChangePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierService_ChangePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierServiceServer).ChangePlan(ctx, req.(*ChangePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierService_Subscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierServiceServer).Subscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierService_Subscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierServiceServer).Subscription(ctx, req.(*SubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierService_BillingPortalURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillingPortalURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierServiceServer).BillingPortalURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierService_BillingPortalURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierServiceServer).BillingPortalURL(ctx, req.(*BillingPortalURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierService_UsageSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsageSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierServiceServer).UsageSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierService_UsageSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierServiceServer).UsageSummary(ctx, req.(*UsageSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierService_CreateCheckoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCheckoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierServiceServer).CreateCheckoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierService_CreateCheckoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierServiceServer).CreateCheckoutSession(ctx, req.(*CreateCheckoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CashierService_RetrieveCheckoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveCheckoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CashierServiceServer).RetrieveCheckoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CashierService_RetrieveCheckoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CashierServiceServer).RetrieveCheckoutSession(ctx, req.(*RetrieveCheckoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CashierService_ServiceDesc is the grpc.ServiceDesc for CashierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CashierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cashier.CashierService",
	HandlerType: (*CashierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _CashierService_CreateCustomer_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _CashierService_CreateSubscription_Handler,
		},
		{
			MethodName: "ChangePlan",
			Handler:    _CashierService_ChangePlan_Handler,
		},
		{
			MethodName: "Subscription",
			Handler:    _CashierService_Subscription_Handler,
		},
		{
			MethodName: "BillingPortalURL",
			Handler:    _CashierService_BillingPortalURL_Handler,
		},
		{
			MethodName: "UsageSummary",
			Handler:    _CashierService_UsageSummary_Handler,
		},
		{
			MethodName: "CreateCheckoutSession",
			Handler:    _CashierService_CreateCheckoutSession_Handler,
		},
		{
			MethodName: "RetrieveCheckoutSession",
			Handler:    _CashierService_RetrieveCheckoutSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cashier.proto",
}
