root = "."
tmp_dir = "../../tmp/air/webhook"
env_files = [".env"]

[build]
  bin = "../../tmp/air/webhook/webhook"
  cmd = "go build -o ../../tmp/air/webhook/webhook ./cmd/webhook/..."
  delay = 1000
  exclude_dir = ["node_modules", "tmp", "vendor"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go"]
  include_dir = [".", "../../pkg/webhook", "../../pkg/graceful", "../../pkg/logger"]
  kill_delay = "2s"
  send_interrupt = true
  stop_on_error = true

[log]
  main_only = false
